export const StackOverflowCompareValues = {
  "Main Branch": [
    "I am a developer by profession",
    "I am learning to code",
    "I am not primarily a developer, but I write code sometimes as part of my work",
    "I code primarily as a hobby",
    "I used to be a developer by profession, but no longer am",
    "None of these",
  ],
  Employment: [
    "Employed, full-time",
    "Employed, part-time",
    "Independent contractor, freelancer, or self-employed",
    "Not employed, and not looking for work",
    "Not employed, but looking for work",
    "Retired",
    "Student, full-time",
    "Student, part-time",
    "I prefer not to say",
  ],
  "Remote Work": [
    "Full in-person",
    "Fully remote",
    "Hybrid (some remote, some in-person)",
  ],
  "Coding Activities": [
    "Bootstrapping a business",
    "Contribute to open-source projects",
    "Freelance/contract work",
    "Hobby",
    "I don’t code outside of work",
    "School or academic work",
    "Other",
  ],
  "Education Level": [
    "Primary/elementary school",
    "Secondary school",
    "Some college/university study without earning a degree",
    "Associate degree (A.A., A.S., etc.)",
    "Bachelor’s degree",
    "Master’s degree",
    "Professional degree (JD, MD, etc.)",
    "Other doctoral degree (Ph.D., Ed.D., etc.)",
    "Something else",
  ],
  "Learn Code": [
    "Books / Physical media",
    "Coding Bootcamp",
    "Colleague",
    "Friend or family member",
    "Hackathons (virtual or in-person)",
    "On the job training",
    "Online Courses or Certification",
    "School (i.e., University, College, etc)",
    "Other online resources (e.g., videos, blogs, forum)",
    "Other",
  ],
  "Learn Code Online": [
    "Blogs",
    "Certification videos",
    "Coding sessions (live or recorded)",
    "How-to videos",
    "Interactive tutorial",
    "Online books",
    "Online challenges (e.g., daily or weekly coding challenges)",
    "Online forum",
    "Programming Games",
    "Stack Overflow",
    "Technical documentation",
    "Video-based Online Courses",
    "Written Tutorials",
    "Written-based Online Courses",
    "Other",
  ],
  "Learn Code Courses Certification": [
    "Codecademy",
    "Coursera",
    "Other",
    "Pluralsight",
    "Skillsoft",
    "Udacity",
    "Udemy",
    "edX",
  ],
  "Years Code": ["<1", "1-5", "5-10", "10-20", ">20"],
  "Years Code Professionally": ["<1", "1-5", "5-10", "10-20", ">20"],
  "Developer Type": [
    "Academic researcher",
    "Blockchain",
    "Cloud infrastructure engineer",
    "Data or business analyst",
    "Data scientist or machine learning specialist",
    "Database administrator",
    "Designer",
    "DevOps specialist",
    "Developer, QA or test",
    "Developer, back-end",
    "Developer, desktop or enterprise applications",
    "Developer, embedded applications or devices",
    "Developer, front-end",
    "Developer, full-stack",
    "Developer, game or graphics",
    "Developer, mobile",
    "Educator",
    "Engineer, data",
    "Engineer, site reliability",
    "Engineering manager",
    "Marketing or sales professional",
    "Product manager",
    "Project manager",
    "Scientist",
    "Security professional",
    "Senior Executive (C-Suite, VP, etc.)",
    "Student",
    "System administrator",
    "Other",
  ],
  "Organization Size": [
    "Just me - I am a freelancer, sole proprietor, etc.",
    "2 to 9 employees",
    "10 to 19 employees",
    "20 to 99 employees",
    "100 to 499 employees",
    "500 to 999 employees",
    "1,000 to 4,999 employees",
    "5,000 to 9,999 employees",
    "10,000 or more employees",
    "I don’t know",
  ],
  "Purchase Influence": [
    "I have little or no influence",
    "I have some influence",
    "I have a great deal of influence",
  ],
  "Buy New Tool": [
    "Ask developers I know/work with",
    "Read ratings or reviews on third party sites like G2Crowd",
    "Research companies that have advertised on sites I visit",
    "Research companies that have emailed me",
    "Start a free trial",
    "Visit developer communities like Stack Overflow",
    "Other",
  ],
  Country: [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Congo, Republic of the...",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Côte d'Ivoire",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Guatemala",
    "Guinea",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong (S.A.R.)",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran, Islamic Republic of...",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Lao People's Democratic Republic",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libyan Arab Jamahiriya",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Nomadic",
    "North Korea",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Republic of Korea",
    "Republic of Moldova",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "San Marino",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan",
    "Tajikistan",
    "Thailand",
    "The former Yugoslav Republic of Macedonia",
    "Timor-Leste",
    "Togo",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom of Great Britain and Northern Ireland",
    "United Republic of Tanzania",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Venezuela, Bolivarian Republic of...",
    "Viet Nam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ],
  "Language Have Worked With": [
    "APL",
    "Assembly",
    "Bash/Shell",
    "C",
    "C++",
    "C#",
    "COBOL",
    "Clojure",
    "Crystal",
    "Dart",
    "Delphi",
    "Elixir",
    "Erlang",
    "F#",
    "Fortran",
    "Go",
    "Groovy",
    "HTML/CSS",
    "Haskell",
    "Java",
    "JavaScript",
    "Julia",
    "Kotlin",
    "LISP",
    "Lua",
    "MATLAB",
    "OCaml",
    "Objective-C",
    "PHP",
    "Perl",
    "PowerShell",
    "Python",
    "R",
    "Ruby",
    "Rust",
    "SAS",
    "SQL",
    "Scala",
    "Solidity",
    "Swift",
    "TypeScript",
    "VBA",
  ],
  "Language Want To Work With": [
    "APL",
    "Assembly",
    "Bash/Shell",
    "C",
    "C#",
    "C++",
    "COBOL",
    "Clojure",
    "Crystal",
    "Dart",
    "Delphi",
    "Elixir",
    "Erlang",
    "F#",
    "Fortran",
    "Go",
    "Groovy",
    "HTML/CSS",
    "Haskell",
    "Java",
    "JavaScript",
    "Julia",
    "Kotlin",
    "LISP",
    "Lua",
    "MATLAB",
    "OCaml",
    "Objective-C",
    "PHP",
    "Perl",
    "PowerShell",
    "Python",
    "R",
    "Ruby",
    "Rust",
    "SAS",
    "SQL",
    "Scala",
    "Solidity",
    "Swift",
    "TypeScript",
    "VBA",
  ],
  "Database Have Worked With": [
    "Cassandra",
    "Cloud Firestore",
    "CouchDB",
    "Couchbase",
    "DynamoDB",
    "Elasticsearch",
    "Firebase Realtime Database",
    "IBM DB2",
    "MariaDB",
    "Microsoft SQL Server",
    "MongoDB",
    "MySQL",
    "Neo4j",
    "Oracle",
    "PostgreSQL",
    "Redis",
    "Rust",
    "SQLite",
  ],
  "Database Want To Work With": [
    "Cassandra",
    "Cloud Firestore",
    "CouchDB",
    "Couchbase",
    "DynamoDB",
    "Elasticsearch",
    "Firebase Realtime Database",
    "IBM DB2",
    "MariaDB",
    "Microsoft SQL Server",
    "MongoDB",
    "MySQL",
    "Neo4j",
    "Oracle",
    "PostgreSQL",
    "Redis",
    "SQLite",
  ],
  "Platform Have Worked With": [
    "AWS",
    "Colocation",
    "DigitalOcean",
    "Firebase",
    "Google Cloud",
    "Heroku",
    "IBM Cloud or Watson",
    "Linode",
    "Managed Hosting",
    "Microsoft Azure",
    "OVH",
    "OpenStack",
    "Oracle Cloud Infrastructure",
    "VMware",
  ],
  "Platform Want To Work With": [
    "AWS",
    "Colocation",
    "DigitalOcean",
    "Firebase",
    "Google Cloud",
    "Heroku",
    "IBM Cloud or Watson",
    "Linode",
    "Managed Hosting",
    "Microsoft Azure",
    "OVH",
    "OpenStack",
    "Oracle Cloud Infrastructure",
    "VMware",
  ],
  "Webframe Have Worked With": [
    "ASP.NET",
    "ASP.NET Core ",
    "Angular",
    "Angular.js",
    "Blazor",
    "Deno",
    "Django",
    "Drupal",
    "Express",
    "FastAPI",
    "Fastify",
    "Flask",
    "Gatsby",
    "jQuery",
    "Laravel",
    "Next.js",
    "Node.js",
    "Nuxt.js",
    "Phoenix",
    "Play Framework",
    "React.js",
    "Ruby on Rails",
    "Svelte",
    "Symfony",
    "Vue.js",
  ],
  "Webframe Want To Work With": [
    "ASP.NET",
    "ASP.NET Core ",
    "Angular",
    "Angular.js",
    "Blazor",
    "Deno",
    "Django",
    "Drupal",
    "Express",
    "FastAPI",
    "Fastify",
    "Flask",
    "Gatsby",
    "jQuery",
    "Laravel",
    "Next.js",
    "Node.js",
    "Nuxt.js",
    "Phoenix",
    "Play Framework",
    "React.js",
    "Ruby on Rails",
    "Svelte",
    "Symfony",
    "Vue.js",
  ],
  "Miscellaneous Technology Have Worked With": [
    ".NET",
    "Apache Kafka",
    "Apache Spark",
    "Capacitor",
    "Cordova",
    "Electron",
    "Flutter",
    "GTK",
    "Hadoop",
    "Hugging Face Transformers",
    "Ionic",
    "Keras",
    "NumPy",
    "Pandas",
    "Qt",
    "React Native",
    "Scikit-learn",
    "Spring",
    "TensorFlow",
    "Tidyverse",
    "Torch/PyTorch",
    "Uno Platform",
    "Xamarin",
  ],
  "Miscellaneous Technology Want To Work With": [
    ".NET",
    "Apache Kafka",
    "Apache Spark",
    "Capacitor",
    "Cordova",
    "Electron",
    "Flutter",
    "GTK",
    "Hadoop",
    "Hugging Face Transformers",
    "Ionic",
    "Keras",
    "NumPy",
    "Pandas",
    "Qt",
    "React Native",
    "Scikit-learn",
    "Spring",
    "TensorFlow",
    "Tidyverse",
    "Torch/PyTorch",
    "Uno Platform",
    "Xamarin",
  ],
  "Tools Tech Have Worked With": [
    "Ansible",
    "Chef",
    "Docker",
    "Flow",
    "Homebrew",
    "Kubernetes",
    "npm",
    "Pulumi",
    "Puppet",
    "Terraform",
    "Unity 3D",
    "Unreal Engine",
    "Yarn",
  ],
  "Tools Tech Want To Work With": [
    "Ansible",
    "Chef",
    "Docker",
    "Flow",
    "Homebrew",
    "Kubernetes",
    "npm",
    "Pulumi",
    "Puppet",
    "Terraform",
    "Unity 3D",
    "Unreal Engine",
    "Yarn",
  ],
  "New Collab Tools Have Worked With": [
    "Android Studio",
    "Atom",
    "CLion",
    "Eclipse",
    "Emacs",
    "GoLand",
    "IPython/Jupyter",
    "IntelliJ",
    "Nano",
    "Neovim",
    "NetBeans",
    "Notepad++",
    "PhpStorm",
    "PyCharm",
    "Qt Creator",
    "RAD Studio (Delphi, C++ Builder)",
    "RStudio",
    "Rider",
    "RubyMine",
    "Spyder",
    "Sublime Text",
    "TextMate",
    "Vim",
    "Visual Studio",
    "Visual Studio Code",
    "Webstorm",
    "Xcode",
  ],
  "New Collab Tools Want To Work With": [
    "Android Studio",
    "Atom",
    "CLion",
    "Eclipse",
    "Emacs",
    "GoLand",
    "IPython/Jupyter",
    "IntelliJ",
    "Nano",
    "Neovim",
    "NetBeans",
    "Notepad++",
    "PhpStorm",
    "PyCharm",
    "Qt Creator",
    "RAD Studio (Delphi, C++ Builder)",
    "RStudio",
    "Rider",
    "RubyMine",
    "Spyder",
    "Sublime Text",
    "TextMate",
    "Vim",
    "Visual Studio",
    "Visual Studio Code",
    "Webstorm",
    "Xcode",
  ],
  "Operating System Professional use": [
    "BSD",
    "Linux-based",
    "macOS",
    "Windows",
    "Windows Subsystem for Linux (WSL)",
    "Other",
  ],
  "Operating System Personal use": [
    "BSD",
    "Linux-based",
    "macOS",
    "Windows",
    "Windows Subsystem for Linux (WSL)",
    "Other",
  ],
  "Version Control System": [
    "Git",
    "Mercurial",
    "SVN",
    "I don't use one",
    "Other",
  ],
  "Version Control Interaction": [
    "Code editor",
    "Command-line",
    "Dedicated version control GUI application",
    "Version control hosting service web GUI",
  ],
  "Office Stack Async Have Worked With": [
    "Adobe Workfront",
    "Airtable",
    "Asana",
    "Cerri",
    "ClickUp",
    "Confluence",
    "DingTalk (Teambition)",
    "Jira Work Management",
    "Leankor",
    "Microsoft Lists",
    "Microsoft Planner",
    "monday.com",
    "Notion",
    "Planview Projectplace or Clarizen",
    "Smartsheet",
    "Stack Overflow for Teams",
    "Swit",
    "Trello",
    "Wimi",
    "Workzone",
    "Wrike",
  ],
  "Office Stack Async Want To Work With": [
    "Adobe Workfront",
    "Airtable",
    "Asana",
    "Cerri",
    "ClickUp",
    "Confluence",
    "DingTalk (Teambition)",
    "Jira Work Management",
    "Leankor",
    "Microsoft Lists",
    "Microsoft Planner",
    "monday.com",
    "Notion",
    "Planview Projectplace or Clarizen",
    "Smartsheet",
    "Stack Overflow for Teams",
    "Swit",
    "Trello",
    "Wimi",
    "Workzone",
    "Wrike",
  ],
  "Office Stack Sync Have Worked With": [
    "Cisco Webex Teams",
    "Coolfire Core",
    "Google Chat",
    "Mattermost",
    "Microsoft Teams",
    "RingCentral",
    "Rocketchat",
    "Slack",
    "Symphony",
    "Unify Circuit",
    "Wickr",
    "Wire",
    "Zoom",
  ],
  "Office Stack Sync Want To Work With": [
    "Cisco Webex Teams",
    "Coolfire Core",
    "Google Chat",
    "Mattermost",
    "Microsoft Teams",
    "RingCentral",
    "Rocketchat",
    "Slack",
    "Symphony",
    "Unify Circuit",
    "Wickr",
    "Wire",
    "Zoom",
  ],
  Blockchain: [
    "Very unfavorable",
    "Unfavorable",
    "Favorable",
    "Very favorable",
    "Indifferent",
    "Unsure",
  ],
  Age: [
    "Under 18 years old",
    "18-24 years old",
    "25-34 years old",
    "35-44 years old",
    "45-54 years old",
    "55-64 years old",
    "65 years or older",
    "Prefer not to say",
  ],
  Gender: [
    "Man",
    "Woman",
    "Non-binary, genderqueer, or gender non-conforming",
    "Other (user specified)",
    "Prefer not to say",
  ],
  Trans: ["No", "Yes", "Other (user specified)", "Prefer not to say"],
  Sexuality: [
    "Bisexual",
    "Gay or Lesbian",
    "Straight / Heterosexual",
    "Queer",
    "Other (user specified)",
    "Prefer not to say",
  ],
  Ethnicity: [
    "African",
    "Asian",
    "Biracial",
    "Black",
    "Caribbean",
    "Central American",
    "Central Asian",
    "East Asian",
    "Ethnoreligious group",
    "European",
    "Hispanic or Latino/a",
    "I don't know",
    "Indian",
    "Indigenous (such as Native American or Indigenous Australian)",
    "Middle Eastern",
    "Multiracial",
    "North African",
    "North American",
    "Other (user specified)",
    "Pacific Islander",
    "Prefer not to say",
    "South American",
    "South Asian",
    "Southeast Asian",
    "White",
  ],
  Accessibility: [
    "I am blind / have difficulty seeing",
    "I am deaf / hard of hearing",
    "I am unable to / find it difficult to type",
    "I am unable to / find it difficult to walk or stand without assistance",
    "None of the above",
    "Other (user specified)",
    "Prefer not to say",
  ],
  "Mental Health": [
    "I have a concentration and/or memory disorder (e.g., ADHD, etc.)",
    "I have a mood or emotional disorder (e.g., depression, bipolar disorder, etc.)",
    "I have an anxiety disorder",
    "I have autism / an autism spectrum disorder (e.g. Asperger's, etc.)",
    "I have learning differences (e.g., Dyslexic, Dyslexia, etc.)",
    "None of the above",
    "Other (user specified)",
    "Prefer not to say",
  ],
  "Independent Contributor or People Manager": [
    "Independent contributor",
    "People manager",
  ],
  "Work Experience": ["<1", "1-5", "5-10", "10-20", ">20"],
  "Time Searching": [
    "Less than 15 minutes a day",
    "15-30 minutes a day",
    "30-60 minutes a day",
    "60-120 minutes a day",
    "Over 120 minutes a day",
  ],
};
