export const StackOverflowGroupByOptions = [
  "Age",
  "Accessibility",
  "Blockchain",
  "Buy New Tool",
  "Coding Activities",
  "Country",
  "Database Have Worked With",
  "Database Want To Work With",
  "Developer Type",
  "Education Level",
  "Employment",
  "Ethnicity",
  "Gender",
  "Independent Contributor or People Manager",
  "Language Have Worked With",
  "Language Want To Work With",
  "Learn Code",
  "Learn Code Courses Certification",
  "Learn Code Online",
  "Main Branch",
  "Mental Health",
  "Miscellaneous Technology Have Worked With",
  "Miscellaneous Technology Want To Work With",
  "New Collab Tools Have Worked With",
  "New Collab Tools Want To Work With",
  "Office Stack Async Have Worked With",
  "Office Stack Async Want To Work With",
  "Office Stack Sync Have Worked With",
  "Office Stack Sync Want To Work With",
  "Operating System Personal use",
  "Operating System Professional use",
  "Platform Have Worked With",
  "Platform Want To Work With",
  "Purchase Influence",
  "Remote Work",
  "Sexuality",
  "Time Searching",
  "Tools Tech Have Worked With",
  "Tools Tech Want To Work With",
  "Trans",
  "Version Control Interaction",
  "Version Control System",
  "Webframe Have Worked With",
  "Webframe Want To Work With",
  "Work Experience",
  "Years Code",
  "Years Code Professionally",
  "Organization Size",
];
