export const HMCompareValues = {
  Age: [
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
    "31",
    "32",
    "33",
    "34",
    "35",
    "36",
    "37",
    "38",
    "39",
    "40",
    "41",
    "42",
    "43",
    "44",
    "45",
    "46",
    "47",
    "48",
    "49",
    "50",
    "51",
    "52",
    "53",
    "54",
    "55",
    "56",
    "57",
    "58",
    "59",
    "60",
    "61",
    "62",
    "63",
    "64",
    "65",
  ],
  "Product Type Name": [
    "Accessories set",
    "Alice band",
    "Baby Bib",
    "Backpack",
    "Bag",
    "Ballerinas",
    "Beanie",
    "Belt",
    "Bikini top",
    "Blazer",
    "Blouse",
    "Bodysuit",
    "Bootie",
    "Boots",
    "Bra",
    "Bra extender",
    "Bracelet",
    "Braces",
    "Bucket hat",
    "Bumbag",
    "Cap",
    "Cap/peaked",
    "Cardigan",
    "Chem. cosmetics",
    "Clothing mist",
    "Coat",
    "Costumes",
    "Cross-body bag",
    "Cushion",
    "Dog Wear",
    "Dog wear",
    "Dress",
    "Dungarees",
    "Earring",
    "Earrings",
    "Eyeglasses",
    "Felt hat",
    "Fine cosmetics",
    "Flat shoe",
    "Flat shoes",
    "Flip flop",
    "Garment Set",
    "Giftbox",
    "Gloves",
    "Hair clip",
    "Hair string",
    "Hair ties",
    "Hair/alice band",
    "Hairband",
    "Hat/beanie",
    "Hat/brim",
    "Headband",
    "Heeled sandals",
    "Heels",
    "Hoodie",
    "Jacket",
    "Jumpsuit/Playsuit",
    "Keychain",
    "Kids Underwear top",
    "Leg warmers",
    "Leggings/Tights",
    "Long John",
    "Marker pen",
    "Mobile case",
    "Moccasins",
    "Necklace",
    "Night gown",
    "Nipple covers",
    "Other accessories",
    "Other shoe",
    "Outdoor Waistcoat",
    "Outdoor overall",
    "Outdoor trousers",
    "Polo shirt",
    "Pumps",
    "Pyjama bottom",
    "Pyjama jumpsuit/playsuit",
    "Pyjama set",
    "Ring",
    "Robe",
    "Sandals",
    "Sarong",
    "Scarf",
    "Sewing kit",
    "Shirt",
    "Shorts",
    "Shoulder bag",
    "Side table",
    "Skirt",
    "Sleeping sack",
    "Slippers",
    "Sneakers",
    "Socks",
    "Soft Toys",
    "Stain remover spray",
    "Straw hat",
    "Sunglasses",
    "Sweater",
    "Swimsuit",
    "Swimwear bottom",
    "Swimwear set",
    "Swimwear top",
    "T-shirt",
    "Tailored Waistcoat",
    "Tie",
    "Top",
    "Tote bag",
    "Towel",
    "Toy",
    "Trousers",
    "Umbrella",
    "Underdress",
    "Underwear Tights",
    "Underwear body",
    "Underwear bottom",
    "Underwear corset",
    "Underwear set",
    "Unknown",
    "Vest top",
    "Wallet",
    "Washing bag",
    "Watch",
    "Waterbottle",
    "Wedge",
    "Weekend/Gym bag",
    "Wireless earphone case",
    "Wood balls",
    "Zipper head",
  ],
  "Product Group Name": [
    "Accessories",
    "Bags",
    "Cosmetic",
    "Fun",
    "Furniture",
    "Garment Full body",
    "Garment Lower body",
    "Garment Upper body",
    "Garment and Shoe care",
    "Interior textile",
    "Items",
    "Nightwear",
    "Shoes",
    "Socks & Tights",
    "Stationery",
    "Swimwear",
    "Underwear",
    "Underwear/nightwear",
    "Unknown",
  ],
  "Graphical Appearance Name": [
    "All over pattern",
    "Application/3D",
    "Argyle",
    "Chambray",
    "Check",
    "Colour blocking",
    "Contrast",
    "Denim",
    "Dot",
    "Embroidery",
    "Front print",
    "Glittering/Metallic",
    "Hologram",
    "Jacquard",
    "Lace",
    "Melange",
    "Mesh",
    "Metallic",
    "Mixed solid/pattern",
    "Neps",
    "Other pattern",
    "Other structure",
    "Placement print",
    "Sequin",
    "Slub",
    "Solid",
    "Stripe",
    "Transparent",
    "Treatment",
    "Unknown",
  ],
  "Colour Group Name": [
    "Beige",
    "Black",
    "Blue",
    "Bronze/Copper",
    "Dark Beige",
    "Dark Blue",
    "Dark Green",
    "Dark Grey",
    "Dark Orange",
    "Dark Pink",
    "Dark Purple",
    "Dark Red",
    "Dark Turquoise",
    "Dark Yellow",
    "Gold",
    "Green",
    "Greenish Khaki",
    "Grey",
    "Greyish Beige",
    "Light Beige",
    "Light Blue",
    "Light Green",
    "Light Grey",
    "Light Orange",
    "Light Pink",
    "Light Purple",
    "Light Red",
    "Light Turquoise",
    "Light Yellow",
    "Off White",
    "Orange",
    "Other",
    "Other Blue",
    "Other Green",
    "Other Orange",
    "Other Pink",
    "Other Purple",
    "Other Red",
    "Other Turquoise",
    "Other Yellow",
    "Pink",
    "Purple",
    "Red",
    "Silver",
    "Transparent",
    "Turquoise",
    "Unknown",
    "White",
    "Yellow",
    "Yellowish Brown",
  ],
  "Perceived Colour Value Name": [
    "Bright",
    "Dark",
    "Dusty Light",
    "Light",
    "Medium",
    "Medium Dusty",
    "Undefined",
    "Unknown",
  ],
  "Perceived Colour Master Name": [
    "Beige",
    "Black",
    "Blue",
    "Bluish Green",
    "Brown",
    "Green",
    "Grey",
    "Khaki green",
    "Lilac Purple",
    "Metal",
    "Mole",
    "Orange",
    "Pink",
    "Red",
    "Turquoise",
    "Unknown",
    "White",
    "Yellow",
    "Yellowish Green",
    "undefined",
  ],
  "Department Name": [
    "AK Bottoms",
    "AK Dresses & Outdoor",
    "AK Other",
    "AK Tops Jersey & Woven",
    "AK Tops Knitwear",
    "Accessories",
    "Accessories Boys",
    "Accessories Other",
    "Asia Assortment",
    "Baby Boy Jersey Fancy",
    "Baby Boy Knitwear",
    "Baby Boy Local Relevance",
    "Baby Boy Outdoor",
    "Baby Boy Woven",
    "Baby Exclusive",
    "Baby Girl Jersey Fancy",
    "Baby Girl Knitwear",
    "Baby Girl Local Relevance",
    "Baby Girl Outdoor",
    "Baby Girl Woven",
    "Baby Nightwear",
    "Baby Shoes",
    "Baby Socks",
    "Baby Toys/Acc",
    "Baby basics",
    "Bags",
    "Bags & Items",
    "Basic 1",
    "Basics",
    "Belts",
    "Blanks",
    "Blazer",
    "Blazer S&T",
    "Blouse",
    "Blouse & Dress",
    "Boots",
    "Bottoms",
    "Bottoms Boys",
    "Bottoms Girls",
    "Boys Local Relevance",
    "Boys Small Acc & Bags",
    "Campaigns",
    "Casual Lingerie",
    "Clean Lingerie",
    "Conscious Exclusive",
    "Denim Other Garments",
    "Denim Trousers",
    "Denim shorts",
    "Denim trousers",
    "Denim wardrobe H&M man inactive from S.6",
    "Divided Shoes",
    "Divided Swimwear",
    "Divided+",
    "Divided+ inactive from s.1",
    "Dress",
    "Dress-up Boys",
    "Dresses",
    "Dresses DS",
    "EQ & Special Collections",
    "EQ Divided Basics",
    "EQ Divided Blue",
    "EQ H&M Man",
    "EQ Ladies Denim",
    "Equatorial",
    "Equatorial Assortment",
    "Everyday Waredrobe Denim",
    "Expressive Lingerie",
    "Flats",
    "Functional Lingerie",
    "Girls Local Relevance",
    "Girls Projects",
    "Girls Small Acc/Bags",
    "Gloves/Hats",
    "Hair Accessories",
    "Heavy Basic Jersey",
    "Heels",
    "Jacket",
    "Jacket Casual",
    "Jacket Smart",
    "Jacket Street",
    "Jackets",
    "Jersey",
    "Jersey Basic",
    "Jersey Fancy",
    "Jersey Fancy DS",
    "Jersey License",
    "Jersey Occasion",
    "Jersey fancy",
    "Jersey inactive from s1",
    "Jersey/Knitwear Premium",
    "Jewellery",
    "Jewellery Extended",
    "Kids Boy Big Acc",
    "Kids Boy Denim",
    "Kids Boy Exclusive",
    "Kids Boy Jersey Basic",
    "Kids Boy Jersey Fancy",
    "Kids Boy Knitwear",
    "Kids Boy Outdoor",
    "Kids Boy Shirt",
    "Kids Boy Shoes",
    "Kids Boy Shorts",
    "Kids Boy Socks",
    "Kids Boy Swimwear",
    "Kids Boy Trouser",
    "Kids Boy UW/NW",
    "Kids Dress-up/Football",
    "Kids Girl Big Acc",
    "Kids Girl Denim",
    "Kids Girl Dresses",
    "Kids Girl Exclusive",
    "Kids Girl Jersey Basic",
    "Kids Girl Jersey Fancy",
    "Kids Girl Knitwear",
    "Kids Girl License",
    "Kids Girl Outdoor",
    "Kids Girl S&T",
    "Kids Girl Shoes",
    "Kids Girl Swimwear",
    "Kids Girl Trouser",
    "Kids Girl UW/NW",
    "Knit & Woven",
    "Knitwear",
    "Knitwear Basic",
    "Knitwear inactive from s1",
    "Ladies Sport Acc",
    "Ladies Sport Bottoms",
    "Ladies Sport Bras",
    "Ladies Sport Woven",
    "License",
    "Light Basic Jersey",
    "Limited Edition",
    "Local relevance",
    "Loungewear",
    "Mama Lingerie",
    "Men Sport Acc",
    "Men Sport Bottoms",
    "Men Sport Tops",
    "Men Sport Woven",
    "Newborn",
    "Nightwear",
    "Nursing",
    "OL Extended Sizes",
    "On Demand",
    "Other Accessories",
    "Other items",
    "Outdoor inactive from s1",
    "Outdoor/Blazers",
    "Outdoor/Blazers DS",
    "Outwear",
    "Outwear & Blazers",
    "Premium Quality",
    "Price Items",
    "Projects",
    "Projects Dresses",
    "Projects Jersey & Knitwear",
    "Projects Woven Bottoms",
    "Projects Woven Tops",
    "Promotion / Other / Offer",
    "Promotion/ Other /Offer",
    "Promotion/Other/Offer",
    "Read & React",
    "Scarves",
    "Shirt",
    "Shirt S&T",
    "Shoes",
    "Shoes / Boots inactive from s5",
    "Shoes Other",
    "Shopbasket Lingerie",
    "Shopbasket Socks",
    "Shorts",
    "Shorts & Skirts",
    "Shorts DS",
    "Skirt",
    "Skirts",
    "Skirts DS",
    "Small Acc. Jewellery & Other",
    "Small Accessories",
    "Small Accessories Extended",
    "Small Bags",
    "Sneakers",
    "Sneakers big girl inactive from s2",
    "Sneakers small girl inactive from s2",
    "Socks",
    "Socks Bin",
    "Socks Wall",
    "Special Collection",
    "Studio Collection",
    "Suit",
    "Suit jacket",
    "Sunglasses",
    "Swimwear",
    "Take Care External",
    "Take care",
    "Test Ladies",
    "Tights basic",
    "Tops & Bottoms Other",
    "Tops Boys",
    "Tops Fancy Jersey",
    "Tops Girls",
    "Tops Knitwear",
    "Tops Knitwear DS",
    "Tops Woven",
    "Tops woven DS",
    "Trouser",
    "Trouser S&T",
    "Trousers",
    "Trousers & Skirt",
    "Trousers DS",
    "UW",
    "Underwear Jersey",
    "Underwear Woven",
    "Woven",
    "Woven Occasion",
    "Woven Premium",
    "Woven Tops",
    "Woven bottoms",
    "Woven inactive from s1",
    "Woven top",
    "Young Boy Big Acc",
    "Young Boy Denim",
    "Young Boy Jersey Basic",
    "Young Boy Jersey Fancy",
    "Young Boy Knitwear",
    "Young Boy Outdoor",
    "Young Boy Shirt",
    "Young Boy Shoes",
    "Young Boy Shorts",
    "Young Boy Socks",
    "Young Boy Trouser",
    "Young Boy UW/NW",
    "Young Girl Big Acc",
    "Young Girl Denim",
    "Young Girl Dresses",
    "Young Girl Jersey Basic",
    "Young Girl Jersey Fancy",
    "Young Girl Knitwear",
    "Young Girl Outdoor",
    "Young Girl S&T",
    "Young Girl Shoes",
    "Young Girl Swimwear",
    "Young Girl Trouser",
    "Young Girl UW/NW",
    "Young boy Swimwear",
  ],
  "Index Name": [
    "Baby Sizes 50-98",
    "Children Accessories, Swimwear",
    "Children Sizes 134-170",
    "Children Sizes 92-140",
    "Divided",
    "Ladies Accessories",
    "Ladieswear",
    "Lingeries/Tights",
    "Menswear",
    "Sport",
  ],
  "Index Group Name": [
    "Baby/Children",
    "Divided",
    "Ladieswear",
    "Menswear",
    "Sport",
  ],
  "Section Name": [
    "Baby Boy",
    "Baby Essentials & Complements",
    "Baby Girl",
    "Boys Underwear & Basics",
    "Collaborations",
    "Contemporary Casual",
    "Contemporary Smart",
    "Contemporary Street",
    "Denim Men",
    "Divided Accessories",
    "Divided Asia keys",
    "Divided Basics",
    "Divided Collection",
    "Divided Complements Other",
    "Divided Projects",
    "Divided Selected",
    "EQ Divided",
    "Girls Underwear & Basics",
    "H&M+",
    "Kids & Baby Shoes",
    "Kids Accessories, Swimwear & D",
    "Kids Boy",
    "Kids Girl",
    "Kids Local Relevance",
    "Kids Outerwear",
    "Kids Sports",
    "Ladies Denim",
    "Ladies H&M Sport",
    "Ladies Other",
    "Mama",
    "Men Accessories",
    "Men Edition",
    "Men H&M Sport",
    "Men Other",
    "Men Other 2",
    "Men Project",
    "Men Shoes",
    "Men Suits & Tailoring",
    "Men Underwear",
    "Mens Outerwear",
    "Special Collections",
    "Womens Big accessories",
    "Womens Casual",
    "Womens Everyday Basics",
    "Womens Everyday Collection",
    "Womens Jackets",
    "Womens Lingerie",
    "Womens Nightwear, Socks & Tigh",
    "Womens Premium",
    "Womens Shoes",
    "Womens Small accessories",
    "Womens Swimwear, beachwear",
    "Womens Tailoring",
    "Womens Trend",
    "Young Boy",
    "Young Girl",
  ],
  "Garment Group Name": [
    "Accessories",
    "Blouses",
    "Dressed",
    "Dresses Ladies",
    "Dresses/Skirts girls",
    "Jersey Basic",
    "Jersey Fancy",
    "Knitwear",
    "Outdoor",
    "Shirts",
    "Shoes",
    "Shorts",
    "Skirts",
    "Socks and Tights",
    "Special Offers",
    "Swimwear",
    "Trousers",
    "Trousers Denim",
    "Under-, Nightwear",
    "Unknown",
    "Woven/Jersey/Knitted mix Baby",
  ],
  "Sales Channel ID": ["1", "2"],
  fn: ["0.0", "1.0"],
  Active: ["1.0", "0.0"],
  "Club Member Status": ["ACTIVE", "LEFT CLUB", "PRE-CREATE"],
  "Fashion News Frequency": ["Monthly", "NONE", "Regularly"],
  "Day of Month": [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
    "31",
  ],
};
