export const HMGroupByOptions = [
  "active",
  "age",
  "club member status",
  "colour group name",
  "day of month",
  "department name",
  "fashion news frequency",
  "fn",
  "garment group name",
  "graphical appearance name",
  "index group name",
  "index name",
  "perceived colour master name",
  "perceived colour value name",
  "product group name",
  "product type name",
  "sales channel id",
  "section name",
];
