export const ASC7CompareValues = {
  "Georgraphic division": [
    "Middle Atlantic (Northeast region)",
    "East North Central (Midwest region)",
    "South Atlantic (South region)",
    "West South Central (South Region)",
    "Pacific (West region)",
  ],
  "Person Number in household": [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
  ],
  "Public use microdata area code": [
    "100",
    "101",
    "102",
    "103",
    "104",
    "105",
    "106",
    "107",
    "108",
    "109",
    "110",
    "200",
    "202",
    "300",
    "400",
    "401",
    "402",
    "403",
    "500",
    "501",
    "502",
    "600",
    "700",
    "701",
    "702",
    "703",
    "704",
    "800",
    "801",
    "802",
    "803",
    "900",
    "901",
    "902",
    "903",
    "904",
    "905",
    "906",
    "907",
    "908",
    "909",
    "910",
    "1000",
    "1001",
    "1100",
    "1101",
    "1102",
    "1103",
    "1104",
    "1105",
    "1106",
    "1107",
    "1108",
    "1109",
    "1110",
    "1111",
    "1112",
    "1113",
    "1114",
    "1200",
    "1201",
    "1202",
    "1203",
    "1204",
    "1205",
    "1206",
    "1207",
    "1300",
    "1301",
    "1302",
    "1303",
    "1304",
    "1305",
    "1306",
    "1307",
    "1308",
    "1309",
    "1400",
    "1500",
    "1501",
    "1502",
    "1600",
    "1602",
    "1700",
    "1701",
    "1702",
    "1800",
    "1801",
    "1802",
    "1803",
    "1804",
    "1805",
    "1806",
    "1807",
    "1900",
    "1901",
    "1902",
    "1903",
    "1904",
    "1905",
    "1906",
    "1907",
    "2000",
    "2001",
    "2002",
    "2003",
    "2004",
    "2005",
    "2006",
    "2100",
    "2101",
    "2102",
    "2103",
    "2200",
    "2201",
    "2202",
    "2203",
    "2300",
    "2301",
    "2302",
    "2303",
    "2304",
    "2305",
    "2306",
    "2307",
    "2308",
    "2309",
    "2310",
    "2311",
    "2312",
    "2313",
    "2314",
    "2315",
    "2316",
    "2317",
    "2318",
    "2319",
    "2320",
    "2321",
    "2322",
    "2400",
    "2401",
    "2402",
    "2500",
    "2501",
    "2502",
    "2503",
    "2504",
    "2505",
    "2506",
    "2507",
    "2508",
    "2509",
    "2510",
    "2511",
    "2512",
    "2513",
    "2514",
    "2515",
    "2516",
    "2600",
    "2601",
    "2700",
    "2701",
    "2702",
    "2703",
    "2800",
    "2801",
    "2802",
    "2803",
    "2900",
    "2901",
    "2902",
    "2903",
    "2904",
    "2905",
    "3000",
    "3001",
    "3002",
    "3003",
    "3004",
    "3005",
    "3007",
    "3008",
    "3009",
    "3100",
    "3101",
    "3102",
    "3103",
    "3104",
    "3105",
    "3106",
    "3107",
    "3108",
    "3200",
    "3201",
    "3202",
    "3203",
    "3204",
    "3205",
    "3206",
    "3207",
    "3208",
    "3209",
    "3210",
    "3211",
    "3212",
    "3300",
    "3301",
    "3302",
    "3303",
    "3304",
    "3305",
    "3306",
    "3307",
    "3308",
    "3309",
    "3310",
    "3311",
    "3312",
    "3313",
    "3400",
    "3401",
    "3402",
    "3403",
    "3404",
    "3407",
    "3408",
    "3409",
    "3410",
    "3411",
    "3412",
    "3413",
    "3414",
    "3415",
    "3416",
    "3417",
    "3418",
    "3419",
    "3420",
    "3421",
    "3422",
    "3500",
    "3501",
    "3502",
    "3503",
    "3504",
    "3520",
    "3521",
    "3522",
    "3523",
    "3524",
    "3525",
    "3526",
    "3527",
    "3528",
    "3529",
    "3530",
    "3531",
    "3532",
    "3600",
    "3601",
    "3602",
    "3603",
    "3700",
    "3701",
    "3702",
    "3703",
    "3704",
    "3705",
    "3706",
    "3707",
    "3708",
    "3709",
    "3710",
    "3711",
    "3712",
    "3713",
    "3714",
    "3715",
    "3716",
    "3717",
    "3718",
    "3719",
    "3720",
    "3721",
    "3722",
    "3723",
    "3724",
    "3725",
    "3726",
    "3727",
    "3728",
    "3729",
    "3730",
    "3731",
    "3732",
    "3733",
    "3734",
    "3735",
    "3736",
    "3737",
    "3738",
    "3739",
    "3740",
    "3741",
    "3742",
    "3743",
    "3744",
    "3745",
    "3746",
    "3747",
    "3748",
    "3749",
    "3750",
    "3751",
    "3752",
    "3753",
    "3754",
    "3755",
    "3756",
    "3757",
    "3758",
    "3759",
    "3760",
    "3761",
    "3762",
    "3763",
    "3764",
    "3765",
    "3766",
    "3767",
    "3768",
    "3769",
    "3800",
    "3801",
    "3802",
    "3803",
    "3804",
    "3805",
    "3806",
    "3807",
    "3808",
    "3809",
    "3810",
    "3900",
    "3901",
    "3902",
    "3903",
    "4000",
    "4001",
    "4002",
    "4003",
    "4004",
    "4005",
    "4006",
    "4007",
    "4008",
    "4009",
    "4010",
    "4011",
    "4012",
    "4013",
    "4014",
    "4015",
    "4016",
    "4017",
    "4018",
    "4100",
    "4101",
    "4102",
    "4103",
    "4104",
    "4105",
    "4106",
    "4107",
    "4108",
    "4109",
    "4110",
    "4111",
    "4112",
    "4113",
    "4114",
    "4200",
    "4300",
    "4301",
    "4302",
    "4400",
    "4500",
    "4501",
    "4502",
    "4503",
    "4504",
    "4601",
    "4602",
    "4603",
    "4604",
    "4605",
    "4606",
    "4607",
    "4608",
    "4609",
    "4610",
    "4611",
    "4612",
    "4613",
    "4614",
    "4615",
    "4616",
    "4617",
    "4618",
    "4619",
    "4620",
    "4621",
    "4622",
    "4623",
    "4624",
    "4625",
    "4626",
    "4627",
    "4628",
    "4629",
    "4630",
    "4631",
    "4632",
    "4633",
    "4634",
    "4635",
    "4636",
    "4637",
    "4638",
    "4700",
    "4701",
    "4702",
    "4800",
    "4801",
    "4802",
    "4803",
    "4900",
    "4901",
    "4902",
    "4903",
    "4904",
    "4905",
    "5000",
    "5100",
    "5200",
    "5201",
    "5202",
    "5203",
    "5204",
    "5301",
    "5302",
    "5303",
    "5304",
    "5305",
    "5306",
    "5307",
    "5308",
    "5309",
    "5400",
    "5401",
    "5402",
    "5403",
    "5500",
    "5501",
    "5502",
    "5503",
    "5504",
    "5505",
    "5506",
    "5507",
    "5600",
    "5700",
    "5701",
    "5702",
    "5703",
    "5704",
    "5705",
    "5706",
    "5707",
    "5708",
    "5800",
    "5901",
    "5902",
    "5903",
    "5904",
    "5905",
    "5906",
    "5907",
    "5908",
    "5909",
    "5910",
    "5911",
    "5912",
    "5913",
    "5914",
    "5915",
    "5916",
    "5917",
    "5918",
    "6000",
    "6100",
    "6101",
    "6102",
    "6103",
    "6200",
    "6300",
    "6301",
    "6302",
    "6400",
    "6500",
    "6501",
    "6502",
    "6503",
    "6504",
    "6505",
    "6506",
    "6507",
    "6508",
    "6509",
    "6510",
    "6511",
    "6512",
    "6513",
    "6514",
    "6515",
    "6601",
    "6602",
    "6603",
    "6701",
    "6702",
    "6703",
    "6704",
    "6705",
    "6706",
    "6707",
    "6708",
    "6709",
    "6710",
    "6711",
    "6712",
    "6801",
    "6802",
    "6803",
    "6804",
    "6805",
    "6806",
    "6807",
    "6900",
    "6901",
    "6902",
    "6903",
    "7101",
    "7102",
    "7103",
    "7104",
    "7105",
    "7106",
    "7107",
    "7108",
    "7109",
    "7110",
    "7111",
    "7112",
    "7113",
    "7114",
    "7115",
    "7300",
    "7301",
    "7302",
    "7303",
    "7304",
    "7305",
    "7306",
    "7307",
    "7308",
    "7309",
    "7310",
    "7311",
    "7312",
    "7313",
    "7314",
    "7315",
    "7316",
    "7317",
    "7318",
    "7319",
    "7320",
    "7321",
    "7322",
    "7501",
    "7502",
    "7503",
    "7504",
    "7505",
    "7506",
    "7507",
    "7701",
    "7702",
    "7703",
    "7704",
    "7901",
    "7902",
    "8101",
    "8102",
    "8103",
    "8104",
    "8105",
    "8106",
    "8301",
    "8302",
    "8303",
    "8500",
    "8501",
    "8502",
    "8503",
    "8504",
    "8505",
    "8506",
    "8507",
    "8508",
    "8509",
    "8510",
    "8511",
    "8512",
    "8513",
    "8514",
    "8601",
    "8602",
    "8603",
    "8604",
    "8605",
    "8606",
    "8607",
    "8608",
    "8609",
    "8610",
    "8611",
    "8612",
    "8613",
    "8614",
    "8615",
    "8616",
    "8617",
    "8618",
    "8619",
    "8620",
    "8621",
    "8622",
    "8623",
    "8624",
    "8700",
    "8701",
    "8702",
    "8900",
    "9100",
    "9300",
    "9501",
    "9502",
    "9503",
    "9504",
    "9505",
    "9506",
    "9507",
    "9508",
    "9509",
    "9510",
    "9701",
    "9702",
    "9703",
    "9901",
    "9902",
    "9903",
    "9904",
    "9905",
    "9906",
    "9907",
    "9908",
    "9909",
    "9910",
    "9911",
    "10100",
    "10101",
    "10102",
    "10103",
    "10104",
    "10301",
    "10302",
    "10303",
    "10304",
    "10305",
    "10306",
    "10307",
    "10308",
    "10501",
    "10502",
    "10503",
    "10504",
    "10700",
    "10701",
    "10702",
    "10703",
    "10900",
    "11101",
    "11102",
    "11103",
    "11104",
    "11105",
    "11106",
    "11300",
    "11501",
    "11502",
    "11503",
    "11701",
    "11702",
    "11703",
    "11704",
    "12100",
    "12701",
    "12702",
    "12703",
    "12704",
  ],
  Region: ["Northeast", "Midwest", "South", "West"],
  "State code": [
    "California",
    "Florida",
    "Illinois",
    "New York",
    "Ohio",
    "Pennsylvania",
    "Texas",
  ],
  "Citizenship status": [
    "Born in the U.S.",
    "Born in Puerto Rico, Guam, the U.S. Virgin Islands, or the Northern Marianas",
    "Born abroad of American parent(s)",
    "U.S. citizen by naturalization",
    "Not a citizen of the U.S.",
  ],
  "Class of Worker": [
    "Employee of a private for-profit company or business, or of an individual, for wages, salary, or commissions",
    "Employee of a private not-for-profit, tax-exempt, or charitable organization",
    "Local government employee (city, county, etc.)",
    "State government employee",
    "Federal government employee",
    "Self-employed in own not incorporated business, professional practice, or farm",
    "Self-employed in own incorporated business, professional practice or farm",
    "Working without pay in family business or farm",
    "Unemployed and last worked 5 years ago or earlier or never worked",
  ],
  "Self-care difficulty": ["yes", "no"],
  "Hearing difficulty": ["yes", "no"],
  "Vision difficulty": ["yes", "no"],
  "Independent living difficulty": ["yes", "no"],
  "Ambulatory difficulty": ["yes", "no"],
  "Veteran Service Disability Rating (percentage)": [
    "O percent",
    "10 or 20 percent",
    "30 or 40 percent",
    "50 or 60 percent",
    "70, 80, 90, or 100 percent",
    "Not Reported",
  ],
  "Veteran Service Disability Rating (checkbox)": ["yes", "no"],
  "Cognitive difficulty": ["yes", "no"],
  "Ability to speak English": ["Very well", "Well", "Not well", "Not at all"],
  "Gave birth within past year": ["yes", "no"],
  "Grandparents living with grandchildren": ["yes", "no"],
  "Length of time responsible for grandchildren": [
    "Less than 6 months",
    "6 to 11 months",
    "1 or 2 years",
    "3 or 4 years",
    "5 or more years",
  ],
  "Responsible for grandchildren": ["yes", "no"],
  "Insurance through a current or former employer or union": ["yes", "no"],
  "Insurance purchased directly from an insurance company": ["yes", "no"],
  "Medicare, for people 65 and older, or people with certain disabilities": [
    "yes",
    "no",
  ],
  "Medicaid, Medical Assistance, or any kind of government-assistance plan for those with low incomes or a disability":
    ["yes", "no"],
  "TRICARE or other military health care": ["yes", "no"],
  "VA (Health Insurance through VA Health Care)": ["yes", "no"],
  "Indian Health Service": ["yes", "no"],
  "Vehicle occupancy (to work)": [
    "Drove alone",
    "In 2-person carpool",
    "In 3-person carpool",
    "In 4-person carpool",
    "In 5-person carpool",
    "In 6-person carpool",
    "In 7-person carpool",
    "In 8-person carpool",
    "In 9-person carpool",
    "In 10-person or more carpool",
  ],
  "Means of transportation to work": [
    "Car, truck, or van",
    "Bus or trolley bus",
    "Streetcar or trolley car (carro publico in PR)",
    "Subway or elevated",
    "Railroad",
    "Ferryboat",
    "Taxicab",
    "Motorcycle",
    "Bicycle",
    "Walked",
    "Worked from home",
    "Other method",
  ],
  "Language other than English spoken at home": ["yes", "no"],
  "Marital status": [
    "Married",
    "Widowed",
    "Divorced",
    "Separated",
    "Never Married",
  ],
  "Divorced in the past 12 months": ["Yes", "No"],
  "Married in the past 12 months": ["yes", "no"],
  "Number of times married": ["1.0", "2.0", "3.0"],
  "Widowed in the past 12 months": ["yes", "no"],
  "Mobility status (lived here 1 year ago)": [
    "Yes, same house (nonmovers)",
    "No, outside of US and Puerto Rico",
    "No, different house in US or Puerto Rico",
  ],
  "Military service": [
    "Now on active duty",
    "On active duty in the past, but not now",
    "Only on active duty for training in Reserves/National Guard",
    "Never served in the military",
  ],
  "Served September 2001 or later": ["no", "yes"],
  "Served August 1990 - August 2001 (including Persian Gulf War)": [
    "no",
    "yes",
  ],
  "Served May 1975 - July 1990": ["no", "yes"],
  "Served Vietnam era (August 1964 - April 1975)": ["no", "yes"],
  "Served February 1955 - July 1964": ["no", "yes"],
  "Served Korean War (July 1950 - January 1955)": ["no", "yes"],
  "Served January 1947 - June 1950": ["no", "yes"],
  "Served World War II (December 1941 - December 1946)": ["no", "yes"],
  "Served November 1941 or earlier": ["no", "yes"],
  "Temporary absence from work": ["Yes", "No", "Did not report"],
  "Available for Work": [
    "Yes",
    "No, temporarily ill",
    "No, other reasons",
    "No, unspecified",
    "Did not report",
  ],
  "On layoff from work": ["Yes", "No", "Did not report"],
  "Looking for work": ["Yes", "No", "Did not report"],
  "Informed of recall": ["Yes", "No", "Did not report"],
  "Relationship to reference person": [
    "Reference person",
    "Husband/wife",
    "Biological son or daughter",
    "Adopted son or daughter",
    "Stepson or stepdaughter",
    "Brother or sister",
    "Father or mother",
    "Grandchild",
    "Parent-in-law",
    "Son-in-law or daughter-in-law",
    "Other relative",
    "Roomer or boarder",
    "Housemate or roommate",
    "Unmarried partner",
    "Foster child",
    "Other nonrelative",
    "Institutionalized group quarters population",
    "Noninstitutionalized group quarters population",
  ],
  "School enrollment": [
    "No, has not attended in the last 3 months",
    "Yes, public school or public college",
    "Yes, private school, private college, or home school",
  ],
  "Grade level attending": [
    "Nursery school/preschool",
    "Kindergarten",
    "Grade 1",
    "Grade 2",
    "Grade 3",
    "Grade 4",
    "Grade 5",
    "Grade 6",
    "Grade 7",
    "Grade 8",
    "Grade 9",
    "Grade 10",
    "Grade 11",
    "Grade 12",
    "College undergraduate years (freshman to senior)",
    "Graduate or professional school beyond a bachelor's degree",
  ],
  "Educational attainment": [
    "No schooling completed",
    "Nursery school, preschool",
    "Kindergarten",
    "Grade 1",
    "Grade 2",
    "Grade 3",
    "Grade 4",
    "Grade 5",
    "Grade 6",
    "Grade 7",
    "Grade 8",
    "Grade 9",
    "Grade 10",
    "Grade 11",
    "12th grade - no diploma",
    "Regular high school diploma",
    "GED or alternative credential",
    "Some college, but less than 1 year",
    "1 or more years of college credit, no degree",
    "Associate's degree",
    "Bachelor's degree",
    "Master's degree",
    "Professional degree beyond a bachelor's degree",
    "Doctorate degree",
  ],
  Sex: ["Man", "Woman"],
  "When last worked": [
    "Within past year",
    "1-5 yrs ago",
    "Over 5 yrs ago or never worked",
  ],
  "Weeks worked during past 12 months": [
    "50 to 52 weeks worked during past 12 months",
    "48 to 49 weeks worked during past 12 months",
    "40 to 47 weeks worked during past 12 months",
    "27 to 39 weeks worked during past 12 month",
    "14 to 26 weeks worked during past 12 months",
    "13 weeks or less worked during past 12 months",
  ],
  "Worked last week": ["yes", "no"],
  "Ancestry recode": ["Single", "Multiple", "Unclassified", "Not Reported"],
  "Ancestry recode - first entry": [
    "Alsatian",
    "Austrian",
    "Basque",
    "Belgian",
    "Flemish",
    "British",
    "British Isles",
    "Danish",
    "Dutch",
    "English",
    "Finnish",
    "French",
    "German",
    "Prussian",
    "Greek",
    "Icelander",
    "Irish",
    "Italian",
    "Sicilian",
    "Luxembourger",
    "Maltese",
    "Norwegian",
    "Portuguese",
    "Scotch Irish",
    "Scottish",
    "Swedish",
    "Swiss",
    "Irish Scotch",
    "Welsh",
    "Scandinavian",
    "Celtic",
    "Albanian",
    "Belorussian",
    "Bulgarian",
    "Croatian",
    "Czech",
    "Bohemian",
    "Czechoslovakian",
    "Estonian",
    "German Russian",
    "Rom",
    "Hungarian",
    "Latvian",
    "Lithuanian",
    "Macedonian",
    "Montenegrin",
    "Polish",
    "Romanian",
    "Moldavian",
    "Russian",
    "Serbian",
    "Slovak",
    "Slovene",
    "Turkestani",
    "Uzbeg",
    "Georgia CIS",
    "Ukrainian",
    "Yugoslavian",
    "Bosnian and Herzegovinian",
    "Slavic",
    "Slavonian",
    "Central European",
    "Northern European",
    "Southern European",
    "Western European",
    "Eastern European",
    "Germanic",
    "European",
    "Spaniard",
    "Mexican",
    "Mexican American",
    "Mexicano",
    "Chicano",
    "Mexican American Indian",
    "Mexican State",
    "Mexican Indian",
    "Costa Rican",
    "Guatemalan",
    "Honduran",
    "Nicaraguan",
    "Panamanian",
    "Salvadoran",
    "Central American",
    "Argentinean",
    "Bolivian",
    "Chilean",
    "Colombian",
    "Ecuadorian",
    "Paraguayan",
    "Peruvian",
    "Uruguayan",
    "Venezuelan",
    "South American",
    "Latin American",
    "Latin",
    "Latino",
    "Puerto Rican",
    "Cuban",
    "Dominican",
    "Hispanic",
    "Spanish",
    "Spanish American",
    "Bahamian",
    "Barbadian",
    "Belizean",
    "Jamaican",
    "Dutch West Indian",
    "Trinidadian Tobagonian",
    "British West Indian",
    "Antigua and Barbuda",
    "Grenadian",
    "Vincent-Grenadine Islander",
    "St Lucia Islander",
    "West Indian",
    "Haitian",
    "Other West Indian",
    "Brazilian",
    "Guyanese",
    "Algerian",
    "Egyptian",
    "Libyan (2017 or later)",
    "Moroccan",
    "North African",
    "Iranian",
    "Iraqi",
    "Israeli",
    "Jordanian",
    "Kuwaiti (2017 or later)",
    "Lebanese",
    "Saudi Arabian",
    "Syrian",
    "Armenian",
    "Turkish",
    "Yemeni",
    "Kurdish",
    "Palestinian",
    "Assyrian",
    "Chaldean",
    "Mideast",
    "Arab",
    "Arabic",
    "Other Arab",
    "Cameroonian",
    "Cape Verdean",
    "Congolese",
    "Ethiopian",
    "Eritrean",
    "Gambian (2017 or later)",
    "Ghanaian",
    "Guinean (2017 or later)",
    "Kenyan",
    "Liberian",
    "Nigerian",
    "Senegalese",
    "Sierra Leonean",
    "Somali",
    "South African",
    "Sudanese",
    "Togo (2017 or later)",
    "Other Subsaharan African",
    "Ugandan",
    "Zimbabwean (2017 or later)",
    "Western African",
    "African",
    "Afghan",
    "Bangladeshi",
    "Bhutanese",
    "Nepali",
    "Asian Indian",
    "Bengali",
    "East Indian",
    "Punjabi",
    "Pakistani",
    "Sri Lankan",
    "Burmese",
    "Cambodian",
    "Chinese",
    "Cantonese",
    "Mongolian",
    "Tibetan",
    "Hong Kong (2017 or later)",
    "Filipino",
    "Indonesian",
    "Japanese",
    "Okinawan",
    "Korean",
    "Laotian",
    "Hmong",
    "Malaysian",
    "Thai",
    "Taiwanese",
    "Vietnamese",
    "Asian",
    "Other Asian",
    "Australian",
    "New Zealander",
    "Polynesian",
    "Hawaiian",
    "Samoan",
    "Tongan",
    "Micronesian",
    "Guamanian",
    "Chamorro",
    "Palauan (2017 or later)",
    "Marshallese",
    "Fijian",
    "Pacific Islander",
    "Other Pacific",
    "Afro American",
    "Afro",
    "African American",
    "Black",
    "Negro",
    "Creole",
    "Central American Indian",
    "South American Indian",
    "Native American",
    "Indian",
    "Cherokee",
    "American Indian",
    "Eskimo",
    "White",
    "Anglo",
    "Appalachian",
    "Pennsylvania German",
    "Canadian",
    "French Canadian",
    "Acadian (2017 or later)",
    "Cajun",
    "American",
    "United States",
    "New Mexico (2017 or later)",
    "Texas",
    "North American",
    "Mixture",
    "Uncodable entries",
    "Other groups",
    "Other responses",
    "Not reported",
  ],
  "Ancestry recode - second entry": [
    "Alsatian",
    "Austrian",
    "Basque",
    "Belgian",
    "Flemish",
    "British",
    "British Isles",
    "Danish",
    "Dutch",
    "English",
    "Finnish",
    "French",
    "German",
    "Prussian",
    "Greek",
    "Icelander",
    "Irish",
    "Italian",
    "Sicilian",
    "Luxembourger",
    "Maltese",
    "Norwegian",
    "Portuguese",
    "Scotch Irish",
    "Scottish",
    "Swedish",
    "Swiss",
    "Irish Scotch",
    "Welsh",
    "Scandinavian",
    "Celtic",
    "Albanian",
    "Belorussian",
    "Bulgarian",
    "Croatian",
    "Czech",
    "Bohemian",
    "Czechoslovakian",
    "Estonian",
    "German Russian",
    "Rom",
    "Hungarian",
    "Latvian",
    "Lithuanian",
    "Macedonian",
    "Montenegrin",
    "Polish",
    "Romanian",
    "Moldavian",
    "Russian",
    "Serbian",
    "Slovak",
    "Slovene",
    "Turkestani",
    "Uzbeg",
    "Georgia CIS",
    "Ukrainian",
    "Yugoslavian",
    "Bosnian and Herzegovinian",
    "Slavic",
    "Slavonian",
    "Central European",
    "Northern European",
    "Southern European",
    "Western European",
    "Eastern European",
    "Germanic",
    "European",
    "Spaniard",
    "Mexican",
    "Mexican American",
    "Mexicano",
    "Chicano",
    "Mexican American Indian",
    "Mexican State",
    "Mexican Indian",
    "Costa Rican",
    "Guatemalan",
    "Honduran",
    "Nicaraguan",
    "Panamanian",
    "Salvadoran",
    "Central American",
    "Argentinean",
    "Bolivian",
    "Chilean",
    "Colombian",
    "Ecuadorian",
    "Paraguayan",
    "Peruvian",
    "Uruguayan",
    "Venezuelan",
    "South American",
    "Latin American",
    "Latin",
    "Latino",
    "Puerto Rican",
    "Cuban",
    "Dominican",
    "Hispanic",
    "Spanish",
    "Spanish American",
    "Bahamian",
    "Barbadian",
    "Belizean",
    "Jamaican",
    "Dutch West Indian",
    "Trinidadian Tobagonian",
    "British West Indian",
    "Antigua and Barbuda",
    "Grenadian",
    "Vincent-Grenadine Islander",
    "St Lucia Islander",
    "West Indian",
    "Haitian",
    "Other West Indian",
    "Brazilian",
    "Guyanese",
    "Algerian",
    "Egyptian",
    "Libyan (2017 or later)",
    "Moroccan",
    "North African",
    "Iranian",
    "Iraqi",
    "Israeli",
    "Jordanian",
    "Kuwaiti (2017 or later)",
    "Lebanese",
    "Saudi Arabian",
    "Syrian",
    "Armenian",
    "Turkish",
    "Yemeni",
    "Kurdish",
    "Palestinian",
    "Assyrian",
    "Chaldean",
    "Mideast",
    "Arab",
    "Arabic",
    "Other Arab",
    "Cameroonian",
    "Cape Verdean",
    "Congolese",
    "Ethiopian",
    "Eritrean",
    "Ghanaian",
    "Guinean (2017 or later)",
    "Kenyan",
    "Liberian",
    "Nigerian",
    "Senegalese",
    "Sierra Leonean",
    "Somali",
    "South African",
    "Sudanese",
    "Togo (2017 or later)",
    "Other Subsaharan African",
    "Ugandan",
    "Zimbabwean (2017 or later)",
    "Western African",
    "African",
    "Afghan",
    "Bangladeshi",
    "Bhutanese",
    "Nepali",
    "Asian Indian",
    "Bengali",
    "East Indian",
    "Punjabi",
    "Pakistani",
    "Sri Lankan",
    "Burmese",
    "Cambodian",
    "Chinese",
    "Cantonese",
    "Mongolian",
    "Tibetan",
    "Hong Kong (2017 or later)",
    "Filipino",
    "Indonesian",
    "Japanese",
    "Okinawan",
    "Korean",
    "Laotian",
    "Hmong",
    "Malaysian",
    "Thai",
    "Taiwanese",
    "Vietnamese",
    "Asian",
    "Other Asian",
    "Australian",
    "New Zealander",
    "Polynesian",
    "Hawaiian",
    "Samoan",
    "Tongan",
    "Micronesian",
    "Guamanian",
    "Chamorro",
    "Marshallese",
    "Fijian",
    "Pacific Islander",
    "Other Pacific",
    "Afro American",
    "Afro",
    "African American",
    "Black",
    "Negro",
    "Creole",
    "Central American Indian",
    "South American Indian",
    "Native American",
    "Indian",
    "Cherokee",
    "American Indian",
    "Eskimo",
    "White",
    "Anglo",
    "Appalachian",
    "Pennsylvania German",
    "Canadian",
    "French Canadian",
    "Acadian (2017 or later)",
    "Cajun",
    "American",
    "United States",
    "New Mexico (2017 or later)",
    "Texas",
    "North American",
    "Mixture",
    "Other groups",
    "Other responses",
    "Not reported",
  ],
  "Decade of entry": [
    "Before 1950",
    "1950 - 1959",
    "1960 - 1969",
    "1970 - 1979",
    "1980 - 1989",
    "1990 - 1999",
    "2000 - 2009",
    "2010 or later",
  ],
  "With a disability": ["yes", "no"],
  "Number of vehicles calculated from JWRI": [
    "1.000 vehicles (Drove alone)",
    "0.500 vehicles (In a 2-person carpool)",
    "0.333 vehicles (In a 3-person carpool)",
    "0.250 vehicles (In a 4-person carpool)",
    "0.200 vehicles (In a 5- or 6-person carpool)",
    "0.143 vehicles (In a 7-or-more person carpool)",
  ],
  "Employment status of parents": [
    "Both parents in LF",
    "Father only in LF",
    "Mother only in LF",
    "Neither parent in LF",
    "Living w/ father only: Father in LF",
    "Living w/ father only: Father not in LF",
    "Living w/ mother only: Mother in LF",
    "Living w/ mother only: Mother not in LF",
  ],
  "Raw labor-force status": [
    "Civilian employed, at work",
    "Civilian employed, with a job but not at work",
    "Unemployed",
    "Armed forces, at work",
    "Armed forces, with a job but not at work",
    "Not in the labor force",
  ],
  "Recoded field of degree - first entry": [
    "General Agriculture",
    "Agriculture Production And Management",
    "Agricultural Economics",
    "Animal Sciences",
    "Food Science",
    "Plant Science And Agronomy",
    "Soil Science",
    "Miscellaneous Agriculture",
    "Environmental Science",
    "Forestry",
    "Natural Resources Management",
    "Architecture",
    "Area Ethnic And Civilization Studies",
    "Communications",
    "Journalism",
    "Mass Media",
    "Advertising And Public Relations",
    "Communication Technologies",
    "Computer And Information Systems",
    "Computer Programming And Data Processing",
    "Computer Science",
    "Information Sciences",
    "Computer Administration Management And Security",
    "Computer Networking And Telecommunications",
    "Cosmetology Services And Culinary Arts",
    "General Education",
    "Educational Administration And Supervision",
    "School Student Counseling",
    "Elementary Education",
    "Mathematics Teacher Education",
    "Physical And Health Education Teaching",
    "Early Childhood Education",
    "Science And Computer Teacher Education",
    "Secondary Teacher Education",
    "Special Needs Education",
    "Social Science Or History Teacher Education",
    "Teacher Education: Multiple Levels",
    "Language And Drama Education",
    "Art And Music Education",
    "Miscellaneous Education",
    "General Engineering",
    "Aerospace Engineering",
    "Biological Engineering",
    "Architectural Engineering",
    "Biomedical Engineering",
    "Chemical Engineering",
    "Civil Engineering",
    "Computer Engineering",
    "Electrical Engineering",
    "Engineering Mechanics Physics And Science",
    "Environmental Engineering",
    "Geological And Geophysical Engineering",
    "Industrial And Manufacturing Engineering",
    "Materials Engineering And Materials Science",
    "Mechanical Engineering",
    "Metallurgical Engineering",
    "Mining And Mineral Engineering",
    "Naval Architecture And Marine Engineering",
    "Nuclear Engineering",
    "Petroleum Engineering",
    "Miscellaneous Engineering",
    "Engineering Technologies",
    "Engineering And Industrial Management",
    "Electrical Engineering Technology",
    "Industrial Production Technologies",
    "Mechanical Engineering Related Technologies",
    "Miscellaneous Engineering Technologies",
    "Linguistics And Comparative Language And Literature",
    "French German Latin And Other Common Foreign Language Studies",
    "Other Foreign Languages",
    "Family And Consumer Sciences",
    "Court Reporting",
    "Pre-Law And Legal Studies",
    "English Language And Literature",
    "Composition And Rhetoric",
    "Liberal Arts",
    "Humanities",
    "Library Science",
    "Biology",
    "Biochemical Sciences",
    "Botany",
    "Molecular Biology",
    "Ecology",
    "Genetics",
    "Microbiology",
    "Pharmacology",
    "Physiology",
    "Zoology",
    "Neuroscience",
    "Miscellaneous Biology",
    "Mathematics",
    "Applied Mathematics",
    "Statistics And Decision Science",
    "Military Technologies",
    "Multi/Interdisciplinary Studies",
    "Intercultural And International Studies",
    "Nutrition Sciences",
    "Mathematics And Computer Science",
    "Cognitive Science And Biopsychology",
    "Interdisciplinary Social Sciences",
    "Physical Fitness Parks Recreation And Leisure",
    "Philosophy And Religious Studies",
    "Theology And Religious Vocations",
    "Physical Sciences",
    "Astronomy And Astrophysics",
    "Atmospheric Sciences And Meteorology",
    "Chemistry",
    "Geology And Earth Science",
    "Geosciences",
    "Oceanography",
    "Physics",
    "Materials Science",
    "Multi-Disciplinary Or General Science",
    "Nuclear, Industrial Radiology, And Biological Technologies",
    "Psychology",
    "Educational Psychology",
    "Clinical Psychology",
    "Counseling Psychology",
    "Industrial And Organizational Psychology",
    "Social Psychology",
    "Miscellaneous Psychology",
    "Criminal Justice And Fire Protection",
    "Public Administration",
    "Public Policy",
    "Human Services And Community Organization",
    "Social Work",
    "General Social Sciences",
    "Economics",
    "Anthropology And Archeology",
    "Criminology",
    "Geography",
    "International Relations",
    "Political Science And Government",
    "Sociology",
    "Miscellaneous Social Sciences",
    "Construction Services",
    "Electrical, Mechanical, And Precision Technologies And Production",
    "Transportation Sciences And Technologies",
    "Fine Arts",
    "Drama And Theater Arts",
    "Music",
    "Visual And Performing Arts",
    "Commercial Art And Graphic Design",
    "Film Video And Photographic Arts",
    "Art History And Criticism",
    "Studio Arts",
    "Miscellaneous Fine Arts",
    "General Medical And Health Services",
    "Communication Disorders Sciences And Services",
    "Health And Medical Administrative Services",
    "Medical Assisting Services",
    "Medical Technologies Technicians",
    "Health And Medical Preparatory Programs",
    "Nursing",
    "Pharmacy Pharmaceutical Sciences And Administration",
    "Treatment Therapy Professions",
    "Community And Public Health",
    "Miscellaneous Health Medical Professions",
    "General Business",
    "Accounting",
    "Actuarial Science",
    "Business Management And Administration",
    "Operations Logistics And E-Commerce",
    "Business Economics",
    "Marketing And Marketing Research",
    "Finance",
    "Human Resources And Personnel Management",
    "International Business",
    "Hospitality Management",
    "Management Information Systems And Statistics",
    "Miscellaneous Business and Medical Administration",
    "History",
    "United States History",
  ],
  "Recoded field of degree - second entry": [
    "General Agriculture",
    "Agriculture Production And Management",
    "Agricultural Economics",
    "Animal Sciences",
    "Food Science",
    "Plant Science And Agronomy",
    "Soil Science",
    "Miscellaneous Agriculture",
    "Environmental Science",
    "Forestry",
    "Natural Resources Management",
    "Architecture",
    "Area Ethnic And Civilization Studies",
    "Communications",
    "Journalism",
    "Mass Media",
    "Advertising And Public Relations",
    "Communication Technologies",
    "Computer And Information Systems",
    "Computer Programming And Data Processing",
    "Computer Science",
    "Information Sciences",
    "Computer Administration Management And Security",
    "Computer Networking And Telecommunications",
    "Cosmetology Services And Culinary Arts",
    "General Education",
    "Educational Administration And Supervision",
    "School Student Counseling",
    "Elementary Education",
    "Mathematics Teacher Education",
    "Physical And Health Education Teaching",
    "Early Childhood Education",
    "Science And Computer Teacher Education",
    "Secondary Teacher Education",
    "Special Needs Education",
    "Social Science Or History Teacher Education",
    "Teacher Education: Multiple Levels",
    "Language And Drama Education",
    "Art And Music Education",
    "Miscellaneous Education",
    "General Engineering",
    "Aerospace Engineering",
    "Biological Engineering",
    "Architectural Engineering",
    "Biomedical Engineering",
    "Chemical Engineering",
    "Civil Engineering",
    "Computer Engineering",
    "Electrical Engineering",
    "Engineering Mechanics Physics And Science",
    "Environmental Engineering",
    "Geological And Geophysical Engineering",
    "Industrial And Manufacturing Engineering",
    "Materials Engineering And Materials Science",
    "Mechanical Engineering",
    "Metallurgical Engineering",
    "Mining And Mineral Engineering",
    "Naval Architecture And Marine Engineering",
    "Nuclear Engineering",
    "Petroleum Engineering",
    "Miscellaneous Engineering",
    "Engineering Technologies",
    "Engineering And Industrial Management",
    "Electrical Engineering Technology",
    "Industrial Production Technologies",
    "Mechanical Engineering Related Technologies",
    "Miscellaneous Engineering Technologies",
    "Linguistics And Comparative Language And Literature",
    "French German Latin And Other Common Foreign Language Studies",
    "Other Foreign Languages",
    "Family And Consumer Sciences",
    "Pre-Law And Legal Studies",
    "English Language And Literature",
    "Composition And Rhetoric",
    "Liberal Arts",
    "Humanities",
    "Library Science",
    "Biology",
    "Biochemical Sciences",
    "Botany",
    "Molecular Biology",
    "Ecology",
    "Genetics",
    "Microbiology",
    "Pharmacology",
    "Physiology",
    "Zoology",
    "Neuroscience",
    "Miscellaneous Biology",
    "Mathematics",
    "Applied Mathematics",
    "Statistics And Decision Science",
    "Military Technologies",
    "Multi/Interdisciplinary Studies",
    "Intercultural And International Studies",
    "Nutrition Sciences",
    "Mathematics And Computer Science",
    "Cognitive Science And Biopsychology",
    "Interdisciplinary Social Sciences",
    "Physical Fitness Parks Recreation And Leisure",
    "Philosophy And Religious Studies",
    "Theology And Religious Vocations",
    "Physical Sciences",
    "Astronomy And Astrophysics",
    "Atmospheric Sciences And Meteorology",
    "Chemistry",
    "Geology And Earth Science",
    "Geosciences",
    "Oceanography",
    "Physics",
    "Materials Science",
    "Multi-Disciplinary Or General Science",
    "Nuclear, Industrial Radiology, And Biological Technologies",
    "Psychology",
    "Educational Psychology",
    "Clinical Psychology",
    "Counseling Psychology",
    "Industrial And Organizational Psychology",
    "Social Psychology",
    "Miscellaneous Psychology",
    "Criminal Justice And Fire Protection",
    "Public Administration",
    "Public Policy",
    "Human Services And Community Organization",
    "Social Work",
    "General Social Sciences",
    "Economics",
    "Anthropology And Archeology",
    "Criminology",
    "Geography",
    "International Relations",
    "Political Science And Government",
    "Sociology",
    "Miscellaneous Social Sciences",
    "Construction Services",
    "Electrical, Mechanical, And Precision Technologies And Production",
    "Transportation Sciences And Technologies",
    "Fine Arts",
    "Drama And Theater Arts",
    "Music",
    "Visual And Performing Arts",
    "Commercial Art And Graphic Design",
    "Film Video And Photographic Arts",
    "Art History And Criticism",
    "Studio Arts",
    "Miscellaneous Fine Arts",
    "General Medical And Health Services",
    "Communication Disorders Sciences And Services",
    "Health And Medical Administrative Services",
    "Medical Assisting Services",
    "Medical Technologies Technicians",
    "Health And Medical Preparatory Programs",
    "Nursing",
    "Pharmacy Pharmaceutical Sciences And Administration",
    "Treatment Therapy Professions",
    "Community And Public Health",
    "Miscellaneous Health Medical Professions",
    "General Business",
    "Accounting",
    "Actuarial Science",
    "Business Management And Administration",
    "Operations Logistics And E-Commerce",
    "Business Economics",
    "Marketing And Marketing Research",
    "Finance",
    "Human Resources And Personnel Management",
    "International Business",
    "Hospitality Management",
    "Management Information Systems And Statistics",
    "Miscellaneous Business and Medical Administration",
    "History",
    "United States History",
  ],
  "Health insurance coverage recode": ["yes", "no"],
  "Hispanic, Detailed": [
    "Not Spanish/Hispanic/Latino",
    "Mexican",
    "Puerto Rican",
    "Cuban",
    "Dominican",
    "Costa Rican",
    "Guatemalan",
    "Honduran",
    "Nicaraguan",
    "Panamanian",
    "Salvadoran",
    "Other Central American",
    "Argentinean",
    "Bolivian",
    "Chilean",
    "Colombian",
    "Ecuadorian",
    "Paraguayan",
    "Peruvian",
    "Uruguayan",
    "Venezuelan",
    "Other South American",
    "Spaniard",
    "All Other Spanish/Hispanic/Latino",
  ],
  "Industry group": [
    "Administration",
    "Agriculture And Forestry",
    "Construction",
    "Education",
    "Entertainment",
    "Mining",
    "Finance",
    "Information Services",
    "Healtchare",
    "Manufacturing Industries",
    "Military",
    "Professional, Scientific, And Technical Services",
    "Retail trade",
    "Social Services",
    "Personal Care and Services",
    "Transportation",
    "Utilities",
    "Wholesalers",
  ],
  "Industry recode": [
    "AGR-Crop Production",
    "AGR-Animal Production And Aquaculture",
    "AGR-Forestry Except Logging",
    "AGR-Logging",
    "AGR-Fishing, Hunting And Trapping",
    "AGR-Support Activities For Agriculture And Forestry",
    "EXT-Oil And Gas Extraction",
    "EXT-Coal Mining",
    "EXT-Metal Ore Mining",
    "EXT-Nonmetallic Mineral Mining And Quarrying",
    "EXT-Support Activities For Mining",
    "UTL-Electric Power Generation, Transmission And Distribution",
    "UTL-Natural Gas Distribution",
    "UTL-Electric And Gas, And Other Combinations",
    "UTL-Water, Steam, Air-Conditioning, And Irrigation Systems",
    "UTL-Sewage Treatment Facilities",
    "UTL-Not Specified Utilities",
    "CON-Construction (The Cleaning Of Buildings And Dwellings Is Incidental During Construction And Immediately After Construction)",
    "MFG-Animal Food, Grain And Oilseed Milling",
    "MFG-Sugar And Confectionery Products",
    "MFG-Fruit And Vegetable Preserving And Specialty Food",
    "MFG-Dairy Product",
    "MFG-Animal Slaughtering And Processing",
    "MFG-Retail Bakeries",
    "MFG-Bakeries And Tortilla, Except Retail Bakeries",
    "MFG-Seafood And Other Miscellaneous Foods, N.E.C.",
    "MFG-Not Specified Food Industries",
    "MFG-Beverage",
    "MFG-Tobacco",
    "MFG-Fiber, Yarn, And Thread Mills",
    "MFG-Fabric Mills, Except Knitting Mills",
    "MFG-Textile And Fabric Finishing And Fabric Coating Mills",
    "MFG-Carpet And Rug Mills",
    "MFG-Textile Product Mills, Except Carpet And Rug",
    "MFG-Knitting Fabric Mills, And Apparel Knitting Mills",
    "MFG-Cut And Sew, And Apparel Accessories And Other Apparel",
    "MFG-Footwear",
    "MFG-Leather And Hide Tanning And Finishing, And Other Leather And Allied Product",
    "MFG-Pulp, Paper, And Paperboard Mills",
    "MFG-Paperboard Container",
    "MFG-Miscellaneous Paper And Pulp Products",
    "MFG-Printing And Related Support Activities",
    "MFG-Petroleum Refining",
    "MFG-Miscellaneous Petroleum And Coal Products",
    "MFG-Resin, Synthetic Rubber, And Fibers And Filaments",
    "MFG-Agricultural Chemical",
    "MFG-Pharmaceutical And Medicine",
    "MFG-Paint, Coating, And Adhesive",
    "MFG-Soap, Cleaning Compound, And Cosmetics",
    "MFG-Industrial And Miscellaneous Chemicals",
    "MFG-Plastics Product",
    "MFG-Tire",
    "MFG-Rubber Products, Except Tires",
    "MFG-Pottery, Ceramics, And Plumbing Fixture",
    "MFG-Clay Building Material And Refractories",
    "MFG-Glass And Glass Product",
    "MFG-Cement, Concrete, Lime, And Gypsum Product",
    "MFG-Miscellaneous Nonmetallic Mineral Product",
    "MFG-Iron And Steel Mills And Steel Product",
    "MFG-Aluminum Production And Processing",
    "MFG-Nonferrous Metal (Except Aluminum) Production And Processing",
    "MFG-Foundries",
    "MFG-Metal Forgings And Stampings",
    "MFG-Cutlery And Hand Tool",
    "MFG-Structural Metals, And Boiler, Tank, And Shipping Container",
    "MFG-Machine Shops; Turned Product; Screw, Nut, And Bolt",
    "MFG-Coating, Engraving, Heat Treating, And Allied Activities",
    "MFG-Ordnance",
    "MFG-Miscellaneous Fabricated Metal Products",
    "MFG-Not Specified Metal Industries",
    "MFG-Agricultural Implement",
    "MFG-Construction, And Mining And Oil And Gas Field Machinery",
    "MFG-Commercial And Service Industry Machinery",
    "MFG-Metalworking Machinery",
    "MFG-Engine, Turbine, And Power Transmission Equipment",
    "MFG-Machinery, N.E.C. Or Not Specified",
    "MFG-Computer And Peripheral Equipment",
    "MFG-Communications, Audio, And Video Equipment",
    "MFG-Navigational, Measuring, Electromedical, And Control Instruments",
    "MFG-Electronic Component And Product, N.E.C.",
    "MFG-Household Appliance",
    "MFG-Electric Lighting And Electrical Equipment, And Other Electrical Component, N.E.C.",
    "MFG-Motor Vehicles And Motor Vehicle Equipment",
    "MFG-Aircraft And Parts",
    "MFG-Aerospace Products And Parts",
    "MFG-Railroad Rolling Stock",
    "MFG-Ship And Boat Building",
    "MFG-Other Transportation Equipment",
    "MFG-Sawmills And Wood Preservation",
    "MFG-Veneer, Plywood, And Engineered Wood Products",
    "MFG-Prefabricated Wood Buildings And Mobile Homes",
    "MFG-Miscellaneous Wood Products",
    "MFG-Furniture And Related Product",
    "MFG-Medical Equipment And Supplies",
    "MFG-Sporting And Athletic Goods, And Doll, Toy And Game",
    "MFG-Miscellaneous Manufacturing, N.E.C.",
    "MFG-Not Specified Manufacturing Industries",
    "WHL-Motor Vehicle And Motor Vehicle Parts And Supplies Merchant Wholesalers",
    "WHL-Furniture And Home Furnishing Merchant Wholesalers",
    "WHL-Lumber And Other Construction Materials Merchant Wholesalers",
    "WHL-Professional And Commercial Equipment And Supplies Merchant Wholesalers",
    "WHL-Metals And Minerals, Except Petroleum, Merchant Wholesalers",
    "WHL-Household Appliances And Electrical And Electronic Goods Merchant Wholesalers",
    "WHL-Hardware, And Plumbing And Heating Equipment, And Supplies Merchant Wholesalers",
    "WHL-Machinery, Equipment, And Supplies Merchant Wholesalers",
    "WHL-Recyclable Material Merchant Wholesalers",
    "WHL-Miscellaneous Durable Goods Merchant Wholesalers",
    "WHL-Paper And Paper Products Merchant Wholesalers",
    "WHL-Drugs, Sundries, And Chemical And Allied Products Merchant Wholesalers",
    "WHL-Apparel, Piece Goods, And Notions Merchant Wholesalers",
    "WHL-Grocery And Related Product Merchant Wholesalers",
    "WHL-Farm Product Raw Material Merchant Wholesalers",
    "WHL-Petroleum And Petroleum Products Merchant Wholesalers",
    "WHL-Alcoholic Beverages Merchant Wholesalers",
    "WHL-Farm Supplies Merchant Wholesalers",
    "WHL-Miscellaneous Nondurable Goods Merchant Wholesalers",
    "WHL-Wholesale Electronic Markets And Agents And Brokers",
    "WHL-Not Specified Wholesale Trade",
    "RET-Automobile Dealers",
    "RET-Other Motor Vehicle Dealers",
    "RET-Automotive Parts, Accessories, And Tire Stores",
    "RET-Furniture And Home Furnishings Stores",
    "RET-Household Appliance Stores",
    "RET-Electronics Stores",
    "RET-Building Material And Supplies Dealers",
    "RET-Hardware Stores",
    "RET-Lawn And Garden Equipment And Supplies Stores",
    "RET-Supermarkets and Other Grocery (Except Convenience) Stores",
    "RET-Convenience Stores",
    "RET-Specialty Food Stores",
    "RET-Beer, Wine, And Liquor Stores",
    "RET-Pharmacies And Drug Stores",
    "RET-Health And Personal Care, Except Drug, Stores",
    "RET-Gasoline Stations",
    "RET-Clothing Stores",
    "RET-Shoe Stores",
    "RET-Jewelry, Luggage, And Leather Goods Stores",
    "RET-Sporting Goods, And Hobby And Toy Stores",
    "RET-Sewing, Needlework, And Piece Goods Stores",
    "RET-Musical Instrument And Supplies Stores",
    "RET-Book Stores And News Dealers",
    "RET-Department Stores",
    "RET-General Merchandise Stores, Including Warehouse Clubs and Supercenters",
    "RET-Florists",
    "RET-Office Supplies And Stationery Stores",
    "RET-Used Merchandise Stores",
    "RET-Gift, Novelty, And Souvenir Shops",
    "RET-Miscellaneous Retail Stores",
    "RET-Electronic Shopping And Mail-Order Houses",
    "RET-Vending Machine Operators",
    "RET-Fuel Dealers",
    "RET-Other Direct Selling Establishments",
    "RET-Not Specified Retail Trade",
    "TRN-Air Transportation",
    "TRN-Rail Transportation",
    "TRN-Water Transportation",
    "TRN-Truck Transportation",
    "TRN-Bus Service And Urban Transit",
    "TRN-Taxi And Limousine Service",
    "TRN-Pipeline Transportation",
    "TRN-Scenic And Sightseeing Transportation",
    "TRN-Services Incidental To Transportation",
    "TRN-Postal Service",
    "TRN-Couriers And Messengers",
    "TRN-Warehousing And Storage",
    "INF-Newspaper Publishers",
    "INF-Periodical, Book, And Directory Publishers",
    "INF-Software Publishers",
    "INF-Motion Pictures And Video Industries",
    "INF-Sound Recording Industries",
    "INF-Broadcasting (Except Internet)",
    "INF-Internet Publishing And Broadcasting And Web Search Portals",
    "INF-Wired Telecommunications Carriers",
    "INF-Telecommunications, Except Wired Telecommunications Carriers",
    "INF-Data Processing, Hosting, And Related Services",
    "INF-Libraries And Archives",
    "INF-Other Information Services, Except Libraries And Archives, And Internet Publishing And Broadcasting And Web Search Portals",
    "FIN-Banking And Related Activities",
    "FIN-Savings Institutions, Including Credit Unions",
    "FIN-Nondepository Credit And Related Activities",
    "FIN-Securities, Commodities, Funds, Trusts, And Other Financial Investments",
    "FIN-Insurance Carriers",
    "FIN-Agencies, Brokerages, And Other Insurance Related Activities",
    "FIN-Lessors Of Real Estate, And Offices Of Real Estate Agents And Brokers",
    "FIN-Real Estate Property Managers, Offices Of Real Estate Appraisers, And Other Activities Related To Real Estate",
    "FIN-Automotive Equipment Rental And Leasing",
    "FIN-Other Consumer Goods Rental",
    "FIN-Commercial, Industrial, And Other Intangible Assets Rental And Leasing",
    "PRF-Legal Services",
    "PRF-Accounting, Tax Preparation, Bookkeeping, And Payroll Services",
    "PRF-Architectural, Engineering, And Related Services",
    "PRF-Specialized Design Services",
    "PRF-Computer Systems Design And Related Services",
    "PRF-Management, Scientific, And Technical Consulting Services",
    "PRF-Scientific Research And Development Services",
    "PRF-Advertising, Public Relations, And Related Services",
    "PRF-Veterinary Services",
    "PRF-Other Professional, Scientific, And Technical Services",
    "PRF-Management Of Companies And Enterprises",
    "PRF-Employment Services",
    "PRF-Business Support Services",
    "PRF-Travel Arrangements And Reservation Services",
    "PRF-Investigation And Security Services",
    "PRF-Services To Buildings And Dwellings (Except Cleaning During Construction And Immediately After Construction)",
    "PRF-Landscaping Services",
    "PRF-Other Administrative And Other Support Services",
    "PRF-Waste Management And Remediation Services",
    "EDU-Elementary And Secondary Schools",
    "EDU-Colleges, Universities, And Professional Schools, Including Junior Colleges",
    "EDU-Business, Technical, And Trade Schools And Training",
    "EDU-Other Schools And Instruction, And Educational Support Services",
    "MED-Offices Of Physicians",
    "MED-Offices Of Dentists",
    "MED-Offices Of Chiropractors",
    "MED-Offices Of Optometrists",
    "MED-Offices Of Other Health Practitioners",
    "MED-Outpatient Care Centers",
    "MED-Home Health Care Services",
    "MED-Other Health Care Services",
    "MED-General Medical And Surgical Hospitals, And Specialty (Except Psychiatric And Substance Abuse) Hospitals",
    "MED-Psychiatric And Substance Abuse Hospitals",
    "MED-Nursing Care Facilities (Skilled Nursing Facilities)",
    "MED-Residential Care Facilities, Except Skilled Nursing Facilities",
    "SCA-Individual And Family Services",
    "SCA-Community Food And Housing, And Emergency Services",
    "SCA-Vocational Rehabilitation Services",
    "SCA-Child Day Care Services",
    "ENT-Performing Arts Companies",
    "ENT-Spectator Sports",
    "ENT-Promoters Of Performing Arts, Sports, And Similar Events, Agents And Managers For Artists, Athletes, Entertainers, And Other Public Figures",
    "ENT-Independent Artists, Writers, And Performers",
    "ENT-Museums, Art Galleries, Historical Sites, And Similar Institutions",
    "ENT-Bowling Centers",
    "ENT-Other Amusement, Gambling, And Recreation Industries",
    "ENT-Traveler Accommodation",
    "ENT-Recreational Vehicle Parks And Camps, And Rooming And Boarding Houses, Dormitories, And Workers' Camps",
    "ENT-Restaurants And Other Food Services",
    "ENT-Drinking Places, Alcoholic Beverages",
    "SRV-Automotive Repair And Maintenance",
    "SRV-Car Washes",
    "SRV-Electronic And Precision Equipment Repair And Maintenance",
    "SRV-Commercial And Industrial Machinery And Equipment Repair And Maintenance",
    "SRV-Personal And Household Goods Repair And Maintenance",
    "SRV-Barber Shops",
    "SRV-Beauty Salons",
    "SRV-Nail Salons And Other Personal Care Services",
    "SRV-Drycleaning And Laundry Services",
    "SRV-Funeral Homes, And Cemeteries And Crematories",
    "SRV-Other Personal Services",
    "SRV-Religious Organizations",
    "SRV-Civic, Social, Advocacy Organizations, And Grantmaking And Giving Services",
    "SRV-Labor Unions",
    "SRV-Business, Professional, Political, And Similar Organizations",
    "SRV-Private Households",
    "ADM-Executive Offices And Legislative Bodies",
    "ADM-Public Finance Activities",
    "ADM-Other General Government And Support",
    "ADM-Justice, Public Order, And Safety Activities",
    "ADM-Administration Of Human Resource Programs",
    "ADM-Administration Of Environmental Quality And Housing Programs",
    "ADM-Administration Of Economic Programs And Space Research",
    "ADM-National Security And International Affairs",
    "MIL-U.S. Army",
    "MIL-U.S. Air Force",
    "MIL-U.S. Navy",
    "MIL-U.S. Marines",
    "MIL-U.S. Coast Guard",
    "MIL-Armed Forces, Branch Not Specified",
    "MIL-Military Reserves Or National Guard",
    "Unemployed, With No Work Experience In The Last 5 Years Or Earlier Or Never Worked",
  ],
  "Occupation group": [
    "Business",
    "Cleaning",
    "Computers and Mathematics",
    "Community services",
    "Construction",
    "Food",
    "Education",
    "Engineering",
    "Entertainment",
    "Mining",
    "Farming, Fishing and Forestry",
    "Finance",
    "Healthcare Support",
    "Legal",
    "Healthcare Practitioners and Technical Occupations",
    "Managers",
    "Military",
    "Office And Administrative Support",
    "Production",
    "Personal Care and Services",
    "Protective Service",
    "Repair Services",
    "Sales",
    "Science",
    "Transportation",
    "Unemployed",
  ],
  "Standard Occupational Classification": [
    "MGR-General And Operations Managers",
    "MGR-Chief Executives And Legislators",
    "MGR-Advertising And Promotions Managers",
    "MGR-Marketing Managers",
    "MGR-Sales Managers",
    "MGR-Public Relations And Fundraising Managers",
    "MGR-Administrative Services Managers",
    "MGR-Facilities Managers",
    "MGR-Computer And Information Systems Managers",
    "MGR-Financial Managers",
    "MGR-Industrial Production Managers",
    "MGR-Purchasing Managers",
    "MGR-Transportation, Storage, And Distribution Managers",
    "MGR-Compensation And Benefits Managers",
    "MGR-Human Resources Managers",
    "MGR-Training And Development Managers",
    "MGR-Farmers, Ranchers, And Other Agricultural Managers",
    "MGR-Construction Managers",
    "MGR-Education And Childcare Administrators",
    "MGR-Architectural And Engineering Managers",
    "MGR-Food Service Managers",
    "MGR-Entertainment And Recreation Managers",
    "MGR-Lodging Managers",
    "MGR-Medical And Health Services Managers",
    "MGR-Natural Sciences Managers",
    "MGR-Property, Real Estate, And Community Association Managers",
    "MGR-Social And Community Service Managers",
    "MGR-Emergency Management Directors",
    "MGR-Other Managers",
    "BUS-Agents And Business Managers Of Artists, Performers, And Athletes",
    "BUS-Buyers And Purchasing Agents, Farm Products",
    "BUS-Wholesale And Retail Buyers, Except Farm Products",
    "BUS-Purchasing Agents, Except Wholesale, Retail, And Farm Products",
    "BUS-Claims Adjusters, Appraisers, Examiners, And Investigators",
    "BUS-Compliance Officers",
    "BUS-Cost Estimators",
    "BUS-Human Resources Workers",
    "BUS-Logisticians",
    "BUS-Project Management Specialists",
    "BUS-Management Analysts",
    "BUS-Meeting Convention, And Event Planners",
    "BUS-Fundraisers",
    "BUS-Compensation, Benefits, And Job Analysis Specialists",
    "BUS-Training And Development Specialists",
    "BUS-Market Research Analysts And Marketing Specialists",
    "BUS-Business Operations Specialists, All Other",
    "FIN-Accountants And Auditors",
    "FIN-Property Appraisers And Assessors",
    "FIN-Budget Analysts",
    "FIN-Credit Analysts",
    "FIN-Financial Analysts",
    "FIN-Personal Financial Advisors",
    "FIN-Insurance Underwriters",
    "FIN-Financial Examiners",
    "FIN-Credit Counselors And Loan Officers",
    "FIN-Tax Examiners And Collectors, And Revenue Agents",
    "FIN-Tax Preparers",
    "FIN-Other Financial Specialists",
    "CMM-Computer Systems Analysts",
    "CMM-Information Security Analysts",
    "CMM-Computer And Information Research Scientists",
    "CMM-Computer Support Specialists",
    "CMM-Computer Network Architects",
    "CMM-Network And Computer Systems Administrators",
    "CMM-Database Administrators And Architects",
    "CMM-Computer Programmers",
    "CMM-Software Developers",
    "CMM-Software Quality Assurance Analysts And Testers",
    "CMM_Web Developers",
    "CMM Web And Digital Interface Designers",
    "CMM Computer Occupations, All Other",
    "CMM-Actuaries",
    "CMM-Operations Research Analysts",
    "CMM-Other Mathematical Science Occupations",
    "ENG-Architects, Except Landscape And Naval",
    "ENG-Landscape Architects",
    "ENG-Surveyors, Cartographers, And Photogrammetrists",
    "ENG-Aerospace Engineers",
    "ENG-Chemical Engineers",
    "ENG-Civil Engineers",
    "ENG-Computer Hardware Engineers",
    "ENG-Electrical And Electronics Engineers",
    "ENG-Environmental Engineers",
    "ENG-Biomedical And Agricultural Engineers",
    "ENG-Industrial Engineers, Including Health And Safety",
    "ENG-Marine Engineers And Naval Architects",
    "ENG-Materials Engineers",
    "ENG-Mechanical Engineers",
    "ENG-Petroleum, Mining And Geological Engineers, Including Mining Safety Engineers",
    "ENG-Other Engineers",
    "ENG-Architectural And Civil Drafters",
    "ENG-Other Drafters",
    "ENG-Electrical and Electronic Engineering Technologists AndTechnicians",
    "ENG-Other Engineering Technologists And Technicians, Except Drafters",
    "ENG-Surveying And Mapping Technicians",
    "SCI-Agricultural And Food Scientists",
    "SCI-Biological Scientists",
    "SCI-Conservation Scientists And Foresters",
    "SCI-Medical Scientists, And Life Scientists, All Other",
    "SCI-Astronomers And Physicists",
    "SCI-Atmospheric And Space Scientists",
    "SCI-Chemists And Materials Scientists",
    "SCI-Environmental Scientists And Specialists, Including Health",
    "Geoscientists And Hydrologists, Except Geographers",
    "SCI-Physical Scientists, All Other",
    "SCI-Economists",
    "SCI-Clinical And Counseling Psychologists",
    "SCI-School Psychologists",
    "SCI-Other Psychologists",
    "SCI-Urban And Regional Planners",
    "Other Social Scientists",
    "SCI Agricultural And Food Science Technicians",
    "SCI-Biological Technicians",
    "SCI-Chemical Technicians",
    "SCI-Environmental Science And Geoscience Technicians, And Nuclear Technicians",
    "SCI-Other Life, Physical, And Social Science Technicians",
    "SCI-Occupational Health And Safety Specialists And Technicians",
    "CMS-Substance Abuse And Behavioral Disorder Counselors",
    "CMS-Educational, Guidance, And Career Counselors And Advisors",
    "CMS-Marriage And Family Therapists",
    "CMS-Mental Health Counselors",
    "CMS-Rehabilitation Counselors",
    "CMS-Counselors, All Other",
    "CMS-Child, Family, And School Social Workers",
    "CMS-Healthcare Social Workers",
    "CMS-Mental Health And Substance Abuse Social Workers",
    "CMS-Social Workers All Other",
    "CMS-Probation Officers And Correctional Treatment Specialists",
    "CMS-Social And Human Service Assistants",
    "CMS-Other Community And Social Service Specialists",
    "CMS-Clergy",
    "CMS-Directors, Religious Activities And Education",
    "CMS-Religious Workers, All Other",
    "LGL-Judicial Law Clerks",
    "LGL-Lawyers, And Judges, Magistrates, And Other Judicial Workers",
    "LGL-Paralegals And Legal Assistants",
    "LGL-Title Examiners, Abstractors, And Searchers",
    "LGL-Legal Support Workers, All Other",
    "EDU-Postsecondary Teachers",
    "EDU-Preschool And Kindergarten Teachers",
    "EDU-Elementary And Middle School Teachers",
    "EDU-Secondary School Teachers",
    "EDU-Special Education Teachers",
    "EDU-Tutors",
    "EDU-Other Teachers And Instructors",
    "EDU-Archivists, Curators, And Museum Technicians",
    "EDU-Librarians And Media Collections Specialists",
    "EDU-Library Technicians",
    "EDU-Teaching Assistants",
    "EDU-Other Educational Instruction and Library Workers",
    "ENT-Artists And Related Workers",
    "ENT-Commercial And Industrial Designers",
    "ENT-Fashion Designers",
    "ENT-Floral Designers",
    "ENT-Graphic Designers",
    "ENT-Interior Designers",
    "ENT-Merchandise Displayers And Windows Trimmers",
    "ENT-Other Designers",
    "ENT-Actors",
    "ENT-Producers And Directors",
    "ENT-Athletes And Sports Competitors",
    "ENT-Coaches And Scouts",
    "ENT-Umpires, Referees, And Other Sports Officials",
    "ENT-Dancers And Choreographers",
    "ENT-Music Directors And Composers",
    "ENT-Musicians And Singers",
    "ENT-Disc Jockeys, Except Radio",
    "ENT-Entertainers And Performers, Sports And Related Workers, All Other",
    "ENT-Broadcast Announcers And Radio Disc Jockeys",
    "ENT-News Analysts, Reporters, And Journalists",
    "ENT-Public Relations Specialists",
    "ENT-Editors",
    "ENT-Technical Writers",
    "ENT-Writers And Authors",
    "ENT-Interpreters And Translators",
    "ENT-Court Reporters And Simultaneous Captioners",
    "ENT-Media And Communications Workers, All Other",
    "ENT-Photographers",
    "ENT-Television, Video, And Motion Picture Camera Operators And Editors",
    "ENT-Other Media And Communication Equipment Workers",
    "MED-Chiropractors",
    "MED-Dentists",
    "MED-Dietitians And Nutritionists",
    "MED-Optometrists",
    "MED-Pharmacists",
    "MED-Physician Assistants",
    "MED-Podiatrists",
    "MED-Occupational Therapists",
    "MED-Physical Therapists",
    "MED-Radiation Therapists",
    "MED-Recreational Therapists",
    "MED-Respiratory Therapists",
    "MED-Speech-Language Pathologists",
    "MED-Other Therapists",
    "MED-Veterinarians",
    "MED-Registered Nurses",
    "MED-Nurse Anesthetists",
    "MED-Audiologists",
    "MED-Nurse Practitioners And Nurse Midwives",
    "MED-Physicians",
    "MED-Surgeons",
    "MED-Acupuncturists",
    "MED-Dental Hygienists",
    "MED-Healthcare Diagnosing Or Treating Practitioners, All Other",
    "MED-Clinical Laboratory Technologists And Technicians",
    "MED-Cardiovascular Technologists And Technicians",
    "MED-Diagnostic Medical Sonographers",
    "MED-Radiologic Technologists And Technicians",
    "MED-Magnetic Resonance Imaging Technologists",
    "MED-Nuclear Medicine Technologists And Medical Dosimetrists",
    "MED-Emergency Medical Technicians",
    "MED-Paramedics",
    "MED-Pharmacy Technicians",
    "MED-Psychiatric Technicians",
    "MED-Surgical Technologists",
    "MED-Veterinary Technologists And Technicians",
    "MED-Dietetic Technicians And Ophthalmic Medical Technicians",
    "MED-Licensed Practical And Licensed Vocational Nurses",
    "MED-Medical Records Specialists",
    "MED-Opticians, Dispensing",
    "MED-Miscellaneous Health Technologists And Technicians",
    "MED-Other Healthcare Practitioners And Technical Occupations",
    "HLS-Home Health Aides",
    "HLS-Personal Care Aides",
    "HLS-Nursing Assistants",
    "HLS-Orderlies And Psychiatric Aides",
    "HLS-Occupational Therapy Assistants And Aides",
    "HLS-Physical Therapist Assistants And Aides",
    "HLS-Massage Therapists",
    "HLS-Dental Assistants",
    "HLS-Medical Assistants",
    "HLS-Medical Transcriptionists",
    "HLS-Pharmacy Aides",
    "HLS-Veterinary Assistants And Laboratory Animal Caretakers",
    "HLS-Phlebotomists",
    "HLS-Other Healthcare Support Workers",
    "PRT-First-Line Supervisors Of Correctional Officers",
    "PRT-First-Line Supervisors Of Police And Detectives",
    "PRT-First-Line Supervisors Of Fire Fighting And Prevention Workers",
    "PRT-Miscellaneous First-Line Supervisors, Protective Service Workers",
    "PRT-Firefighters",
    "PRT-Fire Inspectors",
    "PRT-Bailiffs",
    "PRT-Correctional Officers And Jailers",
    "PRT-Detectives And Criminal Investigators",
    "PRT-Police Officers",
    "PRT-Fish And Game Wardens And Parking Enforcement Officers",
    "PRT-Animal Control Workers",
    "PRT-Private Detectives And Investigators",
    "PRT-Security Guards And Gaming Surveillance Officers",
    "PRT-Crossing Guards And Flaggers",
    "PRT-Transportation Security Screeners",
    "PRT-School Bus Monitors",
    "PRT-Other Protective Service Workers",
    "EAT-Chefs And Head Cooks",
    "EAT-First-Line Supervisors Of Food Preparation And Serving Workers",
    "EAT-Cooks",
    "EAT-Food Preparation Workers",
    "EAT-Bartenders",
    "EAT-Fast Food And Counter Workers",
    "EAT-Waiters And Waitresses",
    "EAT-Food Servers, Nonrestaurant",
    "EAT-Dining Room And Cafeteria Attendants And Bartender Helpers",
    "EAT-Dishwashers",
    "EAT-Hosts And Hostesses, Restaurant, Lounge, And Coffee Shop",
    "EAT-Food Preparation And Serving Related Workers, All Other",
    "CLN-First-Line Supervisors Of Housekeeping And Janitorial Workers",
    "CLN-First-Line Supervisors Of Landscaping, Lawn Service, And Groundskeeping Workers",
    "CLN-Maids And Housekeeping Cleaners",
    "CLN-Janitors And Building Cleaners",
    "CLN-Pest Control Workers",
    "CLN-Landscaping And Groundskeeping Workers",
    "CLN-Tree Trimmers And Pruners",
    "CLN-Other Grounds Maintenance Workers",
    "PRS-Supervisors of Personal Care And Service Workers",
    "PRS-Animal Trainers",
    "PRS-Animal Caretakers",
    "PRS-Gambling Services Workers",
    "PRS-Ushers, Lobby Attendants, And Ticket Takers",
    "PRS-Other Entertainment Attendants And Related Workers",
    "PRS-Morticians, Undertakers, And Funeral Arrangers",
    "PRS-Embalmers, Crematory Operators, And Funeral Attendants",
    "PRS-Barbers",
    "PRS-Hairdressers, Hairstylists, And Cosmetologists",
    "PRS-Manicurists and Pedicurists",
    "PRS-Skincare Specialists",
    "PRS-Other Personal Appearance Workers",
    "PRS-Baggage Porters, Bellhops, And Concierges",
    "PRS-Tour And Travel Guides",
    "PRS-Childcare Workers",
    "PRS-Exercise Trainers And Group Fitness Instructors",
    "PRS-Recreation Workers",
    "PRS-Residential Advisors",
    "PRS-Personal Care And Service Workers, All Other",
    "SAL-First-Line Supervisors Of Retail Sales Workers",
    "SAL-First-Line Supervisors Of Non-Retail Sales Workers",
    "SAL-Cashiers",
    "SAL-Counter And Rental Clerks",
    "SAL-Parts Salespersons",
    "SAL-Retail Salespersons",
    "SAL-Advertising Sales Agents",
    "SAL-Insurance Sales Agents",
    "SAL-Securities, Commodities, And Financial Services Sales Agents",
    "SAL-Travel Agents",
    "SAL-Sales Representatives Of Services, Except Advertising, Insurance, Financial Services, And Travel",
    "SAL-Sales Representatives, Wholesale And Manufacturing",
    "SAL-Models, Demonstrators, And Product Promoters",
    "SAL-Real Estate Brokers And Sales Agents",
    "SAL-Sales Engineers",
    "SAL-Telemarketers",
    "SAL-Door-To-Door Sales Workers, News And Street Vendors, And Related Workers",
    "SAL-Sales And Related Workers, All Other",
    "OFF-First-Line Supervisors Of Office And Administrative Support Workers",
    "OFF-Switchboard Operators, Including Answering Service",
    "OFF-Telephone Operators",
    "OFF-Communications Equipment Operators, All Other",
    "OFF-Bill And Account Collectors",
    "OFF-Billing And Posting Clerks",
    "OFF-Bookkeeping, Accounting, And Auditing Clerks",
    "OFF-Payroll And Timekeeping Clerks",
    "OFF-Procurement Clerks",
    "OFF-Tellers",
    "OFF-Other Financial Clerks",
    "OFF-Court, Municipal, And License Clerks",
    "OFF-Credit Authorizers, Checkers, And Clerks",
    "OFF-Customer Service Representatives",
    "OFF-Eligibility Interviewers, Government Programs",
    "OFF-File Clerks",
    "OFF-Hotel, Motel, And Resort Desk Clerks",
    "OFF-Interviewers, Except Eligibility And Loan",
    "OFF-Library Assistants, Clerical",
    "OFF-Loan Interviewers And Clerks",
    "OFF-New Accounts Clerks",
    "OFF-Human Resources Assistants, Except Payroll And Timekeeping",
    "OFF-Receptionists And Information Clerks",
    "OFF-Reservation And Transportation Ticket Agents And TravelClerks",
    "OFF-Correspondence Clerks And Order Clerks",
    "OFF-Other Information And Records Clerks",
    "OFF-Cargo And Freight Agents",
    "OFF-Couriers And Messengers",
    "OFF-Public Safety Telecommunicators",
    "OFF-Dispatchers, Except Police, Fire, And Ambulance",
    "OFF-Meter Readers, Utilities",
    "OFF-Postal Service Clerks",
    "OFF-Postal Service Mail Carriers",
    "OFF-Postal Service Mail Sorters, Processors, And ProcessingMachine Operators",
    "OFF-Production, Planning, And Expediting Clerks",
    "OFF-Shipping, Receiving, And Traffic Clerks",
    "OFF-Weighers, Measurers, Checkers, And Samplers, Recordkeeping",
    "OFF-Executive Secretaries And Executive Administrative Assistants",
    "OFF-Legal Secretaries And Administrative Assistants",
    "OFF-Medical Secretaries And Administrative Assistants",
    "OFF-Secretaries And Administrative, Except Legal, Medical, And Executive",
    "OFF-Data Entry Keyers",
    "OFF-Word Processors And Typists",
    "OFF-Insurance Claims And Policy Processing Clerks",
    "OFF-Mail Clerks And Mail Machine Operators, Except Postal Service",
    "OFF-Office Clerks, General",
    "OFF-Office Machine Operators, Except Computer",
    "OFF-Proofreaders And Copy Markers",
    "OFF-Statistical Assistants",
    "OFF-Other Office And Administrative Support Workers",
    "FFF-First-Line Supervisors Of Farming, Fishing, And Forestry Workers",
    "FFF-Agricultural Inspectors",
    "FFF-Graders And Sorters, Agricultural Products",
    "FFF-Other Agricultural Workers",
    "FFF-Fishing And Hunting Workers",
    "FFF-Forest And Conservation Workers",
    "FFF-Logging Workers",
    "CON-First-Line Supervisors Of Construction Trades And Extraction Workers",
    "CON-Boilermakers",
    "CON-Carpenters",
    "CON-Carpet, Floor, And Tile Installers And Finishers",
    "CON-Cement Masons, Concrete Finishers, And Terrazzo Workers",
    "CON-Construction Laborers",
    "CON-Construction Equipment Operators",
    "CON-Drywall Installers, Ceiling Tile Installers, And Tapers",
    "CON-Electricians",
    "CON-Glaziers",
    "CON-Insulation Workers",
    "CON-Painters And Paperhangers",
    "CON-Pipelayers",
    "CON-Plumbers, Pipefitters, And Steamfitters",
    "CON-Plasterers And Stucco Masons",
    "CON-Roofers",
    "CON-Sheet Metal Workers",
    "CON-Structural Iron And Steel Workers",
    "CON-Solar Photovoltaic Installers",
    "CON-Brickmasons, Blockmasons, Stonemasons, And Reinforcing Iron And Rebar Workers",
    "CON-Helpers, Construction Trades",
    "CON-Construction And Building Inspectors",
    "CON-Elevator Installers And Repairers",
    "CON-Fence Erectors",
    "CON-Hazardous Materials Removal Workers",
    "CON-Highway Maintenance Workers",
    "CON-Rail-Track Laying And Maintenance Equipment Operators",
    "CON-Other Construction And Related Workers",
    "EXT_Surface Mining Machine Operators And Earth Drillers",
    "EXT-Explosives Workers, Ordnance Handling Experts, And Blasters",
    "EXT-Underground Mining Machine Operators",
    "EXT-Other Extraction Workers",
    "EXT-Derrick, Rotary Drill, And Service Unit Operators, And Roustabouts, Oil, Gas, And Mining",
    "RPR-First-Line Supervisors Of Mechanics, Installers, And Repairers",
    "RPR-Computer, Automated Teller, And Office Machine Repairers",
    "RPR-Radio And Telecommunications Equipment Installers And Repairers",
    "RPR-Avionics Technicians",
    "RPR-Electric Motor, Power Tool, And Related Repairers",
    "RPR-Electronic Home Entertainment Equipment Installers And Repairers",
    "RPR-Security And Fire Alarm Systems Installers",
    "RPR-Other Electrical And Electronic Equipment Mechanics, Installers, and Repairers",
    "RPR-Aircraft Mechanics And Service Technicians",
    "RPR-Automotive Body And Related Repairers",
    "RPR-Automotive Glass Installers And Repairers",
    "RPR-Automotive Service Technicians And Mechanics",
    "RPR-Bus And Truck Mechanics And Diesel Engine Specialists",
    "RPR-Heavy Vehicle And Mobile Equipment Service Technicians And Mechanics",
    "RPR-Small Engine Mechanics",
    "RPR-Miscellaneous Vehicle And Mobile Equipment Mechanics, Installers, And Repairers",
    "RPR-Control And Valve Installers And Repairers",
    "RPR-Heating, Air Conditioning, And Refrigeration Mechanics And Installers",
    "RPR-Home Appliance Repairers",
    "RPR-Maintenance Workers, Machinery",
    "RPR-Millwrights",
    "RPR-Industrial And Refractory Machinery Mechanics",
    "RPR-Electrical Power-Line Installers And Repairers",
    "RPR-Telecommunications Line Installers And Repairers",
    "RPR-Precision Instrument And Equipment Repairers",
    "RPR-Maintenance And Repair Workers, General",
    "RPR-Coin, Vending, And Amusement Machine Servicers And Repairers",
    "RPR-Locksmiths And Safe Repairers",
    "RPR-Riggers",
    "RPR-Helpers--Installation, Maintenance, And Repair Workers",
    "RPR-Other Installation, Maintenance, And Repair Workers",
    "PRD-First-Line Supervisors Of Production And Operating Workers",
    "PRD-Electrical, Electronics, And Electromechanical Assemblers",
    "PRD-Engine And Other Machine Assemblers",
    "PRD-Structural Metal Fabricators And Fitters",
    "PRD-Other Assemblers and Fabricators",
    "PRD-Bakers",
    "PRD-Butchers And Other Meat, Poultry, And Fish Processing Workers",
    "PRD-Food And Tobacco Roasting, Baking, And Drying Machine Operators And Tenders",
    "PRD-Food Batchmakers",
    "PRD-Food Cooking Machine Operators And Tenders",
    "PRD-Food Processing Workers, All Other",
    "PRD-Forming Machine Setters, Operators, And Tenders, Metal And Plastic",
    "PRD-Cutting, Punching, And Press Machine Setters, Operators, And Tenders, Metal And Plastic",
    "Grinding, Lapping, Polishing, And Buffing Machine Tool Setters, Operators, And Tenders, Metal and Plastic",
    "Other Machine Tool Setters, Operators, And Tenders,Metal And Plastic",
    "PRD-Machinists",
    "PRD-Metal Furnace Operators, Tenders, Pourers, And Casters",
    "PRD-Model Makers, Patternmakers, And Molding Machine Setters, Metal And Plastic",
    "PRD-Tool And Die Makers",
    "PRD-Welding, Soldering, And Brazing Workers",
    "PRD-Other Metal Workers And Plastic Workers",
    "PRD-Prepress Technicians And Workers",
    "PRD-Printing Press Operators",
    "PRD-Print Binding And Finishing Workers",
    "PRD-Laundry And Dry-Cleaning Workers",
    "PRD-Pressers, Textile, Garment, And Related Materials",
    "PRD-Sewing Machine Operators",
    "PRD-Shoe And Leather Workers",
    "PRD-Tailors, Dressmakers, And Sewers",
    "PRD-Textile Machine Setters, Operators, And Tenders",
    "PRD-Upholsterers",
    "PRD-Other Textile, Apparel, And Furnishings Workers",
    "PRD-Cabinetmakers And Bench Carpenters",
    "PRD-Furniture Finishers",
    "PRD-Sawing Machine Setters, Operators, And Tenders, Wood",
    "PRD-Woodworking Machine Setters, Operators, And Tenders, Except Sawing",
    "PRD-Other Woodworkers",
    "PRD-Power Plant Operators, Distributors, And Dispatchers",
    "PRD-Stationary Engineers And Boiler Operators",
    "PRD-Water And Wastewater Treatment Plant And System Operators",
    "PRD-Miscellaneous Plant And System Operators",
    "PRD-Chemical Processing Machine Setters, Operators, And Tenders",
    "PRD-Crushing, Grinding, Polishing, Mixing, And Blending Workers",
    "PRD-Cutting Workers",
    "PRD-Extruding, Forming, Pressing, And Compacting Machine Setters, Operators, And Tenders",
    "PRD-Furnace, Kiln, Oven, Drier, And Kettle Operators And Tenders",
    "PRD-Inspectors, Testers, Sorters, Samplers, And Weighers",
    "PRD-Jewelers And Precious Stone And Metal Workers",
    "Dental And Ophthalmic Laboratory Technicians And Medical Appliance Technicians",
    "PRD-Packaging And Filling Machine Operators And Tenders",
    "PRD-Painting Workers",
    "PRD-Photographic Process Workers And Processing Machine Operators",
    "PRD-Computer Numerically Controlled Tool Operators And Programmers",
    "PRD-Adhesive Bonding Machine Operators And Tenders",
    "PRD-Etchers And Engravers",
    "PRD-Molders, Shapers, And Casters, Except Metal And Plastic",
    "PRD-Paper Goods Machine Setters, Operators, And Tenders",
    "PRD-Tire Builders",
    "PRD-Helpers-Production Workers",
    "PRD-Miscellaneous Production Workers, Including Equipment Operators and Tenders",
    "TRN-Supervisors Of Transportation And Material Moving Workers",
    "TRN-Aircraft Pilots And Flight Engineers",
    "TRN-Air Traffic Controllers And Airfield Operations Specialists",
    "TRN-Flight Attendants",
    "TRN-Ambulance Drivers And Attendants, Except Emergency Medical Technicians",
    "TRN-Driver/Sales Workers And Truck Drivers",
    "TRN-Bus Drivers, School",
    "TRN-Bus Drivers, Transit And Intercity",
    "TRN-Shuttle Drivers and Chauffeurs",
    "TRN-Taxi Drivers",
    "TRN-Motor Vehicle Operators, All Other",
    "TRN-Locomotive Engineers And Operators",
    "TRN-Railroad Conductors And Yardmasters",
    "TRN-Other Rail Transportation Workers",
    "TRN-Ship And Boat Captains And Operators",
    "TRN-Sailors And Marine Oilers, And Ship Engineers",
    "TRN-Parking Lot Attendants",
    "TRN-Transportation Service Attendants",
    "TRN-Transportation Inspectors",
    "TRN-Passenger Attendants",
    "TRN-Other Transportation Workers",
    "TRN-Crane And Tower Operators",
    "TRN-Industrial Truck And Tractor Operators",
    "TRN-Cleaners Of Vehicles And Equipment",
    "TRN-Laborers And Freight, Stock, And Material Movers, Hand",
    "TRN-Machine Feeders And Offbearers",
    "TRN-Packers And Packagers, Hand",
    "TRN-Stockers And Order Fillers",
    "TRN-Pumping Station Operators",
    "TRN-Refuse And Recyclable Material Collectors",
    "TRN-Conveyor, Dredge, And Hoist And Winch Operators",
    "TRN-Other Material Moving Workers",
    "MIL-Military Officer Special And Tactical Operations Leaders",
    "MIL-First-Line Enlisted Military Supervisors",
    "MIL-Military Enlisted Tactical Operations And Air/Weapons Specialists And Crew Members",
    "MIL-Military, Rank Not Specified",
    "Unemployed And Last Worked 5 Years Ago Or Earlier Or Never Worked",
  ],

  "Migration recode - State or foreign country code": [
    "Alabama/AL",
    "Alaska/AK",
    "Arizona/AZ",
    "Arkansas/AR",
    "California/CA",
    "Colorado/CO",
    "Connecticut/CT",
    "Delaware/DE",
    "District of Columbia/DC",
    "Florida/FL",
    "Georgia/GA",
    "Hawaii/HI",
    "Idaho/ID",
    "Illinois/IL",
    "Indiana/IN",
    "Iowa/IA",
    "Kansas/KS",
    "Kentucky/KY",
    "Louisiana/LA",
    "Maine/ME",
    "Maryland/MD",
    "Massachusetts/MA",
    "Michigan/MI",
    "Minnesota/MN",
    "Mississippi/MS",
    "Missouri/MO",
    "Montana/MT",
    "Nebraska/NE",
    "Nevada/NV",
    "New Hampshire/NH",
    "New Jersey/NJ",
    "New Mexico/NM",
    "New York/NY",
    "North Carolina/NC",
    "North Dakota/ND",
    "Ohio/OH",
    "Oklahoma/OK",
    "Oregon/OR",
    "Pennsylvania/PA",
    "Rhode Island/RI",
    "South Carolina/SC",
    "South Dakota/SD",
    "Tennessee/TN",
    "Texas/TX",
    "Utah/UT",
    "Vermont/VT",
    "Virginia/VA",
    "Washington/WA",
    "West Virginia/WV",
    "Wisconsin/WI",
    "Wyoming/WY",
    "Puerto Rico",
    "France",
    "Germany",
    "Northern Europe, Not Specified",
    "Eastern Europe, Not Specified",
    "Western Europe or Other Europe, Not Specified",
    "Italy",
    "Spain",
    "United Kingdom, Excluding England",
    "England",
    "Russia",
    "Ukraine (2017 or later)",
    "Afghanistan",
    "China, Hong Kong, Macau and Paracel Islands",
    "India",
    "Israel (2017 or later)",
    "Japan",
    "Korea",
    "Nepal",
    "Pakistan",
    "Philippines",
    "Saudi Arabia",
    "Taiwan",
    "Thailand",
    "Turkey",
    "United Arab Emirates (2017 or later)",
    "Vietnam",
    "Eastern Asia, Not Specified",
    "Western Asia, Not Specified",
    "South Central Asia or Asia, Not Specified",
    "Canada",
    "Mexico",
    "El Salvador",
    "Guatemala",
    "Honduras",
    "Central America, Not Specified",
    "Cuba",
    "Dominican Republic",
    "Haiti",
    "Jamaica",
    "Caribbean and North America, Not Specified",
    "Brazil",
    "Colombia",
    "Ecuador (2017 or later)",
    "Peru (2017 or later)",
    "Venezuela (2017 or later)",
    "South America, Not Specified",
    "Egypt",
    "Ethiopia (2017 or later)",
    "Kenya (2017 or later)",
    "Nigeria",
    "Western Africa, Not Specified",
    "Northern Africa or Other Africa, Not Specified",
    "Eastern Africa, Not Specified",
    "Australia",
    "Other US Island Areas, Oceania, Not Specified, or At Sea",
  ],
  "Married, spouse present/spouse absent": [
    "Now married, spouse present",
    "Now married, spouse absent",
    "Widowed",
    "Divorced",
    "Separated",
    "Never married",
  ],
  Nativity: ["yes", "no"],
  "Nativity of parent": [
    "Living w/ 2 parents: Both Native",
    "Living w/ 2 parents: Father Foreign Born",
    "Living w/ 2 parents: Mother Foreign Born",
    "Living w/ 2 parents: BOTH Foreign Born",
    "Living w/ father only: Father Native",
    "Living w/ father only: Father Foreign Born",
    "Living w/ mother only: Mother Native",
    "Living w/ mother only: Mother Foreign Born",
  ],
  "Own child": ["no", "yes"],
  "Presence and age of own children": [
    "Females with own children under 6 years only",
    "Females with own children 6 to 17 years only",
    "Females with own children under 6 years and 6 to 17 years",
    "Females with no own children",
  ],
  "Place of birth": [
    "Alabama/AL",
    "Alaska/AK",
    "Arizona/AZ",
    "Arkansas/AR",
    "California/CA",
    "Colorado/CO",
    "Connecticut/CT",
    "Delaware/DE",
    "District of Columbia/DC",
    "Florida/FL",
    "Georgia/GA",
    "Hawaii/HI",
    "Idaho/ID",
    "Illinois/IL",
    "Indiana/IN",
    "Iowa/IA",
    "Kansas/KS",
    "Kentucky/KY",
    "Louisiana/LA",
    "Maine/ME",
    "Maryland/MD",
    "Massachusetts/MA",
    "Michigan/MI",
    "Minnesota/MN",
    "Mississippi/MS",
    "Missouri/MO",
    "Montana/MT",
    "Nebraska/NE",
    "Nevada/NV",
    "New Hampshire/NH",
    "New Jersey/NJ",
    "New Mexico/NM",
    "New York/NY",
    "North Carolina/NC",
    "North Dakota/ND",
    "Ohio/OH",
    "Oklahoma/OK",
    "Oregon/OR",
    "Pennsylvania/PA",
    "Rhode Island/RI",
    "South Carolina/SC",
    "South Dakota/SD",
    "Tennessee/TN",
    "Texas/TX",
    "Utah/UT",
    "Vermont/VT",
    "Virginia/VA",
    "Washington/WA",
    "West Virginia/WV",
    "Wisconsin/WI",
    "Wyoming/WY",
    "American Samoa",
    "Guam",
    "Commonwealth of the Northern Mariana Islands",
    "Puerto Rico",
    "US Virgin Islands",
    "Albania",
    "Austria",
    "Belgium",
    "Bulgaria",
    "Czechoslovakia",
    "Denmark",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Netherlands",
    "Norway",
    "Poland",
    "Portugal",
    "Azores Islands",
    "Romania",
    "Spain",
    "Sweden",
    "Switzerland",
    "United Kingdom, Not Specified",
    "England",
    "Scotland",
    "Northern Ireland (2017 or later)",
    "Yugoslavia",
    "Czech Republic",
    "Slovakia",
    "Bosnia and Herzegovina",
    "Croatia",
    "Macedonia",
    "Serbia",
    "Latvia",
    "Lithuania",
    "Armenia",
    "Azerbaijan",
    "Belarus",
    "Georgia",
    "Moldova",
    "Russia",
    "Ukraine",
    "USSR",
    "Europe (2017 or later)",
    "Kosovo (2017 or later)",
    "Montenegro",
    "Other Europe, Not Specified",
    "Afghanistan",
    "Bangladesh",
    "Bhutan",
    "Myanmar",
    "Cambodia",
    "China",
    "Hong Kong",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Israel",
    "Japan",
    "Jordan",
    "Korea",
    "Kazakhstan",
    "Kyrgyzstan (2017 or later)",
    "Kuwait",
    "Laos",
    "Lebanon",
    "Malaysia",
    "Mongolia (2017 or later)",
    "Nepal",
    "Pakistan",
    "Philippines",
    "Saudi Arabia",
    "Singapore",
    "Sri Lanka",
    "Syria",
    "Taiwan",
    "Thailand",
    "Turkey",
    "United Arab Emirates",
    "Uzbekistan",
    "Vietnam",
    "Yemen",
    "Asia",
    "South Central Asia, Not Specified",
    "Other Asia, Not Specified",
    "Bermuda",
    "Canada",
    "Mexico",
    "Belize",
    "Costa Rica",
    "El Salvador",
    "Guatemala",
    "Honduras",
    "Nicaragua",
    "Panama",
    "Antigua and Barbuda",
    "Bahamas",
    "Barbados",
    "Cuba",
    "Dominica",
    "Dominican Republic",
    "Grenada",
    "Haiti",
    "Jamaica",
    "St. Kitts-Nevis (2017 or later)",
    "St. Lucia",
    "St. Vincent and the Grenadines",
    "Trinidad and Tobago",
    "West Indies",
    "Caribbean, Not Specified",
    "Argentina",
    "Bolivia",
    "Brazil",
    "Chile",
    "Colombia",
    "Ecuador",
    "Guyana",
    "Paraguay",
    "Peru",
    "Uruguay",
    "Venezuela",
    "South America",
    "Americas, Not Specified",
    "Algeria",
    "Cameroon",
    "Cabo Verde",
    "Congo",
    "Egypt",
    "Ethiopia",
    "Eritrea",
    "Gambia",
    "Ghana",
    "Guinea",
    "Ivory Coast (2017 or later)",
    "Kenya",
    "Liberia",
    "Libya",
    "Morocco",
    "Nigeria",
    "Rwanda (2017 or later)",
    "Senegal",
    "Sierra Leone",
    "Somalia",
    "South Africa",
    "Sudan",
    "Tanzania",
    "Togo",
    "Tunisia (2017 or later)",
    "Uganda",
    "Democratic Republic of Congo (Zaire)",
    "Zambia",
    "Zimbabwe",
    "Africa",
    "South Sudan (2017 or later)",
    "Northern Africa, Not Specified",
    "Western Africa, Not Specified",
    "Other Africa, Not Specified",
    "Eastern Africa, Not Specified",
    "Australia",
    "Fiji",
    "Marshall Islands",
    "Micronesia",
    "New Zealand",
    "Tonga",
    "Samoa",
    "Other US Island Areas, Oceania, Not Specified, or at Sea",
  ],
  "Place of work - State or foreign country recode": [
    "Alabama/AL",
    "Alaska/AK",
    "Arizona/AZ",
    "Arkansas/AR",
    "California/CA",
    "Colorado/CO",
    "Connecticut/CT",
    "Delaware/DE",
    "District of Columbia/DC",
    "Florida/FL",
    "Georgia/GA",
    "Hawaii/HI",
    "Idaho/ID",
    "Illinois/IL",
    "Indiana/IN",
    "Iowa/IA",
    "Kansas/KS",
    "Kentucky/KY",
    "Louisiana/LA",
    "Maine/ME",
    "Maryland/MD",
    "Massachusetts/MA",
    "Michigan/MI",
    "Minnesota/MN",
    "Mississippi/MS",
    "Missouri/MO",
    "Montana/MT",
    "Nebraska/NE",
    "Nevada/NV",
    "New Hampshire/NH",
    "New Jersey/NJ",
    "New Mexico/NM",
    "New York/NY",
    "North Carolina/NC",
    "North Dakota/ND",
    "Ohio/OH",
    "Oklahoma/OK",
    "Oregon/OR",
    "Pennsylvania/PA",
    "Rhode Island/RI",
    "South Carolina/SC",
    "South Dakota/SD",
    "Tennessee/TN",
    "Texas/TX",
    "Utah/UT",
    "Vermont/VT",
    "Virginia/VA",
    "Washington/WA",
    "West Virginia/WV",
    "Wisconsin/WI",
    "Wyoming/WY",
    "Puerto Rico",
    "Europe",
    "Eastern Asia",
    "Other Asia, Not Specified",
    "Canada",
    "Mexico",
    "Americas, Not Specified",
    "Other US Island Areas Not Specified, Africa, Oceania, at Sea, or Abroad, Not Specified",
  ],
  "Private health insurance coverage": ["yes", "no"],
  "Public health coverage": ["yes", "no"],
  "Quarter of birth": [
    "January through March",
    "April through June",
    "July through September",
    "October through December",
  ],
  "Race/Ethnicity": [
    "White alone",
    "Black alone",
    "American Indian alone",
    "Alaskan Native alone",
    "Am Indian and Alaskan Native tribes specified",
    "Asian alone",
    "Native Hawaiian and other PI alone",
    "Some other race alone",
    "2+ major race groups",
  ],
  "American Indian and Alaska Native": ["no", "yes"],
  Asian: ["no", "yes"],
  Black: ["no", "yes"],
  "Native Hawaiian": ["no", "yes"],

  "Other Pacific Islander": ["no", "yes"],
  "Some other race": ["no", "yes"],
  White: ["no", "yes"],
  "Related child": ["no", "yes"],
  "Field of degree - Science and Engineering flag": ["yes", "no"],
  "Field of degree - Science and Engineering Related flag": ["yes", "no"],
  "Subfamily number": ["1.0", "2.0", "3.0"],
  "Subfamily relationship": [
    "Husband/wife no children",
    "Husband/wife with children",
    "Parent in a parent/child subfamily",
    "Child in a married-couple subfamily",
    "Child in a mother-child subfamily",
    "Child in a father-child subfamily",
  ],
  "Veteran Period of Service": [
    "Gulf War: 9/2001 or later",
    "Gulf War: 9/2001 or later and Gulf War: 8/1990 - 8/2001",
    "Gulf War: 9/2001 or later and Gulf War: 8/1990 - 8/2001 and Vietnam Era",
    "Gulf War: 8/1990 - 8/2001",
    "Gulf War: 8/1990 - 8/2001 and Vietnam Era",
    "Vietnam Era",
    "Vietnam Era and Korean War",
    "Vietnam Era, Korean War, and WWII",
    "Korean War",
    "Korean War and WWII",
    "WWII",
    "Between Gulf War and Vietnam Era only",
    "Between Vietnam Era and Korean War only",
    "Between Korean War and World War II only",
    "Pre-WWII only",
  ],
  "World area of birth (2005-2017 categories)": [
    "US",
    "PR and US Island Areas",
    "Latin America",
    "Asia",
    "Europe",
    "Africa",
    "Northern America",
    "Oceania and at Sea",
  ],
  "Medicare coverage given through the eligibility coverage edit": [
    "no",
    "yes",
  ],
  "Medicaid coverage given through the eligibility coverage edit": [
    "no",
    "yes",
  ],
  "TRICARE coverage given through the eligibility coverage edit": ["no", "yes"],
  Age: ["<18", "18-24", "26-34", "35-44", "45-54", "56-64", ">65"],
  "Years since divorce": ["<1", "1-5", "6-10", ">10"],
  "Usual hours worked per week past 12 months": ["<10", "10-40", ">40"],
};
