export const ACS7GroupByOptions = [
  "Ability to speak English",
  "Age",
  "Ambulatory difficulty",
  "American Indian and Alaska Native",
  "Ancestry recode",
  "Ancestry recode - first entry",
  "Ancestry recode - second entry",
  "Asian",
  "Available for Work",
  "Black",
  "Citizenship status",
  "Class of Worker",
  "Cognitive difficulty",
  "Decade of entry",
  "Divorced in the past 12 months",
  "Educational attainment",
  "Employment status of parents",
  "Field of degree - Science and Engineering Related flag",
  "Field of degree - Science and Engineering flag",
  "Gave birth within past year",
  "Georgraphic division",
  "Grade level attending",
  "Grandparents living with grandchildren",
  "Health insurance coverage recode",
  "Hearing difficulty",
  "Hispanic, Detailed",
  "Independent living difficulty",
  "Indian Health Service",
  "Industry group",
  "Industry recode",
  "Informed of recall",
  "Insurance purchased directly from an insurance company",
  "Insurance through a current or former employer or union",
  "Language other than English spoken at home",
  "Language other than English spoken at home",
  "Length of time responsible for grandchildren",
  "Looking for work",
  "Marital status",
  "Married in the past 12 months",
  "Married, spouse present/spouse absent",
  "Means of transportation to work",
  "Medicaid coverage given through the eligibility coverage edit",
  "Medicaid, Medical Assistance, or any kind of government-assistance plan for those with low incomes or a disability",
  "Medicare coverage given through the eligibility coverage edit",
  "Medicare, for people 65 and older, or people with certain disabilities",
  "Migration recode - State or foreign country code",
  "Military service",
  "Mobility status (lived here 1 year ago)",
  "Native Hawaiian",
  "Nativity",
  "Nativity of parent",
  "Number of times married",
  "Number of vehicles calculated from JWRI",
  "Occupation group",
  "On layoff from work",
  "Other Pacific Islander",
  "Own child",
  "Place of birth",
  "Place of work - State or foreign country recode",
  "Place of work PUM area code",
  "Presence and age of own children",
  "Private health insurance coverage",
  "Public health coverage",
  "Public use microdata area code",
  "Quarter of birth",
  "Race/Ethnicity",
  "Raw labor-force status",
  "Recoded field of degree - first entry",
  "Recoded field of degree - second entry",
  "Region",
  "Related child",
  "Relationship to reference person",
  "Responsible for grandchildren",
  "School enrollment",
  "Self-care difficulty",
  "Served August 1990 - August 2001 (including Persian Gulf War)",
  "Served February 1955 - July 1964",
  "Served January 1947 - June 1950",
  "Served Korean War (July 1950 - January 1955)",
  "Served May 1975 - July 1990",
  "Served November 1941 or earlier",
  "Served September 2001 or later",
  "Served Vietnam era (August 1964 - April 1975)",
  "Served World War II (December 1941 - December 1946)",
  "Sex",
  "Some other race",
  "Standard Occupational Classification",
  "State code",
  "Subfamily number",
  "Subfamily relationship",
  "TRICARE coverage given through the eligibility coverage edit",
  "TRICARE or other military health care",
  "Temporary absence from work",
  "Usual hours worked per week past 12 months",
  "VA (Health Insurance through VA Health Care)",
  "Vehicle occupancy (to work)",
  "Veteran Period of Service",
  "Veteran Service Disability Rating (checkbox)",
  "Veteran Service Disability Rating (percentage)",
  "Vision difficulty",
  "Weeks worked during past 12 months",
  "When last worked",
  "White",
  "Widowed in the past 12 months",
  "With a disability",
  "Worked last week",
  "World area of birth (2005-2017 categories)",
  "Years since divorce",
];
