export const ZillowGroupByOptions = [
  "Architectural style of the home (i.e. ranch, colonial, split-level, etc…)",
  "Calculated total finished living area of the home",
  "City in which the property is located (if any)",
  "County in which the property is located",
  "Does the home have a hot tub or spa",
  "Is a fireplace present in this home",
  "Number of bathrooms in home including fractional bathrooms",
  "Number of bedrooms in home",
  "Number of fireplaces in a home (if any)",
  "Number of pools on the lot (if any)",
  "Number of stories or levels the home has",
  "Number of units the structure is built into (i.e. 2 = duplex, 3 = triplex, etc...)",
  "The building framing type (steel frame, wood frame, concrete/brick)",
  "Total number of garages on the lot including an attached garage",
  "Type of cooling system present in the home (if any)",
  "Type of home heating system",
  "Type of land use the property is zoned for",
  "What type of construction material was used to construct the home",
  "Year range built",
];
