export const ZillowCompareValues = {
  "Type of cooling system present in the home (if any)": [
    "Central",
    "nan",
    "Refrigeration",
    "Wall Unit",
    "Yes",
  ],
  "Architectural style of the home (i.e. ranch, colonial, split-level, etc…)": [
    "Cape Cod",
    "Colonial",
    "Contemporary",
    "Conventional",
    "Ranch/Rambler",
  ],
  "Number of bathrooms in home including fractional bathrooms": [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    ">10",
  ],
  "Number of bedrooms in home": [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    ">10",
  ],
  "The building framing type (steel frame, wood frame, concrete/brick)": [
    "Buildings having fireproofed structural steel frames carrying all wall, floor and roof loads. Wall, floor and roof structures are built of non-combustible materials.",
    "Buildings having fireproofed reinforced concrete frames carrying all wall floor and roof loads which are all non-combustible.",
    "Buildings having exterior walls built of a non-combustible material such as brick, concrete, block or poured concrete. Interior partitions and roof structures are built of combustible materials. Floor may be concrete or wood frame.",
    "Buildings having wood or wood and steel frames",
    "Specialized buildings that do not fit in any of the above categories",
  ],
  "Calculated total finished living area of the home": [
    "<1K",
    "1.5K-2K",
    "1K-1.5K",
    "2.5K-3K",
    "2K-2.5K",
    "3K-4K",
    ">4K",
  ],
  "Number of fireplaces in a home (if any)": ["0", "1", "2", "3", "4", ">4"],
  "Total number of garages on the lot including an attached garage": [
    "0",
    "1",
    "2",
    "3",
    "4",
    ">4",
  ],
  "Does the home have a hot tub or spa": ["no", "yes"],
  "Type of home heating system": [
    "Central",
    "Forced air",
    "Floor/Wall",
    "Gravity",
    "Heat Pump",
    "nan",
    "Radiant",
    "Solar",
    "Yes",
  ],
  "Number of pools on the lot (if any)": ["0.0", "1.0"],
  "Type of land use the property is zoned for": [
    "31.0",
    "47.0",
    "246.0",
    "247.0",
    "248.0",
    "260.0",
    "261.0",
    "263.0",
    "264.0",
    "265.0",
    "266.0",
    "267.0",
    "269.0",
    "275.0",
  ],
  "City in which the property is located (if any)": [
    "37882.0",
    "Acton",
    "Agoura Hills",
    "Alhambra",
    "Aliso Viejo",
    "Alondra Park",
    "Altadena",
    "Anaheim",
    "Arcadia",
    "Artesia",
    "Avalon",
    "Avocado Heights",
    "Azusa",
    "Baldwin Park",
    "Bell",
    "Bell Canyon",
    "Bell Gardens",
    "Bellflower",
    "Beverly Hills",
    "Bradbury",
    "Brea",
    "Buena Park",
    "Burbank",
    "Calabasas",
    "Camarillo",
    "Carpinteria",
    "Carson",
    "Castaic",
    "Cerritos",
    "Chino Hills",
    "Claremont",
    "Commerce",
    "Compton",
    "Costa Mesa",
    "Coto de Caza",
    "Covina",
    "Cudahy",
    "Culver City",
    "Cypress",
    "Dana Point",
    "Diamond Bar",
    "Downey",
    "Duarte",
    "East La Mirada",
    "East Los Angeles",
    "East Pasadena",
    "El Monte",
    "El Segundo",
    "Fillmore",
    "Florence-Graham",
    "Fountain Valley",
    "Fullerton",
    "Garden Grove",
    "Gardena",
    "Glendale",
    "Glendora",
    "Hacienda Heights",
    "Hawaiian Gardens",
    "Hawthorne",
    "Hermosa Beach",
    "Hidden Hills",
    "Huntington Beach",
    "Huntington Park",
    "Inglewood",
    "Irvine",
    "Irwindale",
    "La Canada Flintridge",
    "La Crescenta-Montrose",
    "La Habra",
    "La Habra Heights",
    "La Mirada",
    "La Palma",
    "La Puente",
    "La Verne",
    "Ladera Heights",
    "Ladera Ranch",
    "Laguna Beach",
    "Laguna Hills",
    "Laguna Niguel",
    "Laguna Woods",
    "Lake Forest",
    "Lake Hughes",
    "Lakewood",
    "Lancaster",
    "Lawndale",
    "Lebec",
    "Littlerock",
    "Llano",
    "Lomita",
    "Long Beach",
    "Los Alamitos",
    "Los Angeles",
    "Lynwood",
    "Malibu",
    "Manhattan Beach",
    "Marina del Rey",
    "Maywood",
    "Mission Viejo",
    "Monrovia",
    "Montclair",
    "Montebello",
    "Monterey Park",
    "Moorpark",
    "Newport Beach",
    "Newport Coast",
    "North Tustin",
    "Norwalk",
    "Oak Park",
    "Oak View",
    "Oceanside",
    "Ojai",
    "Orange",
    "Oxnard",
    "Palmdale",
    "Palos Verdes Estates",
    "Palos Verdes Peninsula",
    "Paramount",
    "Pasadena",
    "Pearblossom",
    "Pico Rivera",
    "Pinon Hills",
    "Piru",
    "Placentia",
    "Pomona",
    "Port Hueneme",
    "Rancho Palos Verdes",
    "Rancho Santa Margarita",
    "Redondo Beach",
    "Rolling Hills",
    "Rolling Hills Estates",
    "Rosamond",
    "Rosemead",
    "Rowland Heights",
    "San Clemente",
    "San Dimas",
    "San Fernando",
    "San Gabriel",
    "San Juan Capistrano",
    "San Marino",
    "Santa Ana",
    "Santa Clarita",
    "Santa Fe Springs",
    "Santa Monica",
    "Santa Paula",
    "Seal Beach",
    "Sierra Madre",
    "Signal Hill",
    "Silverado",
    "Simi Valley",
    "Somis",
    "South El Monte",
    "South Gate",
    "South Pasadena",
    "South San Jose Hills",
    "South Whittier",
    "Stanton",
    "Sunset Beach",
    "Temple City",
    "Thousand Oaks",
    "Topanga",
    "Torrance",
    "Tustin",
    "Upland",
    "Valinda",
    "Valyermo",
    "Ventura",
    "Vernon",
    "View Park-Windsor Hills",
    "Villa Park",
    "Walnut",
    "West Athens",
    "West Carson",
    "West Compton",
    "West Covina",
    "West Hollywood",
    "West Puente Valley",
    "West Whittier-Los Nietos",
    "Westlake Village",
    "Westminster",
    "Westmont",
    "Whittier",
    "Willowbrook",
    "Wrightwood",
    "Yorba Linda",
  ],
  "County in which the property is located": [
    "Los Angeles County",
    "Orange County",
    "Ventura County",
  ],
  "What type of construction material was used to construct the home": [
    "Frame",
    "Metal",
    "Masonry",
  ],
  "Number of units the structure is built into (i.e. 2 = duplex, 3 = triplex, etc...)":
    ["1", "2", "3", "4", "5-10", ">10"],
  "Number of stories or levels the home has": [
    "1.0",
    "2.0",
    "3.0",
    "4.0",
    "5.0",
  ],
  "Is a fireplace present in this home": ["no", "yes"],
  "Year range built": [
    "1985-1989",
    "1990-1994",
    "1995-1999",
    "2000-2004",
    "2005-2009",
    "2010-2014",
  ],
};
