export const ZillowValuesDict = {
  "Type of cooling system present in the home (if any)": {
    Central: "1.0",
    nan: "5.0",
    Refrigeration: "9.0",
    "Wall Unit": "11.0",
    Yes: "13.0",
  },
  "Architectural style of the home (i.e. ranch, colonial, split-level, etc…)": {
    "Cape Cod": "3.0",
    Colonial: "5.0",
    Contemporary: "7.0",
    Conventional: "8.0",
    "Ranch/Rambler": "21.0",
  },
  "Number of bathrooms in home including fractional bathrooms": {
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "10": "10",
    "9": "9",
    ">10": ">10",
  },
  "Number of bedrooms in home": {
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    ">10": ">10",
  },
  "The building framing type (steel frame, wood frame, concrete/brick)": {
    "Buildings having fireproofed structural steel frames carrying all wall, floor and roof loads. Wall, floor and roof structures are built of non-combustible materials.":
      "1.0",

    "Buildings having fireproofed reinforced concrete frames carrying all wall floor and roof loads which are all non-combustible.":
      "2.0",

    "Buildings having exterior walls built of a non-combustible material such as brick, concrete, block or poured concrete. Interior partitions and roof structures are built of combustible materials. Floor may be concrete or wood frame.":
      "3.0",
    "Buildings having wood or wood and steel frames": "4.0",

    "Specialized buildings that do not fit in any of the above categories":
      "5.0",
  },
  "Calculated total finished living area of the home": {
    "<1K": "<1K",
    "1.5K-2K": "1.5K-2K",
    "1K-1.5K": "1K-1.5K",
    "2.5K-3K": "2.5K-3K",
    "2K-2.5K": "2K-2.5K",
    "3K-4K": "3K-4K",
    ">4K": ">4K",
  },
  "Number of fireplaces in a home (if any)": {
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    ">4": ">4",
  },
  "Total number of garages on the lot including an attached garage": {
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    ">4": ">4",
  },
  "Does the home have a hot tub or spa": {
    no: "no",
    yes: "yes",
  },
  "Type of home heating system": {
    "2.0": "Central",
    "6.0": "Forced air",
    "7.0": "Floor/Wall",
    "10.0": "Gravity",
    "11.0": "Heat Pump",
    "13.0": "nan",
    "18.0": "Radiant",
    "20.0": "Solar",
    "24.0": "Yes",
  },
  "Number of pools on the lot (if any)": {
    "0.0": "0.0",
    "1.0": "1.0",
  },
  "Type of land use the property is zoned for": {
    "31.0": "31.0",
    "47.0": "47.0",
    "246.0": "246.0",
    "247.0": "247.0",
    "248.0": "248.0",
    "260.0": "260.0",
    "261.0": "261.0",
    "263.0": "263.0",
    "264.0": "264.0",
    "265.0": "265.0",
    "266.0": "266.0",
    "267.0": "267.0",
    "269.0": "269.0",
    "275.0": "275.0",
  },
  "City in which the property is located (if any)": {
    "37882.0": "37882.0",
    Acton: "Acton",
    "Agoura Hills": "Agoura Hills",
    Alhambra: "Alhambra",
    "Aliso Viejo": "Aliso Viejo",
    "Alondra Park": "Alondra Park",
    Altadena: "Altadena",
    Anaheim: "Anaheim",
    Arcadia: "Arcadia",
    Artesia: "Artesia",
    Avalon: "Avalon",
    "Avocado Heights": "Avocado Heights",
    Azusa: "Azusa",
    "Baldwin Park": "Baldwin Park",
    Bell: "Bell",
    "Bell Canyon": "Bell Canyon",
    "Bell Gardens": "Bell Gardens",
    Bellflower: "Bellflower",
    "Beverly Hills": "Beverly Hills",
    Bradbury: "Bradbury",
    Brea: "Brea",
    "Buena Park": "Buena Park",
    Burbank: "Burbank",
    Calabasas: "Calabasas",
    Camarillo: "Camarillo",
    Carpinteria: "Carpinteria",
    Carson: "Carson",
    Castaic: "Castaic",
    Cerritos: "Cerritos",
    "Chino Hills": "Chino Hills",
    Claremont: "Claremont",
    Commerce: "Commerce",
    Compton: "Compton",
    "Costa Mesa": "Costa Mesa",
    "Coto de Caza": "Coto de Caza",
    Covina: "Covina",
    Cudahy: "Cudahy",
    "Culver City": "Culver City",
    Cypress: "Cypress",
    "Dana Point": "Dana Point",
    "Diamond Bar": "Diamond Bar",
    Downey: "Downey",
    Duarte: "Duarte",
    "East La Mirada": "East La Mirada",
    "East Los Angeles": "East Los Angeles",
    "East Pasadena": "East Pasadena",
    "El Monte": "El Monte",
    "El Segundo": "El Segundo",
    Fillmore: "Fillmore",
    "Florence-Graham": "Florence-Graham",
    "Fountain Valley": "Fountain Valley",
    Fullerton: "Fullerton",
    "Garden Grove": "Garden Grove",
    Gardena: "Gardena",
    Glendale: "Glendale",
    Glendora: "Glendora",
    "Hacienda Heights": "Hacienda Heights",
    "Hawaiian Gardens": "Hawaiian Gardens",
    Hawthorne: "Hawthorne",
    "Hermosa Beach": "Hermosa Beach",
    "Hidden Hills": "Hidden Hills",
    "Huntington Beach": "Huntington Beach",
    "Huntington Park": "Huntington Park",
    Inglewood: "Inglewood",
    Irvine: "Irvine",
    Irwindale: "Irwindale",
    "La Canada Flintridge": "La Canada Flintridge",
    "La Crescenta-Montrose": "La Crescenta-Montrose",
    "La Habra": "La Habra",
    "La Habra Heights": "La Habra Heights",
    "La Mirada": "La Mirada",
    "La Palma": "La Palma",
    "La Puente": "La Puente",
    "La Verne": "La Verne",
    "Ladera Heights": "Ladera Heights",
    "Ladera Ranch": "Ladera Ranch",
    "Laguna Beach": "Laguna Beach",
    "Laguna Hills": "Laguna Hills",
    "Laguna Niguel": "Laguna Niguel",
    "Laguna Woods": "Laguna Woods",
    "Lake Forest": "Lake Forest",
    "Lake Hughes": "Lake Hughes",
    Lakewood: "Lakewood",
    Lancaster: "Lancaster",
    Lawndale: "Lawndale",
    Lebec: "Lebec",
    Littlerock: "Littlerock",
    Llano: "Llano",
    Lomita: "Lomita",
    "Long Beach": "Long Beach",
    "Los Alamitos": "Los Alamitos",
    "Los Angeles": "Los Angeles",
    Lynwood: "Lynwood",
    Malibu: "Malibu",
    "Manhattan Beach": "Manhattan Beach",
    "Marina del Rey": "Marina del Rey",
    Maywood: "Maywood",
    "Mission Viejo": "Mission Viejo",
    Monrovia: "Monrovia",
    Montclair: "Montclair",
    Montebello: "Montebello",
    "Monterey Park": "Monterey Park",
    Moorpark: "Moorpark",
    "Newport Beach": "Newport Beach",
    "Newport Coast": "Newport Coast",
    "North Tustin": "North Tustin",
    Norwalk: "Norwalk",
    "Oak Park": "Oak Park",
    "Oak View": "Oak View",
    Oceanside: "Oceanside",
    Ojai: "Ojai",
    Orange: "Orange",
    Oxnard: "Oxnard",
    Palmdale: "Palmdale",
    "Palos Verdes Estates": "Palos Verdes Estates",
    "Palos Verdes Peninsula": "Palos Verdes Peninsula",
    Paramount: "Paramount",
    Pasadena: "Pasadena",
    Pearblossom: "Pearblossom",
    "Pico Rivera": "Pico Rivera",
    "Pinon Hills": "Pinon Hills",
    Piru: "Piru",
    Placentia: "Placentia",
    Pomona: "Pomona",
    "Port Hueneme": "Port Hueneme",
    "Rancho Palos Verdes": "Rancho Palos Verdes",
    "Rancho Santa Margarita": "Rancho Santa Margarita",
    "Redondo Beach": "Redondo Beach",
    "Rolling Hills": "Rolling Hills",
    "Rolling Hills Estates": "Rolling Hills Estates",
    Rosamond: "Rosamond",
    Rosemead: "Rosemead",
    "Rowland Heights": "Rowland Heights",
    "San Clemente": "San Clemente",
    "San Dimas": "San Dimas",
    "San Fernando": "San Fernando",
    "San Gabriel": "San Gabriel",
    "San Juan Capistrano": "San Juan Capistrano",
    "San Marino": "San Marino",
    "Santa Ana": "Santa Ana",
    "Santa Clarita": "Santa Clarita",
    "Santa Fe Springs": "Santa Fe Springs",
    "Santa Monica": "Santa Monica",
    "Santa Paula": "Santa Paula",
    "Seal Beach": "Seal Beach",
    "Sierra Madre": "Sierra Madre",
    "Signal Hill": "Signal Hill",
    Silverado: "Silverado",
    "Simi Valley": "Simi Valley",
    Somis: "Somis",
    "South El Monte": "South El Monte",
    "South Gate": "South Gate",
    "South Pasadena": "South Pasadena",
    "South San Jose Hills": "South San Jose Hills",
    "South Whittier": "South Whittier",
    Stanton: "Stanton",
    "Sunset Beach": "Sunset Beach",
    "Temple City": "Temple City",
    "Thousand Oaks": "Thousand Oaks",
    Topanga: "Topanga",
    Torrance: "Torrance",
    Tustin: "Tustin",
    Upland: "Upland",
    Valinda: "Valinda",
    Valyermo: "Valyermo",
    Ventura: "Ventura",
    Vernon: "Vernon",
    "View Park-Windsor Hills": "View Park-Windsor Hills",
    "Villa Park": "Villa Park",
    Walnut: "Walnut",
    "West Athens": "West Athens",
    "West Carson": "West Carson",
    "West Compton": "West Compton",
    "West Covina": "West Covina",
    "West Hollywood": "West Hollywood",
    "West Puente Valley": "West Puente Valley",
    "West Whittier-Los Nietos": "West Whittier-Los Nietos",
    "Westlake Village": "Westlake Village",
    Westminster: "Westminster",
    Westmont: "Westmont",
    Whittier: "Whittier",
    Willowbrook: "Willowbrook",
    Wrightwood: "Wrightwood",
    "Yorba Linda": "Yorba Linda",
  },
  "County in which the property is located": {
    "Los Angeles County": "Los Angeles County",
    "Orange County": "Orange County",
    "Ventura County": "Ventura County",
  },

  "What type of construction material was used to construct the home": {
    "6.0": "Frame",
    "10.0": "Metal",
    "13.0": "Masonry",
  },
  "Number of units the structure is built into (i.e. 2 = duplex, 3 = triplex, etc...)":
    {
      "1": "1",
      "2": "2",
      "3": "3",
      "4": "4",
      "5-10": "5-10",
      ">10": ">10",
    },
  "Number of stories or levels the home has": {
    "1.0": "1.0",
    "2.0": "2.0",
    "3.0": "3.0",
    "4.0": "4.0",
    "5.0": "5.0",
  },
  "Is a fireplace present in this home": {
    no: "no",
    yes: "yes",
  },
  "Year range built": {
    "1985-1989": "1985-1989",
    "1990-1994": "1990-1994",
    "1995-1999": "1995-1999",
    "2000-2004": "2000-2004",
    "2005-2009": "2005-2009",
    "2010-2014": "2010-2014",
  },
};
