export const FlightsCompareValues = {
  Month: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  "Day of Month": ["1-10", "11-20", "21-31"],
  Airline: [
    "American Airlines Inc.",
    "Alaska Airlines Inc.",
    "JetBlue Airways",
    "Delta Air Lines Inc.",
    "Atlantic Southeast Airlines",
    "Frontier Airlines Inc.",
    "Hawaiian Airlines Inc.",
    "American Eagle Airlines Inc.",
    "Spirit Air Lines",
    "Skywest Airlines Inc.",
    "United Air Lines Inc.",
    "US Airways Inc.",
    "Virgin America",
    "Southwest Airlines Co.",
  ],
  "Scheduled Departure Hour": [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
  ],
  "Departure Hour": [
    "0.0",
    "1.0",
    "2.0",
    "3.0",
    "4.0",
    "5.0",
    "6.0",
    "7.0",
    "8.0",
    "9.0",
    "10.0",
    "11.0",
    "12.0",
    "13.0",
    "14.0",
    "15.0",
    "16.0",
    "17.0",
    "18.0",
    "19.0",
    "20.0",
    "21.0",
    "22.0",
    "23.0",
    "24.0",
  ],
  Distance: ["1000-1500", "1500-2000", "500-1000", "<500", ">2000"],
  Diverted: ["No", "Yes"],
  "Origin Airport": [
    "Aberdeen Regional Airport",
    "Abilene Regional Airport",
    "Abraham Lincoln Capital Airport",
    "Adak Airport",
    "Akron-Canton Regional Airport",
    "Albany International Airport",
    "Albert J. Ellis Airport",
    "Albuquerque International Sunport",
    "Alexandria International Airport",
    "Alpena County Regional Airport",
    "Appleton International Airport",
    "Arcata Airport",
    "Arnold Palmer Regional Airport",
    "Asheville Regional Airport",
    "Aspen-Pitkin County Airport",
    "Atlantic City International Airport",
    "Augusta Regional Airport (Bush Field)",
    "Austin-Bergstrom International Airport",
    "Baltimore-Washington International Airport",
    "Bangor International Airport",
    "Barkley Regional Airport",
    "Barnstable Municipal Airport",
    "Baton Rouge Metropolitan Airport",
    "Bellingham International Airport",
    "Bemidji Regional Airport",
    "Bert Mooney Airport",
    "Bethel Airport",
    "Bill and Hillary Clinton National Airport (Adams Field)",
    "Billings Logan International Airport",
    "Birmingham-Shuttlesworth International Airport",
    "Bishop International Airport",
    "Bismarck Municipal Airport",
    "Blue Grass Airport",
    "Bob Hope Airport (Hollywood Burbank Airport)",
    "Boise Airport (Boise Air Terminal)",
    "Bozeman Yellowstone International Airport (Gallatin Field Airport)",
    "Bradley International Airport",
    "Brainerd Lakes Regional Airport",
    "Brownsville/South Padre Island International Airport",
    "Brunswick Golden Isles Airport",
    "Buffalo Niagara International Airport",
    "Burlington International Airport",
    "Canyonlands Field",
    "Capital Region International Airport ( Lansing Capital City)",
    "Cedar City Regional Airport",
    "Central Illinois Regional Airport at Bloomington-Normal",
    "Central Nebraska Regional Airport",
    "Central Wisconsin Airport",
    "Charleston International Airport/Charleston AFB",
    "Charlotte Douglas International Airport",
    "Charlottesville-Albemarle Airport",
    "Chattanooga Metropolitan Airport (Lovell Field)",
    "Cherry Capital Airport",
    "Chicago Midway International Airport",
    "Chicago O'Hare International Airport",
    "Chippewa County International Airport",
    "Chippewa Valley Regional Airport",
    "Cincinnati/Northern Kentucky International Airport",
    "City of Colorado Springs Municipal Airport",
    "Cleveland Hopkins International Airport",
    "Coastal Carolina Regional Airport (Craven County Regional)",
    "Columbia Metropolitan Airport",
    "Columbia Regional Airport",
    "Columbus Metropolitan Airport",
    "Corpus Christi International Airport",
    "Cyril E. King Airport",
    "Dallas Love Field",
    "Dallas/Fort Worth International Airport",
    "Dane County Regional Airport",
    "Daytona Beach International Airport",
    "Deadhorse Airport (Prudhoe Bay Airport)",
    "Del Norte County Airport (Jack McNamara Field)",
    "Delta County Airport",
    "Denver International Airport",
    "Des Moines International Airport",
    "Destin-Fort Walton Beach Airport/Eglin AFB",
    "Detroit Metropolitan Airport",
    "Devils Lake Regional Airport",
    "Dickinson Theodore Roosevelt Regional Airport",
    "Dillingham Airport",
    "Dothan Regional Airport",
    "Dubuque Regional Airport",
    "Duluth International Airport",
    "Durango-La Plata County Airport",
    "Eagle County Regional Airport",
    "East Texas Regional Airport",
    "Easterwood Airport",
    "El Paso International Airport",
    "Elko Regional Airport",
    "Elmira/Corning Regional Airport",
    "Eppley Airfield",
    "Erie International Airport",
    "Eugene Airport (Mahlon Sweet Field)",
    "Evansville Regional Airport",
    "Fairbanks International Airport",
    "Falls International Airport",
    "Fayetteville Regional Airport",
    "Flagstaff Pulliam Airport",
    "Ford Airport",
    "Fort Lauderdale-Hollywood International Airport",
    "Fort Smith Regional Airport",
    "Fort Wayne International Airport",
    "Fresno Yosemite International Airport",
    "Friedman Memorial Airport",
    "Gainesville Regional Airport",
    "Garden City Regional Airport",
    "Gen. Edward Lawrence Logan International Airport",
    "General Mitchell International Airport",
    "General Wayne A. Downing Peoria International Airport",
    "George Bush Intercontinental Airport",
    "Gerald R. Ford International Airport",
    "Gillette-Campbell County Airport",
    "Glacier Park International Airport",
    "Golden Triangle Regional Airport",
    "Grand Forks International Airport",
    "Grand Junction Regional Airport (Walker Field)",
    "Great Falls International Airport",
    "Greater Binghamton Airport",
    "Greater Rochester International Airport",
    "Green Bay-Austin Straubel International Airport",
    "Greenville-Spartanburg International Airport",
    "Guam International Airport",
    "Gulfport-Biloxi International Airport",
    "Gunnison-Crested Butte Regional Airport",
    "Gustavus Airport",
    "Harrisburg International Airport",
    "Hartsfield-Jackson Atlanta International Airport",
    "Hattiesburg-Laurel Regional Airport",
    "Hays Regional Airport",
    "Hector International Airport",
    "Helena Regional Airport",
    "Henry E. Rohlsen Airport",
    "Hilo International Airport",
    "Honolulu International Airport",
    "Houghton County Memorial Airport",
    "Huntsville International Airport",
    "Idaho Falls Regional Airport",
    "Indianapolis International Airport",
    "Ithaca Tompkins Regional Airport",
    "Jack Brooks Regional Airport (Southeast Texas Regional)",
    "Jackson Hole Airport",
    "Jackson-Evers International Airport",
    "Jacksonville International Airport",
    "James M. Cox Dayton International Airport",
    "Jamestown Regional Airport",
    "John F. Kennedy International Airport (New York International Airport)",
    "John Wayne Airport (Orange County Airport)",
    "Joplin Regional Airport",
    "Juneau International Airport",
    "Kahului Airport",
    "Kalamazoo/Battle Creek International Airport",
    "Kansas City International Airport",
    "Ketchikan International Airport",
    "Key West International Airport",
    "Killeen-Fort Hood Regional Airport",
    "King Salmon Airport",
    "Kodiak Airport",
    "Kona International Airport at Keahole",
    "La Crosse Regional Airport",
    "LaGuardia Airport (Marine Air Terminal)",
    "Lafayette Regional Airport",
    "Lake Charles Regional Airport",
    "Laramie Regional Airport",
    "Laredo International Airport",
    "Lawton-Fort Sill Regional Airport",
    "Lea County Regional Airport",
    "Lehigh Valley International Airport",
    "Lewiston-Nez Perce County Airport",
    "Lihue Airport",
    "Lincoln Airport (Lincoln Municipal)",
    "Long Beach Airport (Daugherty Field)",
    "Long Island MacArthur Airport",
    "Los Angeles International Airport",
    "Louis Armstrong New Orleans International Airport",
    "Louisville International Airport (Standiford Field)",
    "Lubbock Preston Smith International Airport",
    "Luis Muñoz Marín International Airport",
    "MBS International Airport",
    "Magic Valley Regional Airport (Joslin Field)",
    "Mammoth Yosemite Airport",
    "Manchester-Boston Regional Airport",
    "Manhattan Regional Airport",
    "Martha's Vineyard Airport",
    "McAllen-Miller International Airport (McAllen Miller International)",
    "McCarran International Airport",
    "McClellan-Palomar Airport",
    "McGhee Tyson Airport",
    "Meadows Field",
    "Melbourne International Airport",
    "Memphis International Airport",
    "Mercedita Airport",
    "Meridian Regional Airport",
    "Merle K. (Mudhole) Smith Airport",
    "Miami International Airport",
    "Midland International Airport",
    "Minneapolis-Saint Paul International Airport",
    "Minot International Airport",
    "Missoula International Airport",
    "Mobile Regional Airport",
    "Monroe Regional Airport",
    "Monterey Regional Airport (Monterey Peninsula Airport)",
    "Montgomery Regional Airport",
    "Montrose Regional Airport",
    "Muskegon County Airport",
    "Myrtle Beach International Airport",
    "Nantucket Memorial Airport",
    "Nashville International Airport",
    "Natrona County International Airport",
    "Newark Liberty International Airport",
    "Newport News/Williamsburg International Airport",
    "Niagara Falls International Airport",
    "Nome Airport",
    "Norfolk International Airport",
    "Norman Y. Mineta San José International Airport",
    "Northeast Florida Regional Airport (St. Augustine Airport)",
    "Northwest Arkansas Regional Airport",
    "Northwest Florida Beaches International Airport",
    "Oakland International Airport",
    "Ontario International Airport",
    "Orlando International Airport",
    "Pago Pago International Airport (Tafuna Airport)",
    "Palm Beach International Airport",
    "Palm Springs International Airport",
    "Pellston Regional Airport of Emmet County",
    "Pensacola International Airport (Pensacola Gulf Coast Regional Airport)",
    "Petersburg James A. Johnson Airport",
    "Philadelphia International Airport",
    "Phoenix Sky Harbor International Airport",
    "Piedmont Triad International Airport",
    "Pittsburgh International Airport",
    "Plattsburgh International Airport",
    "Pocatello Regional Airport",
    "Port Columbus International Airport",
    "Portland International Airport",
    "Portland International Jetport",
    "Pueblo Memorial Airport",
    "Quad City International Airport",
    "Rafael Hernández Airport",
    "Raleigh-Durham International Airport",
    "Ralph Wien Memorial Airport",
    "Range Regional Airport (Chisholm-Hibbing Airport)",
    "Rapid City Regional Airport",
    "Redding Municipal Airport",
    "Redmond Municipal Airport (Roberts Field)",
    "Reno/Tahoe International Airport",
    "Rhinelander-Oneida County Airport",
    "Richmond International Airport",
    "Rick Husband Amarillo International Airport",
    "Roanoke Regional Airport (Woodrum Field)",
    "Rochester International Airport",
    "Rock Springs-Sweetwater County Airport",
    "Rogue Valley International Airport",
    "Ronald Reagan Washington National Airport",
    "Roswell International Air Center",
    "Sacramento International Airport",
    "Salt Lake City International Airport",
    "San Angelo Regional Airport (Mathis Field)",
    "San Antonio International Airport",
    "San Diego International Airport (Lindbergh Field)",
    "San Francisco International Airport",
    "San Luis Obispo County Regional Airport (McChesney Field)",
    "Santa Barbara Municipal Airport (Santa Barbara Airport)",
    "Santa Fe Municipal Airport",
    "Santa Maria Public Airport (Capt G. Allan Hancock Field)",
    "Sarasota-Bradenton International Airport",
    "Savannah/Hilton Head International Airport",
    "Sawyer International Airport",
    "Seattle-Tacoma International Airport",
    "Shreveport Regional Airport",
    "Sioux Falls Regional Airport",
    "Sioux Gateway Airport",
    "Sitka Rocky Gutierrez Airport",
    "Sloulin Field International Airport",
    "South Bend International Airport (South Bend Regional)",
    "Southwest Florida International Airport",
    "Southwest Georgia Regional Airport",
    "Southwest Oregon Regional Airport (North Bend Municipal)",
    "Spokane International Airport",
    "Springfield-Branson National Airport",
    "St. Cloud Regional Airport",
    "St. George Regional Airport",
    "St. Louis International Airport at Lambert Field",
    "Stewart International Airport",
    "Syracuse Hancock International Airport",
    "Tallahassee International Airport",
    "Tampa International Airport",
    "Ted Stevens Anchorage International Airport",
    "Texarkana Regional Airport (Webb Field)",
    "The Eastern Iowa Airport",
    "Theodore Francis Green State Airport",
    "Toledo Express Airport",
    "Trenton Mercer Airport",
    "Tri-Cities Airport",
    "Tri-Cities Regional Airport",
    "Tucson International Airport",
    "Tulsa International Airport",
    "Tyler Pounds Regional Airport",
    "University Park Airport",
    "University of Illinois - Willard Airport",
    "Valdez Airport",
    "Valdosta Regional Airport",
    "Valley International Airport",
    "Waco Regional Airport",
    "Washington Dulles International Airport",
    "Waterloo Regional Airport",
    "Westchester County Airport",
    "Westerly State Airport",
    "Wichita Dwight D. Eisenhower National Airport (Wichita Mid-Continent Airport)",
    "Wichita Falls Municipal Airport/Sheppard AFB",
    "Wiley Post-Will Rogers Memorial Airport",
    "Wilkes-Barre/Scranton International Airport",
    "Will Rogers World Airport",
    "William P. Hobby Airport",
    "Wilmington Airport",
    "Wilmington International Airport",
    "Worcester Regional Airport",
    "Wrangell Airport",
    "Yakutat Airport",
    "Yampa Valley Airport (Yampa Valley Regional)",
    "Yeager Airport",
    "Yellowstone Regional Airport",
    "Yuma International Airport",
  ],
  "Origin City": [
    "Aberdeen",
    "Abilene",
    "Adak",
    "Agana",
    "Aguadilla",
    "Akron",
    "Albany",
    "Albuquerque",
    "Alexandria",
    "Allentown",
    "Alpena",
    "Amarillo",
    "Anchorage",
    "Appleton",
    "Arcata/Eureka",
    "Arlington",
    "Asheville",
    "Aspen",
    "Atlanta",
    "Atlantic City",
    "Augusta",
    "Austin",
    "Bakersfield",
    "Baltimore",
    "Bangor",
    "Barrow",
    "Baton Rouge",
    "Beaumont/Port Arthur",
    "Bellingham",
    "Bemidji",
    "Bethel",
    "Billings",
    "Binghamton",
    "Birmingham",
    "Bismarck",
    "Bloomington",
    "Boise",
    "Boston",
    "Bozeman",
    "Brainerd",
    "Bristol",
    "Brownsville",
    "Brunswick",
    "Buffalo",
    "Burbank",
    "Burlington",
    "Butte",
    "Casper",
    "Cedar City",
    "Cedar Rapids",
    "Champaign/Urbana",
    "Chantilly",
    "Charleston",
    "Charlotte",
    "Charlotte Amalie",
    "Charlottesville",
    "Chattanooga",
    "Chicago",
    "Christiansted",
    "Cleveland",
    "Cody",
    "College Station",
    "Colorado Springs",
    "Columbia",
    "Columbus",
    "Columbus-Starkville-West Point",
    "Cordova",
    "Corpus Christi",
    "Covington",
    "Crescent City",
    "Dallas",
    "Dallas-Fort Worth",
    "Dayton",
    "Daytona Beach",
    "Deadhorse",
    "Denver",
    "Des Moines",
    "Detroit",
    "Devils Lake",
    "Dickinson",
    "Dillingham",
    "Dothan",
    "Dubuque",
    "Duluth",
    "Durango",
    "Eagle",
    "Eau Claire",
    "El Paso",
    "Elko",
    "Elmira",
    "Erie",
    "Escanaba",
    "Eugene",
    "Evansville",
    "Fairbanks",
    "Fargo",
    "Fayetteville",
    "Fayetteville/Springdale/Rogers",
    "Flagstaff",
    "Flint",
    "Fort Smith",
    "Fort Wayne",
    "Fresno",
    "Ft. Lauderdale",
    "Ft. Myers",
    "Gainesville",
    "Garden City",
    "Gillette",
    "Grand Forks",
    "Grand Island",
    "Grand Junction",
    "Grand Rapids",
    "Great Falls",
    "Green Bay",
    "Greensboro",
    "Greer",
    "Gulfport-Biloxi",
    "Gunnison",
    "Gustavus",
    "Hailey",
    "Hancock",
    "Harlingen",
    "Harrisburg",
    "Hattiesburg-Laurel",
    "Hayden",
    "Hays",
    "Helena",
    "Hibbing",
    "Hilo",
    "Hobbs",
    "Honolulu",
    "Houston",
    "Huntsville",
    "Hyannis",
    "Idaho Falls",
    "Indianapolis",
    "International Falls",
    "Iron Mountain/Kingsford",
    "Islip",
    "Ithaca",
    "Jackson",
    "Jacksonville",
    "Jamestown",
    "Joplin",
    "Juneau",
    "Kahului",
    "Kailua/Kona",
    "Kalamazoo",
    "Kalispell",
    "Kansas City",
    "Ketchikan",
    "Key West",
    "Killeen",
    "King Salmon",
    "Knoxville",
    "Kodiak",
    "Kotzebue",
    "La Crosse",
    "Lafayette",
    "Lake Charles",
    "Lansing",
    "Laramie",
    "Laredo",
    "Las Vegas",
    "Latrobe",
    "Lawton",
    "Lewiston",
    "Lexington",
    "Lihue",
    "Lincoln",
    "Little Rock",
    "Long Beach",
    "Longview",
    "Los Angeles",
    "Louisville",
    "Lubbock",
    "Madison",
    "Mammoth Lakes",
    "Manchester",
    "Manhattan",
    "Marquette",
    "Marthas Vineyard",
    "McAllen",
    "Medford",
    "Melbourne",
    "Memphis",
    "Meridian",
    "Miami",
    "Midland",
    "Milwaukee",
    "Minneapolis",
    "Minot",
    "Missoula",
    "Moab",
    "Mobile",
    "Moline",
    "Monroe",
    "Monterey",
    "Montgomery",
    "Montrose",
    "Mosinee",
    "Muskegon",
    "Myrtle Beach",
    "Nantucket",
    "Nashville",
    "New Bern",
    "New Orleans",
    "New York",
    "Newark",
    "Newburgh",
    "Newport News",
    "Niagara Falls",
    "Nome",
    "Norfolk",
    "North Bend",
    "Oakland",
    "Oklahoma City",
    "Omaha",
    "Ontario",
    "Orlando",
    "Paducah",
    "Pago Pago",
    "Palm Springs",
    "Panama City",
    "Pasco",
    "Pellston",
    "Pensacola",
    "Peoria",
    "Petersburg",
    "Philadelphia",
    "Phoenix",
    "Pittsburgh",
    "Plattsburgh",
    "Pocatello",
    "Ponce",
    "Portland",
    "Providence",
    "Pueblo",
    "Raleigh",
    "Rapid City",
    "Redding",
    "Redmond",
    "Reno",
    "Rhinelander",
    "Richmond",
    "Roanoke",
    "Rochester",
    "Rock Springs",
    "Roswell",
    "Sacramento",
    "Saginaw",
    "Salt Lake City",
    "San Angelo",
    "San Antonio",
    "San Diego",
    "San Francisco",
    "San Jose",
    "San Juan",
    "San Luis Obispo",
    "Santa Ana",
    "Santa Barbara",
    "Santa Fe",
    "Santa Maria",
    "Sarasota",
    "Sault Ste. Marie",
    "Savannah",
    "Seattle",
    "Shreveport",
    "Sioux City",
    "Sioux Falls",
    "Sitka",
    "South Bend",
    "Spokane",
    "Springfield",
    "St Cloud",
    "St George",
    "St Louis",
    "St. Augustine",
    "State College",
    "Syracuse",
    "Tallahassee",
    "Tampa",
    "Texarkana",
    "Toledo",
    "Traverse City",
    "Trenton",
    "Tucson",
    "Tulsa",
    "Twin Falls",
    "Tyler",
    "Valdosta",
    "Valparaiso",
    "Vernal",
    "Waco",
    "Waterloo",
    "West Palm Beach",
    "West Yellowstone",
    "White Plains",
    "Wichita",
    "Wichita Falls",
    "Wilkes-Barre/Scranton",
    "Williston",
    "Wilmington",
    "Windsor Locks",
    "Worcester",
    "Wrangell",
    "Yakutat",
    "Yuma",
  ],
  "Origin State": [
    "AK",
    "AL",
    "AR",
    "AS",
    "AZ",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "GU",
    "HI",
    "IA",
    "ID",
    "IL",
    "IN",
    "KS",
    "KY",
    "LA",
    "MA",
    "MD",
    "ME",
    "MI",
    "MN",
    "MO",
    "MS",
    "MT",
    "NC",
    "ND",
    "NE",
    "NH",
    "NJ",
    "NM",
    "NV",
    "NY",
    "OH",
    "OK",
    "OR",
    "PA",
    "PR",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VA",
    "VI",
    "VT",
    "WA",
    "WI",
    "WV",
    "WY",
  ],
  "Destination Airport": [
    "Aberdeen Regional Airport",
    "Abilene Regional Airport",
    "Abraham Lincoln Capital Airport",
    "Adak Airport",
    "Akron-Canton Regional Airport",
    "Albany International Airport",
    "Albert J. Ellis Airport",
    "Albuquerque International Sunport",
    "Alexandria International Airport",
    "Alpena County Regional Airport",
    "Appleton International Airport",
    "Arcata Airport",
    "Arnold Palmer Regional Airport",
    "Asheville Regional Airport",
    "Aspen-Pitkin County Airport",
    "Atlantic City International Airport",
    "Augusta Regional Airport (Bush Field)",
    "Austin-Bergstrom International Airport",
    "Baltimore-Washington International Airport",
    "Bangor International Airport",
    "Barkley Regional Airport",
    "Barnstable Municipal Airport",
    "Baton Rouge Metropolitan Airport",
    "Bellingham International Airport",
    "Bemidji Regional Airport",
    "Bert Mooney Airport",
    "Bethel Airport",
    "Bill and Hillary Clinton National Airport (Adams Field)",
    "Billings Logan International Airport",
    "Birmingham-Shuttlesworth International Airport",
    "Bishop International Airport",
    "Bismarck Municipal Airport",
    "Blue Grass Airport",
    "Bob Hope Airport (Hollywood Burbank Airport)",
    "Boise Airport (Boise Air Terminal)",
    "Bozeman Yellowstone International Airport (Gallatin Field Airport)",
    "Bradley International Airport",
    "Brainerd Lakes Regional Airport",
    "Brownsville/South Padre Island International Airport",
    "Brunswick Golden Isles Airport",
    "Buffalo Niagara International Airport",
    "Burlington International Airport",
    "Canyonlands Field",
    "Capital Region International Airport ( Lansing Capital City)",
    "Cedar City Regional Airport",
    "Central Illinois Regional Airport at Bloomington-Normal",
    "Central Nebraska Regional Airport",
    "Central Wisconsin Airport",
    "Charleston International Airport/Charleston AFB",
    "Charlotte Douglas International Airport",
    "Charlottesville-Albemarle Airport",
    "Chattanooga Metropolitan Airport (Lovell Field)",
    "Cherry Capital Airport",
    "Chicago Midway International Airport",
    "Chicago O'Hare International Airport",
    "Chippewa County International Airport",
    "Chippewa Valley Regional Airport",
    "Cincinnati/Northern Kentucky International Airport",
    "City of Colorado Springs Municipal Airport",
    "Cleveland Hopkins International Airport",
    "Coastal Carolina Regional Airport (Craven County Regional)",
    "Columbia Metropolitan Airport",
    "Columbia Regional Airport",
    "Columbus Metropolitan Airport",
    "Corpus Christi International Airport",
    "Cyril E. King Airport",
    "Dallas Love Field",
    "Dallas/Fort Worth International Airport",
    "Dane County Regional Airport",
    "Daytona Beach International Airport",
    "Deadhorse Airport (Prudhoe Bay Airport)",
    "Del Norte County Airport (Jack McNamara Field)",
    "Delta County Airport",
    "Denver International Airport",
    "Des Moines International Airport",
    "Destin-Fort Walton Beach Airport/Eglin AFB",
    "Detroit Metropolitan Airport",
    "Devils Lake Regional Airport",
    "Dickinson Theodore Roosevelt Regional Airport",
    "Dillingham Airport",
    "Dothan Regional Airport",
    "Dubuque Regional Airport",
    "Duluth International Airport",
    "Durango-La Plata County Airport",
    "Eagle County Regional Airport",
    "East Texas Regional Airport",
    "Easterwood Airport",
    "El Paso International Airport",
    "Elko Regional Airport",
    "Elmira/Corning Regional Airport",
    "Eppley Airfield",
    "Erie International Airport",
    "Eugene Airport (Mahlon Sweet Field)",
    "Evansville Regional Airport",
    "Fairbanks International Airport",
    "Falls International Airport",
    "Fayetteville Regional Airport",
    "Flagstaff Pulliam Airport",
    "Ford Airport",
    "Fort Lauderdale-Hollywood International Airport",
    "Fort Smith Regional Airport",
    "Fort Wayne International Airport",
    "Fresno Yosemite International Airport",
    "Friedman Memorial Airport",
    "Gainesville Regional Airport",
    "Garden City Regional Airport",
    "Gen. Edward Lawrence Logan International Airport",
    "General Mitchell International Airport",
    "General Wayne A. Downing Peoria International Airport",
    "George Bush Intercontinental Airport",
    "Gerald R. Ford International Airport",
    "Gillette-Campbell County Airport",
    "Glacier Park International Airport",
    "Golden Triangle Regional Airport",
    "Grand Forks International Airport",
    "Grand Junction Regional Airport (Walker Field)",
    "Great Falls International Airport",
    "Greater Binghamton Airport",
    "Greater Rochester International Airport",
    "Green Bay-Austin Straubel International Airport",
    "Greenville-Spartanburg International Airport",
    "Guam International Airport",
    "Gulfport-Biloxi International Airport",
    "Gunnison-Crested Butte Regional Airport",
    "Gustavus Airport",
    "Harrisburg International Airport",
    "Hartsfield-Jackson Atlanta International Airport",
    "Hattiesburg-Laurel Regional Airport",
    "Hays Regional Airport",
    "Hector International Airport",
    "Helena Regional Airport",
    "Henry E. Rohlsen Airport",
    "Hilo International Airport",
    "Honolulu International Airport",
    "Houghton County Memorial Airport",
    "Huntsville International Airport",
    "Idaho Falls Regional Airport",
    "Indianapolis International Airport",
    "Ithaca Tompkins Regional Airport",
    "Jack Brooks Regional Airport (Southeast Texas Regional)",
    "Jackson Hole Airport",
    "Jackson-Evers International Airport",
    "Jacksonville International Airport",
    "James M. Cox Dayton International Airport",
    "Jamestown Regional Airport",
    "John F. Kennedy International Airport (New York International Airport)",
    "John Wayne Airport (Orange County Airport)",
    "Joplin Regional Airport",
    "Juneau International Airport",
    "Kahului Airport",
    "Kalamazoo/Battle Creek International Airport",
    "Kansas City International Airport",
    "Ketchikan International Airport",
    "Key West International Airport",
    "Killeen-Fort Hood Regional Airport",
    "King Salmon Airport",
    "Kodiak Airport",
    "Kona International Airport at Keahole",
    "La Crosse Regional Airport",
    "LaGuardia Airport (Marine Air Terminal)",
    "Lafayette Regional Airport",
    "Lake Charles Regional Airport",
    "Laramie Regional Airport",
    "Laredo International Airport",
    "Lawton-Fort Sill Regional Airport",
    "Lea County Regional Airport",
    "Lehigh Valley International Airport",
    "Lewiston-Nez Perce County Airport",
    "Lihue Airport",
    "Lincoln Airport (Lincoln Municipal)",
    "Long Beach Airport (Daugherty Field)",
    "Long Island MacArthur Airport",
    "Los Angeles International Airport",
    "Louis Armstrong New Orleans International Airport",
    "Louisville International Airport (Standiford Field)",
    "Lubbock Preston Smith International Airport",
    "Luis Muñoz Marín International Airport",
    "MBS International Airport",
    "Magic Valley Regional Airport (Joslin Field)",
    "Mammoth Yosemite Airport",
    "Manchester-Boston Regional Airport",
    "Manhattan Regional Airport",
    "Martha's Vineyard Airport",
    "McAllen-Miller International Airport (McAllen Miller International)",
    "McCarran International Airport",
    "McClellan-Palomar Airport",
    "McGhee Tyson Airport",
    "Meadows Field",
    "Melbourne International Airport",
    "Memphis International Airport",
    "Mercedita Airport",
    "Meridian Regional Airport",
    "Merle K. (Mudhole) Smith Airport",
    "Miami International Airport",
    "Midland International Airport",
    "Minneapolis-Saint Paul International Airport",
    "Minot International Airport",
    "Missoula International Airport",
    "Mobile Regional Airport",
    "Monroe Regional Airport",
    "Monterey Regional Airport (Monterey Peninsula Airport)",
    "Montgomery Regional Airport",
    "Montrose Regional Airport",
    "Muskegon County Airport",
    "Myrtle Beach International Airport",
    "Nantucket Memorial Airport",
    "Nashville International Airport",
    "Natrona County International Airport",
    "Newark Liberty International Airport",
    "Newport News/Williamsburg International Airport",
    "Niagara Falls International Airport",
    "Nome Airport",
    "Norfolk International Airport",
    "Norman Y. Mineta San José International Airport",
    "Northeast Florida Regional Airport (St. Augustine Airport)",
    "Northwest Arkansas Regional Airport",
    "Northwest Florida Beaches International Airport",
    "Oakland International Airport",
    "Ontario International Airport",
    "Orlando International Airport",
    "Pago Pago International Airport (Tafuna Airport)",
    "Palm Beach International Airport",
    "Palm Springs International Airport",
    "Pellston Regional Airport of Emmet County",
    "Pensacola International Airport (Pensacola Gulf Coast Regional Airport)",
    "Petersburg James A. Johnson Airport",
    "Philadelphia International Airport",
    "Phoenix Sky Harbor International Airport",
    "Piedmont Triad International Airport",
    "Pittsburgh International Airport",
    "Plattsburgh International Airport",
    "Pocatello Regional Airport",
    "Port Columbus International Airport",
    "Portland International Airport",
    "Portland International Jetport",
    "Pueblo Memorial Airport",
    "Quad City International Airport",
    "Rafael Hernández Airport",
    "Raleigh-Durham International Airport",
    "Ralph Wien Memorial Airport",
    "Range Regional Airport (Chisholm-Hibbing Airport)",
    "Rapid City Regional Airport",
    "Redding Municipal Airport",
    "Redmond Municipal Airport (Roberts Field)",
    "Reno/Tahoe International Airport",
    "Rhinelander-Oneida County Airport",
    "Richmond International Airport",
    "Rick Husband Amarillo International Airport",
    "Roanoke Regional Airport (Woodrum Field)",
    "Rochester International Airport",
    "Rock Springs-Sweetwater County Airport",
    "Rogue Valley International Airport",
    "Ronald Reagan Washington National Airport",
    "Roswell International Air Center",
    "Sacramento International Airport",
    "Salt Lake City International Airport",
    "San Angelo Regional Airport (Mathis Field)",
    "San Antonio International Airport",
    "San Diego International Airport (Lindbergh Field)",
    "San Francisco International Airport",
    "San Luis Obispo County Regional Airport (McChesney Field)",
    "Santa Barbara Municipal Airport (Santa Barbara Airport)",
    "Santa Fe Municipal Airport",
    "Santa Maria Public Airport (Capt G. Allan Hancock Field)",
    "Sarasota-Bradenton International Airport",
    "Savannah/Hilton Head International Airport",
    "Sawyer International Airport",
    "Seattle-Tacoma International Airport",
    "Shreveport Regional Airport",
    "Sioux Falls Regional Airport",
    "Sioux Gateway Airport",
    "Sitka Rocky Gutierrez Airport",
    "Sloulin Field International Airport",
    "South Bend International Airport (South Bend Regional)",
    "Southwest Florida International Airport",
    "Southwest Georgia Regional Airport",
    "Southwest Oregon Regional Airport (North Bend Municipal)",
    "Spokane International Airport",
    "Springfield-Branson National Airport",
    "St. Cloud Regional Airport",
    "St. George Regional Airport",
    "St. Louis International Airport at Lambert Field",
    "Stewart International Airport",
    "Syracuse Hancock International Airport",
    "Tallahassee International Airport",
    "Tampa International Airport",
    "Ted Stevens Anchorage International Airport",
    "Texarkana Regional Airport (Webb Field)",
    "The Eastern Iowa Airport",
    "Theodore Francis Green State Airport",
    "Toledo Express Airport",
    "Trenton Mercer Airport",
    "Tri-Cities Airport",
    "Tri-Cities Regional Airport",
    "Tucson International Airport",
    "Tulsa International Airport",
    "Tyler Pounds Regional Airport",
    "University Park Airport",
    "University of Illinois - Willard Airport",
    "Valdez Airport",
    "Valdosta Regional Airport",
    "Valley International Airport",
    "Waco Regional Airport",
    "Washington Dulles International Airport",
    "Waterloo Regional Airport",
    "Westchester County Airport",
    "Westerly State Airport",
    "Wichita Dwight D. Eisenhower National Airport (Wichita Mid-Continent Airport)",
    "Wichita Falls Municipal Airport/Sheppard AFB",
    "Wiley Post-Will Rogers Memorial Airport",
    "Wilkes-Barre/Scranton International Airport",
    "Will Rogers World Airport",
    "William P. Hobby Airport",
    "Wilmington Airport",
    "Wilmington International Airport",
    "Worcester Regional Airport",
    "Wrangell Airport",
    "Yakutat Airport",
    "Yampa Valley Airport (Yampa Valley Regional)",
    "Yeager Airport",
    "Yellowstone Regional Airport",
    "Yuma International Airport",
  ],
  "Day of Week": [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ],
  "Destination City": [
    "Aberdeen",
    "Abilene",
    "Adak",
    "Agana",
    "Aguadilla",
    "Akron",
    "Albany",
    "Albuquerque",
    "Alexandria",
    "Allentown",
    "Alpena",
    "Amarillo",
    "Anchorage",
    "Appleton",
    "Arcata/Eureka",
    "Arlington",
    "Asheville",
    "Aspen",
    "Atlanta",
    "Atlantic City",
    "Augusta",
    "Austin",
    "Bakersfield",
    "Baltimore",
    "Bangor",
    "Barrow",
    "Baton Rouge",
    "Beaumont/Port Arthur",
    "Bellingham",
    "Bemidji",
    "Bethel",
    "Billings",
    "Binghamton",
    "Birmingham",
    "Bismarck",
    "Bloomington",
    "Boise",
    "Boston",
    "Bozeman",
    "Brainerd",
    "Bristol",
    "Brownsville",
    "Brunswick",
    "Buffalo",
    "Burbank",
    "Burlington",
    "Butte",
    "Casper",
    "Cedar City",
    "Cedar Rapids",
    "Champaign/Urbana",
    "Chantilly",
    "Charleston",
    "Charlotte",
    "Charlotte Amalie",
    "Charlottesville",
    "Chattanooga",
    "Chicago",
    "Christiansted",
    "Cleveland",
    "Cody",
    "College Station",
    "Colorado Springs",
    "Columbia",
    "Columbus",
    "Columbus-Starkville-West Point",
    "Cordova",
    "Corpus Christi",
    "Covington",
    "Crescent City",
    "Dallas",
    "Dallas-Fort Worth",
    "Dayton",
    "Daytona Beach",
    "Deadhorse",
    "Denver",
    "Des Moines",
    "Detroit",
    "Devils Lake",
    "Dickinson",
    "Dillingham",
    "Dothan",
    "Dubuque",
    "Duluth",
    "Durango",
    "Eagle",
    "Eau Claire",
    "El Paso",
    "Elko",
    "Elmira",
    "Erie",
    "Escanaba",
    "Eugene",
    "Evansville",
    "Fairbanks",
    "Fargo",
    "Fayetteville",
    "Fayetteville/Springdale/Rogers",
    "Flagstaff",
    "Flint",
    "Fort Smith",
    "Fort Wayne",
    "Fresno",
    "Ft. Lauderdale",
    "Ft. Myers",
    "Gainesville",
    "Garden City",
    "Gillette",
    "Grand Forks",
    "Grand Island",
    "Grand Junction",
    "Grand Rapids",
    "Great Falls",
    "Green Bay",
    "Greensboro",
    "Greer",
    "Gulfport-Biloxi",
    "Gunnison",
    "Gustavus",
    "Hailey",
    "Hancock",
    "Harlingen",
    "Harrisburg",
    "Hattiesburg-Laurel",
    "Hayden",
    "Hays",
    "Helena",
    "Hibbing",
    "Hilo",
    "Hobbs",
    "Honolulu",
    "Houston",
    "Huntsville",
    "Hyannis",
    "Idaho Falls",
    "Indianapolis",
    "International Falls",
    "Iron Mountain/Kingsford",
    "Islip",
    "Ithaca",
    "Jackson",
    "Jacksonville",
    "Jamestown",
    "Joplin",
    "Juneau",
    "Kahului",
    "Kailua/Kona",
    "Kalamazoo",
    "Kalispell",
    "Kansas City",
    "Ketchikan",
    "Key West",
    "Killeen",
    "King Salmon",
    "Knoxville",
    "Kodiak",
    "Kotzebue",
    "La Crosse",
    "Lafayette",
    "Lake Charles",
    "Lansing",
    "Laramie",
    "Laredo",
    "Las Vegas",
    "Latrobe",
    "Lawton",
    "Lewiston",
    "Lexington",
    "Lihue",
    "Lincoln",
    "Little Rock",
    "Long Beach",
    "Longview",
    "Los Angeles",
    "Louisville",
    "Lubbock",
    "Madison",
    "Mammoth Lakes",
    "Manchester",
    "Manhattan",
    "Marquette",
    "Marthas Vineyard",
    "McAllen",
    "Medford",
    "Melbourne",
    "Memphis",
    "Meridian",
    "Miami",
    "Midland",
    "Milwaukee",
    "Minneapolis",
    "Minot",
    "Missoula",
    "Moab",
    "Mobile",
    "Moline",
    "Monroe",
    "Monterey",
    "Montgomery",
    "Montrose",
    "Mosinee",
    "Muskegon",
    "Myrtle Beach",
    "Nantucket",
    "Nashville",
    "New Bern",
    "New Orleans",
    "New York",
    "Newark",
    "Newburgh",
    "Newport News",
    "Niagara Falls",
    "Nome",
    "Norfolk",
    "North Bend",
    "Oakland",
    "Oklahoma City",
    "Omaha",
    "Ontario",
    "Orlando",
    "Paducah",
    "Pago Pago",
    "Palm Springs",
    "Panama City",
    "Pasco",
    "Pellston",
    "Pensacola",
    "Peoria",
    "Petersburg",
    "Philadelphia",
    "Phoenix",
    "Pittsburgh",
    "Plattsburgh",
    "Pocatello",
    "Ponce",
    "Portland",
    "Providence",
    "Pueblo",
    "Raleigh",
    "Rapid City",
    "Redding",
    "Redmond",
    "Reno",
    "Rhinelander",
    "Richmond",
    "Roanoke",
    "Rochester",
    "Rock Springs",
    "Roswell",
    "Sacramento",
    "Saginaw",
    "Salt Lake City",
    "San Angelo",
    "San Antonio",
    "San Diego",
    "San Francisco",
    "San Jose",
    "San Juan",
    "San Luis Obispo",
    "Santa Ana",
    "Santa Barbara",
    "Santa Fe",
    "Santa Maria",
    "Sarasota",
    "Sault Ste. Marie",
    "Savannah",
    "Seattle",
    "Shreveport",
    "Sioux City",
    "Sioux Falls",
    "Sitka",
    "South Bend",
    "Spokane",
    "Springfield",
    "St Cloud",
    "St George",
    "St Louis",
    "St. Augustine",
    "State College",
    "Syracuse",
    "Tallahassee",
    "Tampa",
    "Texarkana",
    "Toledo",
    "Traverse City",
    "Trenton",
    "Tucson",
    "Tulsa",
    "Twin Falls",
    "Tyler",
    "Valdosta",
    "Valparaiso",
    "Vernal",
    "Waco",
    "Waterloo",
    "West Palm Beach",
    "West Yellowstone",
    "White Plains",
    "Wichita",
    "Wichita Falls",
    "Wilkes-Barre/Scranton",
    "Williston",
    "Wilmington",
    "Windsor Locks",
    "Worcester",
    "Wrangell",
    "Yakutat",
    "Yuma",
  ],
  "Destination State": [
    "AK",
    "AL",
    "AR",
    "AS",
    "AZ",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "GU",
    "HI",
    "IA",
    "ID",
    "IL",
    "IN",
    "KS",
    "KY",
    "LA",
    "MA",
    "MD",
    "ME",
    "MI",
    "MN",
    "MO",
    "MS",
    "MT",
    "NC",
    "ND",
    "NE",
    "NH",
    "NJ",
    "NM",
    "NV",
    "NY",
    "OH",
    "OK",
    "OR",
    "PA",
    "PR",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VA",
    "VI",
    "VT",
    "WA",
    "WI",
    "WV",
    "WY",
  ],
};
