export const FlightsValuesDict = {
  Month: {
    January: "1",
    February: "2",
    March: "3",
    April: "4",
    May: "5",
    June: "6",
    July: "7",
    August: "8",
    September: "9",
    October: "10",
    November: "11",
    December: "12",
  },
  "Day of Month": {
    "1-10": "1-10",
    "11-20": "11-20",
    "21-31": "21-31",
  },

  Airline: {
    "American Airlines Inc.": "AA",
    "Alaska Airlines Inc.": "AS",
    "JetBlue Airways": "B6",
    "Delta Air Lines Inc.": "DL",
    "Atlantic Southeast Airlines": "EV",
    "Frontier Airlines Inc.": "F9",
    "Hawaiian Airlines Inc.": "HA",
    "American Eagle Airlines Inc.": "MQ",
    "Spirit Air Lines": "NK",
    "Skywest Airlines Inc.": "OO",
    "United Air Lines Inc.": "UA",
    "US Airways Inc.": "US",
    "Virgin America": "VX",
    "Southwest Airlines Co.": "WN",
  },

  "Scheduled Departure Hour": {
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    "11": "11",
    "12": "12",
    "13": "13",
    "14": "14",
    "15": "15",
    "16": "16",
    "17": "17",
    "18": "18",
    "19": "19",
    "20": "20",
    "21": "21",
    "22": "22",
    "23": "23",
  },
  "Departure Hour": {
    "0.0": "0.0",
    "1.0": "1.0",
    "2.0": "2.0",
    "3.0": "3.0",
    "4.0": "4.0",
    "5.0": "5.0",
    "6.0": "6.0",
    "7.0": "7.0",
    "8.0": "8.0",
    "9.0": "9.0",
    "10.0": "10.0",
    "11.0": "11.0",
    "12.0": "12.0",
    "13.0": "13.0",
    "14.0": "14.0",
    "15.0": "15.0",
    "16.0": "16.0",
    "17.0": "17.0",
    "18.0": "18.0",
    "19.0": "19.0",
    "20.0": "20.0",
    "21.0": "21.0",
    "22.0": "22.0",
    "23.0": "23.0",
    "24.0": "24.0",
  },
  Distance: {
    "1000-1500": "1000-1500",
    "1500-2000": "1500-2000",
    "500-1000": "500-1000",
    "<500": "<500",
    ">2000": ">2000",
  },
  Diverted: {
    No: "0",
    Yes: "1",
  },
  "Origin Airport": {
    "Aberdeen Regional Airport": "Aberdeen Regional Airport",
    "Abilene Regional Airport": "Abilene Regional Airport",
    "Abraham Lincoln Capital Airport": "Abraham Lincoln Capital Airport",
    "Adak Airport": "Adak Airport",
    "Akron-Canton Regional Airport": "Akron-Canton Regional Airport",
    "Albany International Airport": "Albany International Airport",
    "Albert J. Ellis Airport": "Albert J. Ellis Airport",
    "Albuquerque International Sunport": "Albuquerque International Sunport",
    "Alexandria International Airport": "Alexandria International Airport",
    "Alpena County Regional Airport": "Alpena County Regional Airport",
    "Appleton International Airport": "Appleton International Airport",
    "Arcata Airport": "Arcata Airport",
    "Arnold Palmer Regional Airport": "Arnold Palmer Regional Airport",
    "Asheville Regional Airport": "Asheville Regional Airport",
    "Aspen-Pitkin County Airport": "Aspen-Pitkin County Airport",
    "Atlantic City International Airport":
      "Atlantic City International Airport",
    "Augusta Regional Airport (Bush Field)":
      "Augusta Regional Airport (Bush Field)",
    "Austin-Bergstrom International Airport":
      "Austin-Bergstrom International Airport",
    "Baltimore-Washington International Airport":
      "Baltimore-Washington International Airport",
    "Bangor International Airport": "Bangor International Airport",
    "Barkley Regional Airport": "Barkley Regional Airport",
    "Barnstable Municipal Airport": "Barnstable Municipal Airport",
    "Baton Rouge Metropolitan Airport": "Baton Rouge Metropolitan Airport",
    "Bellingham International Airport": "Bellingham International Airport",
    "Bemidji Regional Airport": "Bemidji Regional Airport",
    "Bert Mooney Airport": "Bert Mooney Airport",
    "Bethel Airport": "Bethel Airport",
    "Bill and Hillary Clinton National Airport (Adams Field)":
      "Bill and Hillary Clinton National Airport (Adams Field)",
    "Billings Logan International Airport":
      "Billings Logan International Airport",
    "Birmingham-Shuttlesworth International Airport":
      "Birmingham-Shuttlesworth International Airport",
    "Bishop International Airport": "Bishop International Airport",
    "Bismarck Municipal Airport": "Bismarck Municipal Airport",
    "Blue Grass Airport": "Blue Grass Airport",
    "Bob Hope Airport (Hollywood Burbank Airport)":
      "Bob Hope Airport (Hollywood Burbank Airport)",
    "Boise Airport (Boise Air Terminal)": "Boise Airport (Boise Air Terminal)",
    "Bozeman Yellowstone International Airport (Gallatin Field Airport)":
      "Bozeman Yellowstone International Airport (Gallatin Field Airport)",
    "Bradley International Airport": "Bradley International Airport",
    "Brainerd Lakes Regional Airport": "Brainerd Lakes Regional Airport",
    "Brownsville/South Padre Island International Airport":
      "Brownsville/South Padre Island International Airport",
    "Brunswick Golden Isles Airport": "Brunswick Golden Isles Airport",
    "Buffalo Niagara International Airport":
      "Buffalo Niagara International Airport",
    "Burlington International Airport": "Burlington International Airport",
    "Canyonlands Field": "Canyonlands Field",
    "Capital Region International Airport ( Lansing Capital City)":
      "Capital Region International Airport ( Lansing Capital City)",
    "Cedar City Regional Airport": "Cedar City Regional Airport",
    "Central Illinois Regional Airport at Bloomington-Normal":
      "Central Illinois Regional Airport at Bloomington-Normal",
    "Central Nebraska Regional Airport": "Central Nebraska Regional Airport",
    "Central Wisconsin Airport": "Central Wisconsin Airport",
    "Charleston International Airport/Charleston AFB":
      "Charleston International Airport/Charleston AFB",
    "Charlotte Douglas International Airport":
      "Charlotte Douglas International Airport",
    "Charlottesville-Albemarle Airport": "Charlottesville-Albemarle Airport",
    "Chattanooga Metropolitan Airport (Lovell Field)":
      "Chattanooga Metropolitan Airport (Lovell Field)",
    "Cherry Capital Airport": "Cherry Capital Airport",
    "Chicago Midway International Airport":
      "Chicago Midway International Airport",
    "Chicago O'Hare International Airport":
      "Chicago O'Hare International Airport",
    "Chippewa County International Airport":
      "Chippewa County International Airport",
    "Chippewa Valley Regional Airport": "Chippewa Valley Regional Airport",
    "Cincinnati/Northern Kentucky International Airport":
      "Cincinnati/Northern Kentucky International Airport",
    "City of Colorado Springs Municipal Airport":
      "City of Colorado Springs Municipal Airport",
    "Cleveland Hopkins International Airport":
      "Cleveland Hopkins International Airport",
    "Coastal Carolina Regional Airport (Craven County Regional)":
      "Coastal Carolina Regional Airport (Craven County Regional)",
    "Columbia Metropolitan Airport": "Columbia Metropolitan Airport",
    "Columbia Regional Airport": "Columbia Regional Airport",
    "Columbus Metropolitan Airport": "Columbus Metropolitan Airport",
    "Corpus Christi International Airport":
      "Corpus Christi International Airport",
    "Cyril E. King Airport": "Cyril E. King Airport",
    "Dallas Love Field": "Dallas Love Field",
    "Dallas/Fort Worth International Airport":
      "Dallas/Fort Worth International Airport",
    "Dane County Regional Airport": "Dane County Regional Airport",
    "Daytona Beach International Airport":
      "Daytona Beach International Airport",
    "Deadhorse Airport (Prudhoe Bay Airport)":
      "Deadhorse Airport (Prudhoe Bay Airport)",
    "Del Norte County Airport (Jack McNamara Field)":
      "Del Norte County Airport (Jack McNamara Field)",
    "Delta County Airport": "Delta County Airport",
    "Denver International Airport": "Denver International Airport",
    "Des Moines International Airport": "Des Moines International Airport",
    "Destin-Fort Walton Beach Airport/Eglin AFB":
      "Destin-Fort Walton Beach Airport/Eglin AFB",
    "Detroit Metropolitan Airport": "Detroit Metropolitan Airport",
    "Devils Lake Regional Airport": "Devils Lake Regional Airport",
    "Dickinson Theodore Roosevelt Regional Airport":
      "Dickinson Theodore Roosevelt Regional Airport",
    "Dillingham Airport": "Dillingham Airport",
    "Dothan Regional Airport": "Dothan Regional Airport",
    "Dubuque Regional Airport": "Dubuque Regional Airport",
    "Duluth International Airport": "Duluth International Airport",
    "Durango-La Plata County Airport": "Durango-La Plata County Airport",
    "Eagle County Regional Airport": "Eagle County Regional Airport",
    "East Texas Regional Airport": "East Texas Regional Airport",
    "Easterwood Airport": "Easterwood Airport",
    "El Paso International Airport": "El Paso International Airport",
    "Elko Regional Airport": "Elko Regional Airport",
    "Elmira/Corning Regional Airport": "Elmira/Corning Regional Airport",
    "Eppley Airfield": "Eppley Airfield",
    "Erie International Airport": "Erie International Airport",
    "Eugene Airport (Mahlon Sweet Field)":
      "Eugene Airport (Mahlon Sweet Field)",
    "Evansville Regional Airport": "Evansville Regional Airport",
    "Fairbanks International Airport": "Fairbanks International Airport",
    "Falls International Airport": "Falls International Airport",
    "Fayetteville Regional Airport": "Fayetteville Regional Airport",
    "Flagstaff Pulliam Airport": "Flagstaff Pulliam Airport",
    "Ford Airport": "Ford Airport",
    "Fort Lauderdale-Hollywood International Airport":
      "Fort Lauderdale-Hollywood International Airport",
    "Fort Smith Regional Airport": "Fort Smith Regional Airport",
    "Fort Wayne International Airport": "Fort Wayne International Airport",
    "Fresno Yosemite International Airport":
      "Fresno Yosemite International Airport",
    "Friedman Memorial Airport": "Friedman Memorial Airport",
    "Gainesville Regional Airport": "Gainesville Regional Airport",
    "Garden City Regional Airport": "Garden City Regional Airport",
    "Gen. Edward Lawrence Logan International Airport":
      "Gen. Edward Lawrence Logan International Airport",
    "General Mitchell International Airport":
      "General Mitchell International Airport",
    "General Wayne A. Downing Peoria International Airport":
      "General Wayne A. Downing Peoria International Airport",
    "George Bush Intercontinental Airport":
      "George Bush Intercontinental Airport",
    "Gerald R. Ford International Airport":
      "Gerald R. Ford International Airport",
    "Gillette-Campbell County Airport": "Gillette-Campbell County Airport",
    "Glacier Park International Airport": "Glacier Park International Airport",
    "Golden Triangle Regional Airport": "Golden Triangle Regional Airport",
    "Grand Forks International Airport": "Grand Forks International Airport",
    "Grand Junction Regional Airport (Walker Field)":
      "Grand Junction Regional Airport (Walker Field)",
    "Great Falls International Airport": "Great Falls International Airport",
    "Greater Binghamton Airport": "Greater Binghamton Airport",
    "Greater Rochester International Airport":
      "Greater Rochester International Airport",
    "Green Bay-Austin Straubel International Airport":
      "Green Bay-Austin Straubel International Airport",
    "Greenville-Spartanburg International Airport":
      "Greenville-Spartanburg International Airport",
    "Guam International Airport": "Guam International Airport",
    "Gulfport-Biloxi International Airport":
      "Gulfport-Biloxi International Airport",
    "Gunnison-Crested Butte Regional Airport":
      "Gunnison-Crested Butte Regional Airport",
    "Gustavus Airport": "Gustavus Airport",
    "Harrisburg International Airport": "Harrisburg International Airport",
    "Hartsfield-Jackson Atlanta International Airport":
      "Hartsfield-Jackson Atlanta International Airport",
    "Hattiesburg-Laurel Regional Airport":
      "Hattiesburg-Laurel Regional Airport",
    "Hays Regional Airport": "Hays Regional Airport",
    "Hector International Airport": "Hector International Airport",
    "Helena Regional Airport": "Helena Regional Airport",
    "Henry E. Rohlsen Airport": "Henry E. Rohlsen Airport",
    "Hilo International Airport": "Hilo International Airport",
    "Honolulu International Airport": "Honolulu International Airport",
    "Houghton County Memorial Airport": "Houghton County Memorial Airport",
    "Huntsville International Airport": "Huntsville International Airport",
    "Idaho Falls Regional Airport": "Idaho Falls Regional Airport",
    "Indianapolis International Airport": "Indianapolis International Airport",
    "Ithaca Tompkins Regional Airport": "Ithaca Tompkins Regional Airport",
    "Jack Brooks Regional Airport (Southeast Texas Regional)":
      "Jack Brooks Regional Airport (Southeast Texas Regional)",
    "Jackson Hole Airport": "Jackson Hole Airport",
    "Jackson-Evers International Airport":
      "Jackson-Evers International Airport",
    "Jacksonville International Airport": "Jacksonville International Airport",
    "James M. Cox Dayton International Airport":
      "James M. Cox Dayton International Airport",
    "Jamestown Regional Airport": "Jamestown Regional Airport",
    "John F. Kennedy International Airport (New York International Airport)":
      "John F. Kennedy International Airport (New York International Airport)",
    "John Wayne Airport (Orange County Airport)":
      "John Wayne Airport (Orange County Airport)",
    "Joplin Regional Airport": "Joplin Regional Airport",
    "Juneau International Airport": "Juneau International Airport",
    "Kahului Airport": "Kahului Airport",
    "Kalamazoo/Battle Creek International Airport":
      "Kalamazoo/Battle Creek International Airport",
    "Kansas City International Airport": "Kansas City International Airport",
    "Ketchikan International Airport": "Ketchikan International Airport",
    "Key West International Airport": "Key West International Airport",
    "Killeen-Fort Hood Regional Airport": "Killeen-Fort Hood Regional Airport",
    "King Salmon Airport": "King Salmon Airport",
    "Kodiak Airport": "Kodiak Airport",
    "Kona International Airport at Keahole":
      "Kona International Airport at Keahole",
    "La Crosse Regional Airport": "La Crosse Regional Airport",
    "LaGuardia Airport (Marine Air Terminal)":
      "LaGuardia Airport (Marine Air Terminal)",
    "Lafayette Regional Airport": "Lafayette Regional Airport",
    "Lake Charles Regional Airport": "Lake Charles Regional Airport",
    "Laramie Regional Airport": "Laramie Regional Airport",
    "Laredo International Airport": "Laredo International Airport",
    "Lawton-Fort Sill Regional Airport": "Lawton-Fort Sill Regional Airport",
    "Lea County Regional Airport": "Lea County Regional Airport",
    "Lehigh Valley International Airport":
      "Lehigh Valley International Airport",
    "Lewiston-Nez Perce County Airport": "Lewiston-Nez Perce County Airport",
    "Lihue Airport": "Lihue Airport",
    "Lincoln Airport (Lincoln Municipal)":
      "Lincoln Airport (Lincoln Municipal)",
    "Long Beach Airport (Daugherty Field)":
      "Long Beach Airport (Daugherty Field)",
    "Long Island MacArthur Airport": "Long Island MacArthur Airport",
    "Los Angeles International Airport": "Los Angeles International Airport",
    "Louis Armstrong New Orleans International Airport":
      "Louis Armstrong New Orleans International Airport",
    "Louisville International Airport (Standiford Field)":
      "Louisville International Airport (Standiford Field)",
    "Lubbock Preston Smith International Airport":
      "Lubbock Preston Smith International Airport",
    "Luis Muñoz Marín International Airport":
      "Luis Muñoz Marín International Airport",
    "MBS International Airport": "MBS International Airport",
    "Magic Valley Regional Airport (Joslin Field)":
      "Magic Valley Regional Airport (Joslin Field)",
    "Mammoth Yosemite Airport": "Mammoth Yosemite Airport",
    "Manchester-Boston Regional Airport": "Manchester-Boston Regional Airport",
    "Manhattan Regional Airport": "Manhattan Regional Airport",
    "Martha's Vineyard Airport": "Martha's Vineyard Airport",
    "McAllen-Miller International Airport (McAllen Miller International)":
      "McAllen-Miller International Airport (McAllen Miller International)",
    "McCarran International Airport": "McCarran International Airport",
    "McClellan-Palomar Airport": "McClellan-Palomar Airport",
    "McGhee Tyson Airport": "McGhee Tyson Airport",
    "Meadows Field": "Meadows Field",
    "Melbourne International Airport": "Melbourne International Airport",
    "Memphis International Airport": "Memphis International Airport",
    "Mercedita Airport": "Mercedita Airport",
    "Meridian Regional Airport": "Meridian Regional Airport",
    "Merle K. (Mudhole) Smith Airport": "Merle K. (Mudhole) Smith Airport",
    "Miami International Airport": "Miami International Airport",
    "Midland International Airport": "Midland International Airport",
    "Minneapolis-Saint Paul International Airport":
      "Minneapolis-Saint Paul International Airport",
    "Minot International Airport": "Minot International Airport",
    "Missoula International Airport": "Missoula International Airport",
    "Mobile Regional Airport": "Mobile Regional Airport",
    "Monroe Regional Airport": "Monroe Regional Airport",
    "Monterey Regional Airport (Monterey Peninsula Airport)":
      "Monterey Regional Airport (Monterey Peninsula Airport)",
    "Montgomery Regional Airport": "Montgomery Regional Airport",
    "Montrose Regional Airport": "Montrose Regional Airport",
    "Muskegon County Airport": "Muskegon County Airport",
    "Myrtle Beach International Airport": "Myrtle Beach International Airport",
    "Nantucket Memorial Airport": "Nantucket Memorial Airport",
    "Nashville International Airport": "Nashville International Airport",
    "Natrona County International Airport":
      "Natrona County International Airport",
    "Newark Liberty International Airport":
      "Newark Liberty International Airport",
    "Newport News/Williamsburg International Airport":
      "Newport News/Williamsburg International Airport",
    "Niagara Falls International Airport":
      "Niagara Falls International Airport",
    "Nome Airport": "Nome Airport",
    "Norfolk International Airport": "Norfolk International Airport",
    "Norman Y. Mineta San José International Airport":
      "Norman Y. Mineta San José International Airport",
    "Northeast Florida Regional Airport (St. Augustine Airport)":
      "Northeast Florida Regional Airport (St. Augustine Airport)",
    "Northwest Arkansas Regional Airport":
      "Northwest Arkansas Regional Airport",
    "Northwest Florida Beaches International Airport":
      "Northwest Florida Beaches International Airport",
    "Oakland International Airport": "Oakland International Airport",
    "Ontario International Airport": "Ontario International Airport",
    "Orlando International Airport": "Orlando International Airport",
    "Pago Pago International Airport (Tafuna Airport)":
      "Pago Pago International Airport (Tafuna Airport)",
    "Palm Beach International Airport": "Palm Beach International Airport",
    "Palm Springs International Airport": "Palm Springs International Airport",
    "Pellston Regional Airport of Emmet County":
      "Pellston Regional Airport of Emmet County",
    "Pensacola International Airport (Pensacola Gulf Coast Regional Airport)":
      "Pensacola International Airport (Pensacola Gulf Coast Regional Airport)",
    "Petersburg James A. Johnson Airport":
      "Petersburg James A. Johnson Airport",
    "Philadelphia International Airport": "Philadelphia International Airport",
    "Phoenix Sky Harbor International Airport":
      "Phoenix Sky Harbor International Airport",
    "Piedmont Triad International Airport":
      "Piedmont Triad International Airport",
    "Pittsburgh International Airport": "Pittsburgh International Airport",
    "Plattsburgh International Airport": "Plattsburgh International Airport",
    "Pocatello Regional Airport": "Pocatello Regional Airport",
    "Port Columbus International Airport":
      "Port Columbus International Airport",
    "Portland International Airport": "Portland International Airport",
    "Portland International Jetport": "Portland International Jetport",
    "Pueblo Memorial Airport": "Pueblo Memorial Airport",
    "Quad City International Airport": "Quad City International Airport",
    "Rafael Hernández Airport": "Rafael Hernández Airport",
    "Raleigh-Durham International Airport":
      "Raleigh-Durham International Airport",
    "Ralph Wien Memorial Airport": "Ralph Wien Memorial Airport",
    "Range Regional Airport (Chisholm-Hibbing Airport)":
      "Range Regional Airport (Chisholm-Hibbing Airport)",
    "Rapid City Regional Airport": "Rapid City Regional Airport",
    "Redding Municipal Airport": "Redding Municipal Airport",
    "Redmond Municipal Airport (Roberts Field)":
      "Redmond Municipal Airport (Roberts Field)",
    "Reno/Tahoe International Airport": "Reno/Tahoe International Airport",
    "Rhinelander-Oneida County Airport": "Rhinelander-Oneida County Airport",
    "Richmond International Airport": "Richmond International Airport",
    "Rick Husband Amarillo International Airport":
      "Rick Husband Amarillo International Airport",
    "Roanoke Regional Airport (Woodrum Field)":
      "Roanoke Regional Airport (Woodrum Field)",
    "Rochester International Airport": "Rochester International Airport",
    "Rock Springs-Sweetwater County Airport":
      "Rock Springs-Sweetwater County Airport",
    "Rogue Valley International Airport": "Rogue Valley International Airport",
    "Ronald Reagan Washington National Airport":
      "Ronald Reagan Washington National Airport",
    "Roswell International Air Center": "Roswell International Air Center",
    "Sacramento International Airport": "Sacramento International Airport",
    "Salt Lake City International Airport":
      "Salt Lake City International Airport",
    "San Angelo Regional Airport (Mathis Field)":
      "San Angelo Regional Airport (Mathis Field)",
    "San Antonio International Airport": "San Antonio International Airport",
    "San Diego International Airport (Lindbergh Field)":
      "San Diego International Airport (Lindbergh Field)",
    "San Francisco International Airport":
      "San Francisco International Airport",
    "San Luis Obispo County Regional Airport (McChesney Field)":
      "San Luis Obispo County Regional Airport (McChesney Field)",
    "Santa Barbara Municipal Airport (Santa Barbara Airport)":
      "Santa Barbara Municipal Airport (Santa Barbara Airport)",
    "Santa Fe Municipal Airport": "Santa Fe Municipal Airport",
    "Santa Maria Public Airport (Capt G. Allan Hancock Field)":
      "Santa Maria Public Airport (Capt G. Allan Hancock Field)",
    "Sarasota-Bradenton International Airport":
      "Sarasota-Bradenton International Airport",
    "Savannah/Hilton Head International Airport":
      "Savannah/Hilton Head International Airport",
    "Sawyer International Airport": "Sawyer International Airport",
    "Seattle-Tacoma International Airport":
      "Seattle-Tacoma International Airport",
    "Shreveport Regional Airport": "Shreveport Regional Airport",
    "Sioux Falls Regional Airport": "Sioux Falls Regional Airport",
    "Sioux Gateway Airport": "Sioux Gateway Airport",
    "Sitka Rocky Gutierrez Airport": "Sitka Rocky Gutierrez Airport",
    "Sloulin Field International Airport":
      "Sloulin Field International Airport",
    "South Bend International Airport (South Bend Regional)":
      "South Bend International Airport (South Bend Regional)",
    "Southwest Florida International Airport":
      "Southwest Florida International Airport",
    "Southwest Georgia Regional Airport": "Southwest Georgia Regional Airport",
    "Southwest Oregon Regional Airport (North Bend Municipal)":
      "Southwest Oregon Regional Airport (North Bend Municipal)",
    "Spokane International Airport": "Spokane International Airport",
    "Springfield-Branson National Airport":
      "Springfield-Branson National Airport",
    "St. Cloud Regional Airport": "St. Cloud Regional Airport",
    "St. George Regional Airport": "St. George Regional Airport",
    "St. Louis International Airport at Lambert Field":
      "St. Louis International Airport at Lambert Field",
    "Stewart International Airport": "Stewart International Airport",
    "Syracuse Hancock International Airport":
      "Syracuse Hancock International Airport",
    "Tallahassee International Airport": "Tallahassee International Airport",
    "Tampa International Airport": "Tampa International Airport",
    "Ted Stevens Anchorage International Airport":
      "Ted Stevens Anchorage International Airport",
    "Texarkana Regional Airport (Webb Field)":
      "Texarkana Regional Airport (Webb Field)",
    "The Eastern Iowa Airport": "The Eastern Iowa Airport",
    "Theodore Francis Green State Airport":
      "Theodore Francis Green State Airport",
    "Toledo Express Airport": "Toledo Express Airport",
    "Trenton Mercer Airport": "Trenton Mercer Airport",
    "Tri-Cities Airport": "Tri-Cities Airport",
    "Tri-Cities Regional Airport": "Tri-Cities Regional Airport",
    "Tucson International Airport": "Tucson International Airport",
    "Tulsa International Airport": "Tulsa International Airport",
    "Tyler Pounds Regional Airport": "Tyler Pounds Regional Airport",
    "University Park Airport": "University Park Airport",
    "University of Illinois - Willard Airport":
      "University of Illinois - Willard Airport",
    "Valdez Airport": "Valdez Airport",
    "Valdosta Regional Airport": "Valdosta Regional Airport",
    "Valley International Airport": "Valley International Airport",
    "Waco Regional Airport": "Waco Regional Airport",
    "Washington Dulles International Airport":
      "Washington Dulles International Airport",
    "Waterloo Regional Airport": "Waterloo Regional Airport",
    "Westchester County Airport": "Westchester County Airport",
    "Westerly State Airport": "Westerly State Airport",
    "Wichita Dwight D. Eisenhower National Airport (Wichita Mid-Continent Airport)":
      "Wichita Dwight D. Eisenhower National Airport (Wichita Mid-Continent Airport)",
    "Wichita Falls Municipal Airport/Sheppard AFB":
      "Wichita Falls Municipal Airport/Sheppard AFB",
    "Wiley Post-Will Rogers Memorial Airport":
      "Wiley Post-Will Rogers Memorial Airport",
    "Wilkes-Barre/Scranton International Airport":
      "Wilkes-Barre/Scranton International Airport",
    "Will Rogers World Airport": "Will Rogers World Airport",
    "William P. Hobby Airport": "William P. Hobby Airport",
    "Wilmington Airport": "Wilmington Airport",
    "Wilmington International Airport": "Wilmington International Airport",
    "Worcester Regional Airport": "Worcester Regional Airport",
    "Wrangell Airport": "Wrangell Airport",
    "Yakutat Airport": "Yakutat Airport",
    "Yampa Valley Airport (Yampa Valley Regional)":
      "Yampa Valley Airport (Yampa Valley Regional)",
    "Yeager Airport": "Yeager Airport",
    "Yellowstone Regional Airport": "Yellowstone Regional Airport",
    "Yuma International Airport": "Yuma International Airport",
  },
  "Origin City": {
    Aberdeen: "Aberdeen",
    Abilene: "Abilene",
    Adak: "Adak",
    Agana: "Agana",
    Aguadilla: "Aguadilla",
    Akron: "Akron",
    Albany: "Albany",
    Albuquerque: "Albuquerque",
    Alexandria: "Alexandria",
    Allentown: "Allentown",
    Alpena: "Alpena",
    Amarillo: "Amarillo",
    Anchorage: "Anchorage",
    Appleton: "Appleton",
    "Arcata/Eureka": "Arcata/Eureka",
    Arlington: "Arlington",
    Asheville: "Asheville",
    Aspen: "Aspen",
    Atlanta: "Atlanta",
    "Atlantic City": "Atlantic City",
    Augusta: "Augusta",
    Austin: "Austin",
    Bakersfield: "Bakersfield",
    Baltimore: "Baltimore",
    Bangor: "Bangor",
    Barrow: "Barrow",
    "Baton Rouge": "Baton Rouge",
    "Beaumont/Port Arthur": "Beaumont/Port Arthur",
    Bellingham: "Bellingham",
    Bemidji: "Bemidji",
    Bethel: "Bethel",
    Billings: "Billings",
    Binghamton: "Binghamton",
    Birmingham: "Birmingham",
    Bismarck: "Bismarck",
    Bloomington: "Bloomington",
    Boise: "Boise",
    Boston: "Boston",
    Bozeman: "Bozeman",
    Brainerd: "Brainerd",
    Bristol: "Bristol",
    Brownsville: "Brownsville",
    Brunswick: "Brunswick",
    Buffalo: "Buffalo",
    Burbank: "Burbank",
    Burlington: "Burlington",
    Butte: "Butte",
    Casper: "Casper",
    "Cedar City": "Cedar City",
    "Cedar Rapids": "Cedar Rapids",
    "Champaign/Urbana": "Champaign/Urbana",
    Chantilly: "Chantilly",
    Charleston: "Charleston",
    Charlotte: "Charlotte",
    "Charlotte Amalie": "Charlotte Amalie",
    Charlottesville: "Charlottesville",
    Chattanooga: "Chattanooga",
    Chicago: "Chicago",
    Christiansted: "Christiansted",
    Cleveland: "Cleveland",
    Cody: "Cody",
    "College Station": "College Station",
    "Colorado Springs": "Colorado Springs",
    Columbia: "Columbia",
    Columbus: "Columbus",
    "Columbus-Starkville-West Point": "Columbus-Starkville-West Point",
    Cordova: "Cordova",
    "Corpus Christi": "Corpus Christi",
    Covington: "Covington",
    "Crescent City": "Crescent City",
    Dallas: "Dallas",
    "Dallas-Fort Worth": "Dallas-Fort Worth",
    Dayton: "Dayton",
    "Daytona Beach": "Daytona Beach",
    Deadhorse: "Deadhorse",
    Denver: "Denver",
    "Des Moines": "Des Moines",
    Detroit: "Detroit",
    "Devils Lake": "Devils Lake",
    Dickinson: "Dickinson",
    Dillingham: "Dillingham",
    Dothan: "Dothan",
    Dubuque: "Dubuque",
    Duluth: "Duluth",
    Durango: "Durango",
    Eagle: "Eagle",
    "Eau Claire": "Eau Claire",
    "El Paso": "El Paso",
    Elko: "Elko",
    Elmira: "Elmira",
    Erie: "Erie",
    Escanaba: "Escanaba",
    Eugene: "Eugene",
    Evansville: "Evansville",
    Fairbanks: "Fairbanks",
    Fargo: "Fargo",
    Fayetteville: "Fayetteville",
    "Fayetteville/Springdale/Rogers": "Fayetteville/Springdale/Rogers",
    Flagstaff: "Flagstaff",
    Flint: "Flint",
    "Fort Smith": "Fort Smith",
    "Fort Wayne": "Fort Wayne",
    Fresno: "Fresno",
    "Ft. Lauderdale": "Ft. Lauderdale",
    "Ft. Myers": "Ft. Myers",
    Gainesville: "Gainesville",
    "Garden City": "Garden City",
    Gillette: "Gillette",
    "Grand Forks": "Grand Forks",
    "Grand Island": "Grand Island",
    "Grand Junction": "Grand Junction",
    "Grand Rapids": "Grand Rapids",
    "Great Falls": "Great Falls",
    "Green Bay": "Green Bay",
    Greensboro: "Greensboro",
    Greer: "Greer",
    "Gulfport-Biloxi": "Gulfport-Biloxi",
    Gunnison: "Gunnison",
    Gustavus: "Gustavus",
    Hailey: "Hailey",
    Hancock: "Hancock",
    Harlingen: "Harlingen",
    Harrisburg: "Harrisburg",
    "Hattiesburg-Laurel": "Hattiesburg-Laurel",
    Hayden: "Hayden",
    Hays: "Hays",
    Helena: "Helena",
    Hibbing: "Hibbing",
    Hilo: "Hilo",
    Hobbs: "Hobbs",
    Honolulu: "Honolulu",
    Houston: "Houston",
    Huntsville: "Huntsville",
    Hyannis: "Hyannis",
    "Idaho Falls": "Idaho Falls",
    Indianapolis: "Indianapolis",
    "International Falls": "International Falls",
    "Iron Mountain/Kingsford": "Iron Mountain/Kingsford",
    Islip: "Islip",
    Ithaca: "Ithaca",
    Jackson: "Jackson",
    Jacksonville: "Jacksonville",
    Jamestown: "Jamestown",
    Joplin: "Joplin",
    Juneau: "Juneau",
    Kahului: "Kahului",
    "Kailua/Kona": "Kailua/Kona",
    Kalamazoo: "Kalamazoo",
    Kalispell: "Kalispell",
    "Kansas City": "Kansas City",
    Ketchikan: "Ketchikan",
    "Key West": "Key West",
    Killeen: "Killeen",
    "King Salmon": "King Salmon",
    Knoxville: "Knoxville",
    Kodiak: "Kodiak",
    Kotzebue: "Kotzebue",
    "La Crosse": "La Crosse",
    Lafayette: "Lafayette",
    "Lake Charles": "Lake Charles",
    Lansing: "Lansing",
    Laramie: "Laramie",
    Laredo: "Laredo",
    "Las Vegas": "Las Vegas",
    Latrobe: "Latrobe",
    Lawton: "Lawton",
    Lewiston: "Lewiston",
    Lexington: "Lexington",
    Lihue: "Lihue",
    Lincoln: "Lincoln",
    "Little Rock": "Little Rock",
    "Long Beach": "Long Beach",
    Longview: "Longview",
    "Los Angeles": "Los Angeles",
    Louisville: "Louisville",
    Lubbock: "Lubbock",
    Madison: "Madison",
    "Mammoth Lakes": "Mammoth Lakes",
    Manchester: "Manchester",
    Manhattan: "Manhattan",
    Marquette: "Marquette",
    "Marthas Vineyard": "Marthas Vineyard",
    McAllen: "McAllen",
    Medford: "Medford",
    Melbourne: "Melbourne",
    Memphis: "Memphis",
    Meridian: "Meridian",
    Miami: "Miami",
    Midland: "Midland",
    Milwaukee: "Milwaukee",
    Minneapolis: "Minneapolis",
    Minot: "Minot",
    Missoula: "Missoula",
    Moab: "Moab",
    Mobile: "Mobile",
    Moline: "Moline",
    Monroe: "Monroe",
    Monterey: "Monterey",
    Montgomery: "Montgomery",
    Montrose: "Montrose",
    Mosinee: "Mosinee",
    Muskegon: "Muskegon",
    "Myrtle Beach": "Myrtle Beach",
    Nantucket: "Nantucket",
    Nashville: "Nashville",
    "New Bern": "New Bern",
    "New Orleans": "New Orleans",
    "New York": "New York",
    Newark: "Newark",
    Newburgh: "Newburgh",
    "Newport News": "Newport News",
    "Niagara Falls": "Niagara Falls",
    Nome: "Nome",
    Norfolk: "Norfolk",
    "North Bend": "North Bend",
    Oakland: "Oakland",
    "Oklahoma City": "Oklahoma City",
    Omaha: "Omaha",
    Ontario: "Ontario",
    Orlando: "Orlando",
    Paducah: "Paducah",
    "Pago Pago": "Pago Pago",
    "Palm Springs": "Palm Springs",
    "Panama City": "Panama City",
    Pasco: "Pasco",
    Pellston: "Pellston",
    Pensacola: "Pensacola",
    Peoria: "Peoria",
    Petersburg: "Petersburg",
    Philadelphia: "Philadelphia",
    Phoenix: "Phoenix",
    Pittsburgh: "Pittsburgh",
    Plattsburgh: "Plattsburgh",
    Pocatello: "Pocatello",
    Ponce: "Ponce",
    Portland: "Portland",
    Providence: "Providence",
    Pueblo: "Pueblo",
    Raleigh: "Raleigh",
    "Rapid City": "Rapid City",
    Redding: "Redding",
    Redmond: "Redmond",
    Reno: "Reno",
    Rhinelander: "Rhinelander",
    Richmond: "Richmond",
    Roanoke: "Roanoke",
    Rochester: "Rochester",
    "Rock Springs": "Rock Springs",
    Roswell: "Roswell",
    Sacramento: "Sacramento",
    Saginaw: "Saginaw",
    "Salt Lake City": "Salt Lake City",
    "San Angelo": "San Angelo",
    "San Antonio": "San Antonio",
    "San Diego": "San Diego",
    "San Francisco": "San Francisco",
    "San Jose": "San Jose",
    "San Juan": "San Juan",
    "San Luis Obispo": "San Luis Obispo",
    "Santa Ana": "Santa Ana",
    "Santa Barbara": "Santa Barbara",
    "Santa Fe": "Santa Fe",
    "Santa Maria": "Santa Maria",
    Sarasota: "Sarasota",
    "Sault Ste. Marie": "Sault Ste. Marie",
    Savannah: "Savannah",
    Seattle: "Seattle",
    Shreveport: "Shreveport",
    "Sioux City": "Sioux City",
    "Sioux Falls": "Sioux Falls",
    Sitka: "Sitka",
    "South Bend": "South Bend",
    Spokane: "Spokane",
    Springfield: "Springfield",
    "St Cloud": "St Cloud",
    "St George": "St George",
    "St Louis": "St Louis",
    "St. Augustine": "St. Augustine",
    "State College": "State College",
    Syracuse: "Syracuse",
    Tallahassee: "Tallahassee",
    Tampa: "Tampa",
    Texarkana: "Texarkana",
    Toledo: "Toledo",
    "Traverse City": "Traverse City",
    Trenton: "Trenton",
    Tucson: "Tucson",
    Tulsa: "Tulsa",
    "Twin Falls": "Twin Falls",
    Tyler: "Tyler",
    Valdosta: "Valdosta",
    Valparaiso: "Valparaiso",
    Vernal: "Vernal",
    Waco: "Waco",
    Waterloo: "Waterloo",
    "West Palm Beach": "West Palm Beach",
    "West Yellowstone": "West Yellowstone",
    "White Plains": "White Plains",
    Wichita: "Wichita",
    "Wichita Falls": "Wichita Falls",
    "Wilkes-Barre/Scranton": "Wilkes-Barre/Scranton",
    Williston: "Williston",
    Wilmington: "Wilmington",
    "Windsor Locks": "Windsor Locks",
    Worcester: "Worcester",
    Wrangell: "Wrangell",
    Yakutat: "Yakutat",
    Yuma: "Yuma",
  },
  "Origin State": {
    AK: "AK",
    AL: "AL",
    AR: "AR",
    AS: "AS",
    AZ: "AZ",
    CA: "CA",
    CO: "CO",
    CT: "CT",
    DE: "DE",
    FL: "FL",
    GA: "GA",
    GU: "GU",
    HI: "HI",
    IA: "IA",
    ID: "ID",
    IL: "IL",
    IN: "IN",
    KS: "KS",
    KY: "KY",
    LA: "LA",
    MA: "MA",
    MD: "MD",
    ME: "ME",
    MI: "MI",
    MN: "MN",
    MO: "MO",
    MS: "MS",
    MT: "MT",
    NC: "NC",
    ND: "ND",
    NE: "NE",
    NH: "NH",
    NJ: "NJ",
    NM: "NM",
    NV: "NV",
    NY: "NY",
    OH: "OH",
    OK: "OK",
    OR: "OR",
    PA: "PA",
    PR: "PR",
    RI: "RI",
    SC: "SC",
    SD: "SD",
    TN: "TN",
    TX: "TX",
    UT: "UT",
    VA: "VA",
    VI: "VI",
    VT: "VT",
    WA: "WA",
    WI: "WI",
    WV: "WV",
    WY: "WY",
  },
  "Destination Airport": {
    "Aberdeen Regional Airport": "Aberdeen Regional Airport",
    "Abilene Regional Airport": "Abilene Regional Airport",
    "Abraham Lincoln Capital Airport": "Abraham Lincoln Capital Airport",
    "Adak Airport": "Adak Airport",
    "Akron-Canton Regional Airport": "Akron-Canton Regional Airport",
    "Albany International Airport": "Albany International Airport",
    "Albert J. Ellis Airport": "Albert J. Ellis Airport",
    "Albuquerque International Sunport": "Albuquerque International Sunport",
    "Alexandria International Airport": "Alexandria International Airport",
    "Alpena County Regional Airport": "Alpena County Regional Airport",
    "Appleton International Airport": "Appleton International Airport",
    "Arcata Airport": "Arcata Airport",
    "Arnold Palmer Regional Airport": "Arnold Palmer Regional Airport",
    "Asheville Regional Airport": "Asheville Regional Airport",
    "Aspen-Pitkin County Airport": "Aspen-Pitkin County Airport",
    "Atlantic City International Airport":
      "Atlantic City International Airport",
    "Augusta Regional Airport (Bush Field)":
      "Augusta Regional Airport (Bush Field)",
    "Austin-Bergstrom International Airport":
      "Austin-Bergstrom International Airport",
    "Baltimore-Washington International Airport":
      "Baltimore-Washington International Airport",
    "Bangor International Airport": "Bangor International Airport",
    "Barkley Regional Airport": "Barkley Regional Airport",
    "Barnstable Municipal Airport": "Barnstable Municipal Airport",
    "Baton Rouge Metropolitan Airport": "Baton Rouge Metropolitan Airport",
    "Bellingham International Airport": "Bellingham International Airport",
    "Bemidji Regional Airport": "Bemidji Regional Airport",
    "Bert Mooney Airport": "Bert Mooney Airport",
    "Bethel Airport": "Bethel Airport",
    "Bill and Hillary Clinton National Airport (Adams Field)":
      "Bill and Hillary Clinton National Airport (Adams Field)",
    "Billings Logan International Airport":
      "Billings Logan International Airport",
    "Birmingham-Shuttlesworth International Airport":
      "Birmingham-Shuttlesworth International Airport",
    "Bishop International Airport": "Bishop International Airport",
    "Bismarck Municipal Airport": "Bismarck Municipal Airport",
    "Blue Grass Airport": "Blue Grass Airport",
    "Bob Hope Airport (Hollywood Burbank Airport)":
      "Bob Hope Airport (Hollywood Burbank Airport)",
    "Boise Airport (Boise Air Terminal)": "Boise Airport (Boise Air Terminal)",
    "Bozeman Yellowstone International Airport (Gallatin Field Airport)":
      "Bozeman Yellowstone International Airport (Gallatin Field Airport)",
    "Bradley International Airport": "Bradley International Airport",
    "Brainerd Lakes Regional Airport": "Brainerd Lakes Regional Airport",
    "Brownsville/South Padre Island International Airport":
      "Brownsville/South Padre Island International Airport",
    "Brunswick Golden Isles Airport": "Brunswick Golden Isles Airport",
    "Buffalo Niagara International Airport":
      "Buffalo Niagara International Airport",
    "Burlington International Airport": "Burlington International Airport",
    "Canyonlands Field": "Canyonlands Field",
    "Capital Region International Airport ( Lansing Capital City)":
      "Capital Region International Airport ( Lansing Capital City)",
    "Cedar City Regional Airport": "Cedar City Regional Airport",
    "Central Illinois Regional Airport at Bloomington-Normal":
      "Central Illinois Regional Airport at Bloomington-Normal",
    "Central Nebraska Regional Airport": "Central Nebraska Regional Airport",
    "Central Wisconsin Airport": "Central Wisconsin Airport",
    "Charleston International Airport/Charleston AFB":
      "Charleston International Airport/Charleston AFB",
    "Charlotte Douglas International Airport":
      "Charlotte Douglas International Airport",
    "Charlottesville-Albemarle Airport": "Charlottesville-Albemarle Airport",
    "Chattanooga Metropolitan Airport (Lovell Field)":
      "Chattanooga Metropolitan Airport (Lovell Field)",
    "Cherry Capital Airport": "Cherry Capital Airport",
    "Chicago Midway International Airport":
      "Chicago Midway International Airport",
    "Chicago O'Hare International Airport":
      "Chicago O'Hare International Airport",
    "Chippewa County International Airport":
      "Chippewa County International Airport",
    "Chippewa Valley Regional Airport": "Chippewa Valley Regional Airport",
    "Cincinnati/Northern Kentucky International Airport":
      "Cincinnati/Northern Kentucky International Airport",
    "City of Colorado Springs Municipal Airport":
      "City of Colorado Springs Municipal Airport",
    "Cleveland Hopkins International Airport":
      "Cleveland Hopkins International Airport",
    "Coastal Carolina Regional Airport (Craven County Regional)":
      "Coastal Carolina Regional Airport (Craven County Regional)",
    "Columbia Metropolitan Airport": "Columbia Metropolitan Airport",
    "Columbia Regional Airport": "Columbia Regional Airport",
    "Columbus Metropolitan Airport": "Columbus Metropolitan Airport",
    "Corpus Christi International Airport":
      "Corpus Christi International Airport",
    "Cyril E. King Airport": "Cyril E. King Airport",
    "Dallas Love Field": "Dallas Love Field",
    "Dallas/Fort Worth International Airport":
      "Dallas/Fort Worth International Airport",
    "Dane County Regional Airport": "Dane County Regional Airport",
    "Daytona Beach International Airport":
      "Daytona Beach International Airport",
    "Deadhorse Airport (Prudhoe Bay Airport)":
      "Deadhorse Airport (Prudhoe Bay Airport)",
    "Del Norte County Airport (Jack McNamara Field)":
      "Del Norte County Airport (Jack McNamara Field)",
    "Delta County Airport": "Delta County Airport",
    "Denver International Airport": "Denver International Airport",
    "Des Moines International Airport": "Des Moines International Airport",
    "Destin-Fort Walton Beach Airport/Eglin AFB":
      "Destin-Fort Walton Beach Airport/Eglin AFB",
    "Detroit Metropolitan Airport": "Detroit Metropolitan Airport",
    "Devils Lake Regional Airport": "Devils Lake Regional Airport",
    "Dickinson Theodore Roosevelt Regional Airport":
      "Dickinson Theodore Roosevelt Regional Airport",
    "Dillingham Airport": "Dillingham Airport",
    "Dothan Regional Airport": "Dothan Regional Airport",
    "Dubuque Regional Airport": "Dubuque Regional Airport",
    "Duluth International Airport": "Duluth International Airport",
    "Durango-La Plata County Airport": "Durango-La Plata County Airport",
    "Eagle County Regional Airport": "Eagle County Regional Airport",
    "East Texas Regional Airport": "East Texas Regional Airport",
    "Easterwood Airport": "Easterwood Airport",
    "El Paso International Airport": "El Paso International Airport",
    "Elko Regional Airport": "Elko Regional Airport",
    "Elmira/Corning Regional Airport": "Elmira/Corning Regional Airport",
    "Eppley Airfield": "Eppley Airfield",
    "Erie International Airport": "Erie International Airport",
    "Eugene Airport (Mahlon Sweet Field)":
      "Eugene Airport (Mahlon Sweet Field)",
    "Evansville Regional Airport": "Evansville Regional Airport",
    "Fairbanks International Airport": "Fairbanks International Airport",
    "Falls International Airport": "Falls International Airport",
    "Fayetteville Regional Airport": "Fayetteville Regional Airport",
    "Flagstaff Pulliam Airport": "Flagstaff Pulliam Airport",
    "Ford Airport": "Ford Airport",
    "Fort Lauderdale-Hollywood International Airport":
      "Fort Lauderdale-Hollywood International Airport",
    "Fort Smith Regional Airport": "Fort Smith Regional Airport",
    "Fort Wayne International Airport": "Fort Wayne International Airport",
    "Fresno Yosemite International Airport":
      "Fresno Yosemite International Airport",
    "Friedman Memorial Airport": "Friedman Memorial Airport",
    "Gainesville Regional Airport": "Gainesville Regional Airport",
    "Garden City Regional Airport": "Garden City Regional Airport",
    "Gen. Edward Lawrence Logan International Airport":
      "Gen. Edward Lawrence Logan International Airport",
    "General Mitchell International Airport":
      "General Mitchell International Airport",
    "General Wayne A. Downing Peoria International Airport":
      "General Wayne A. Downing Peoria International Airport",
    "George Bush Intercontinental Airport":
      "George Bush Intercontinental Airport",
    "Gerald R. Ford International Airport":
      "Gerald R. Ford International Airport",
    "Gillette-Campbell County Airport": "Gillette-Campbell County Airport",
    "Glacier Park International Airport": "Glacier Park International Airport",
    "Golden Triangle Regional Airport": "Golden Triangle Regional Airport",
    "Grand Forks International Airport": "Grand Forks International Airport",
    "Grand Junction Regional Airport (Walker Field)":
      "Grand Junction Regional Airport (Walker Field)",
    "Great Falls International Airport": "Great Falls International Airport",
    "Greater Binghamton Airport": "Greater Binghamton Airport",
    "Greater Rochester International Airport":
      "Greater Rochester International Airport",
    "Green Bay-Austin Straubel International Airport":
      "Green Bay-Austin Straubel International Airport",
    "Greenville-Spartanburg International Airport":
      "Greenville-Spartanburg International Airport",
    "Guam International Airport": "Guam International Airport",
    "Gulfport-Biloxi International Airport":
      "Gulfport-Biloxi International Airport",
    "Gunnison-Crested Butte Regional Airport":
      "Gunnison-Crested Butte Regional Airport",
    "Gustavus Airport": "Gustavus Airport",
    "Harrisburg International Airport": "Harrisburg International Airport",
    "Hartsfield-Jackson Atlanta International Airport":
      "Hartsfield-Jackson Atlanta International Airport",
    "Hattiesburg-Laurel Regional Airport":
      "Hattiesburg-Laurel Regional Airport",
    "Hays Regional Airport": "Hays Regional Airport",
    "Hector International Airport": "Hector International Airport",
    "Helena Regional Airport": "Helena Regional Airport",
    "Henry E. Rohlsen Airport": "Henry E. Rohlsen Airport",
    "Hilo International Airport": "Hilo International Airport",
    "Honolulu International Airport": "Honolulu International Airport",
    "Houghton County Memorial Airport": "Houghton County Memorial Airport",
    "Huntsville International Airport": "Huntsville International Airport",
    "Idaho Falls Regional Airport": "Idaho Falls Regional Airport",
    "Indianapolis International Airport": "Indianapolis International Airport",
    "Ithaca Tompkins Regional Airport": "Ithaca Tompkins Regional Airport",
    "Jack Brooks Regional Airport (Southeast Texas Regional)":
      "Jack Brooks Regional Airport (Southeast Texas Regional)",
    "Jackson Hole Airport": "Jackson Hole Airport",
    "Jackson-Evers International Airport":
      "Jackson-Evers International Airport",
    "Jacksonville International Airport": "Jacksonville International Airport",
    "James M. Cox Dayton International Airport":
      "James M. Cox Dayton International Airport",
    "Jamestown Regional Airport": "Jamestown Regional Airport",
    "John F. Kennedy International Airport (New York International Airport)":
      "John F. Kennedy International Airport (New York International Airport)",
    "John Wayne Airport (Orange County Airport)":
      "John Wayne Airport (Orange County Airport)",
    "Joplin Regional Airport": "Joplin Regional Airport",
    "Juneau International Airport": "Juneau International Airport",
    "Kahului Airport": "Kahului Airport",
    "Kalamazoo/Battle Creek International Airport":
      "Kalamazoo/Battle Creek International Airport",
    "Kansas City International Airport": "Kansas City International Airport",
    "Ketchikan International Airport": "Ketchikan International Airport",
    "Key West International Airport": "Key West International Airport",
    "Killeen-Fort Hood Regional Airport": "Killeen-Fort Hood Regional Airport",
    "King Salmon Airport": "King Salmon Airport",
    "Kodiak Airport": "Kodiak Airport",
    "Kona International Airport at Keahole":
      "Kona International Airport at Keahole",
    "La Crosse Regional Airport": "La Crosse Regional Airport",
    "LaGuardia Airport (Marine Air Terminal)":
      "LaGuardia Airport (Marine Air Terminal)",
    "Lafayette Regional Airport": "Lafayette Regional Airport",
    "Lake Charles Regional Airport": "Lake Charles Regional Airport",
    "Laramie Regional Airport": "Laramie Regional Airport",
    "Laredo International Airport": "Laredo International Airport",
    "Lawton-Fort Sill Regional Airport": "Lawton-Fort Sill Regional Airport",
    "Lea County Regional Airport": "Lea County Regional Airport",
    "Lehigh Valley International Airport":
      "Lehigh Valley International Airport",
    "Lewiston-Nez Perce County Airport": "Lewiston-Nez Perce County Airport",
    "Lihue Airport": "Lihue Airport",
    "Lincoln Airport (Lincoln Municipal)":
      "Lincoln Airport (Lincoln Municipal)",
    "Long Beach Airport (Daugherty Field)":
      "Long Beach Airport (Daugherty Field)",
    "Long Island MacArthur Airport": "Long Island MacArthur Airport",
    "Los Angeles International Airport": "Los Angeles International Airport",
    "Louis Armstrong New Orleans International Airport":
      "Louis Armstrong New Orleans International Airport",
    "Louisville International Airport (Standiford Field)":
      "Louisville International Airport (Standiford Field)",
    "Lubbock Preston Smith International Airport":
      "Lubbock Preston Smith International Airport",
    "Luis Muñoz Marín International Airport":
      "Luis Muñoz Marín International Airport",
    "MBS International Airport": "MBS International Airport",
    "Magic Valley Regional Airport (Joslin Field)":
      "Magic Valley Regional Airport (Joslin Field)",
    "Mammoth Yosemite Airport": "Mammoth Yosemite Airport",
    "Manchester-Boston Regional Airport": "Manchester-Boston Regional Airport",
    "Manhattan Regional Airport": "Manhattan Regional Airport",
    "Martha's Vineyard Airport": "Martha's Vineyard Airport",
    "McAllen-Miller International Airport (McAllen Miller International)":
      "McAllen-Miller International Airport (McAllen Miller International)",
    "McCarran International Airport": "McCarran International Airport",
    "McClellan-Palomar Airport": "McClellan-Palomar Airport",
    "McGhee Tyson Airport": "McGhee Tyson Airport",
    "Meadows Field": "Meadows Field",
    "Melbourne International Airport": "Melbourne International Airport",
    "Memphis International Airport": "Memphis International Airport",
    "Mercedita Airport": "Mercedita Airport",
    "Meridian Regional Airport": "Meridian Regional Airport",
    "Merle K. (Mudhole) Smith Airport": "Merle K. (Mudhole) Smith Airport",
    "Miami International Airport": "Miami International Airport",
    "Midland International Airport": "Midland International Airport",
    "Minneapolis-Saint Paul International Airport":
      "Minneapolis-Saint Paul International Airport",
    "Minot International Airport": "Minot International Airport",
    "Missoula International Airport": "Missoula International Airport",
    "Mobile Regional Airport": "Mobile Regional Airport",
    "Monroe Regional Airport": "Monroe Regional Airport",
    "Monterey Regional Airport (Monterey Peninsula Airport)":
      "Monterey Regional Airport (Monterey Peninsula Airport)",
    "Montgomery Regional Airport": "Montgomery Regional Airport",
    "Montrose Regional Airport": "Montrose Regional Airport",
    "Muskegon County Airport": "Muskegon County Airport",
    "Myrtle Beach International Airport": "Myrtle Beach International Airport",
    "Nantucket Memorial Airport": "Nantucket Memorial Airport",
    "Nashville International Airport": "Nashville International Airport",
    "Natrona County International Airport":
      "Natrona County International Airport",
    "Newark Liberty International Airport":
      "Newark Liberty International Airport",
    "Newport News/Williamsburg International Airport":
      "Newport News/Williamsburg International Airport",
    "Niagara Falls International Airport":
      "Niagara Falls International Airport",
    "Nome Airport": "Nome Airport",
    "Norfolk International Airport": "Norfolk International Airport",
    "Norman Y. Mineta San José International Airport":
      "Norman Y. Mineta San José International Airport",
    "Northeast Florida Regional Airport (St. Augustine Airport)":
      "Northeast Florida Regional Airport (St. Augustine Airport)",
    "Northwest Arkansas Regional Airport":
      "Northwest Arkansas Regional Airport",
    "Northwest Florida Beaches International Airport":
      "Northwest Florida Beaches International Airport",
    "Oakland International Airport": "Oakland International Airport",
    "Ontario International Airport": "Ontario International Airport",
    "Orlando International Airport": "Orlando International Airport",
    "Pago Pago International Airport (Tafuna Airport)":
      "Pago Pago International Airport (Tafuna Airport)",
    "Palm Beach International Airport": "Palm Beach International Airport",
    "Palm Springs International Airport": "Palm Springs International Airport",
    "Pellston Regional Airport of Emmet County":
      "Pellston Regional Airport of Emmet County",
    "Pensacola International Airport (Pensacola Gulf Coast Regional Airport)":
      "Pensacola International Airport (Pensacola Gulf Coast Regional Airport)",
    "Petersburg James A. Johnson Airport":
      "Petersburg James A. Johnson Airport",
    "Philadelphia International Airport": "Philadelphia International Airport",
    "Phoenix Sky Harbor International Airport":
      "Phoenix Sky Harbor International Airport",
    "Piedmont Triad International Airport":
      "Piedmont Triad International Airport",
    "Pittsburgh International Airport": "Pittsburgh International Airport",
    "Plattsburgh International Airport": "Plattsburgh International Airport",
    "Pocatello Regional Airport": "Pocatello Regional Airport",
    "Port Columbus International Airport":
      "Port Columbus International Airport",
    "Portland International Airport": "Portland International Airport",
    "Portland International Jetport": "Portland International Jetport",
    "Pueblo Memorial Airport": "Pueblo Memorial Airport",
    "Quad City International Airport": "Quad City International Airport",
    "Rafael Hernández Airport": "Rafael Hernández Airport",
    "Raleigh-Durham International Airport":
      "Raleigh-Durham International Airport",
    "Ralph Wien Memorial Airport": "Ralph Wien Memorial Airport",
    "Range Regional Airport (Chisholm-Hibbing Airport)":
      "Range Regional Airport (Chisholm-Hibbing Airport)",
    "Rapid City Regional Airport": "Rapid City Regional Airport",
    "Redding Municipal Airport": "Redding Municipal Airport",
    "Redmond Municipal Airport (Roberts Field)":
      "Redmond Municipal Airport (Roberts Field)",
    "Reno/Tahoe International Airport": "Reno/Tahoe International Airport",
    "Rhinelander-Oneida County Airport": "Rhinelander-Oneida County Airport",
    "Richmond International Airport": "Richmond International Airport",
    "Rick Husband Amarillo International Airport":
      "Rick Husband Amarillo International Airport",
    "Roanoke Regional Airport (Woodrum Field)":
      "Roanoke Regional Airport (Woodrum Field)",
    "Rochester International Airport": "Rochester International Airport",
    "Rock Springs-Sweetwater County Airport":
      "Rock Springs-Sweetwater County Airport",
    "Rogue Valley International Airport": "Rogue Valley International Airport",
    "Ronald Reagan Washington National Airport":
      "Ronald Reagan Washington National Airport",
    "Roswell International Air Center": "Roswell International Air Center",
    "Sacramento International Airport": "Sacramento International Airport",
    "Salt Lake City International Airport":
      "Salt Lake City International Airport",
    "San Angelo Regional Airport (Mathis Field)":
      "San Angelo Regional Airport (Mathis Field)",
    "San Antonio International Airport": "San Antonio International Airport",
    "San Diego International Airport (Lindbergh Field)":
      "San Diego International Airport (Lindbergh Field)",
    "San Francisco International Airport":
      "San Francisco International Airport",
    "San Luis Obispo County Regional Airport (McChesney Field)":
      "San Luis Obispo County Regional Airport (McChesney Field)",
    "Santa Barbara Municipal Airport (Santa Barbara Airport)":
      "Santa Barbara Municipal Airport (Santa Barbara Airport)",
    "Santa Fe Municipal Airport": "Santa Fe Municipal Airport",
    "Santa Maria Public Airport (Capt G. Allan Hancock Field)":
      "Santa Maria Public Airport (Capt G. Allan Hancock Field)",
    "Sarasota-Bradenton International Airport":
      "Sarasota-Bradenton International Airport",
    "Savannah/Hilton Head International Airport":
      "Savannah/Hilton Head International Airport",
    "Sawyer International Airport": "Sawyer International Airport",
    "Seattle-Tacoma International Airport":
      "Seattle-Tacoma International Airport",
    "Shreveport Regional Airport": "Shreveport Regional Airport",
    "Sioux Falls Regional Airport": "Sioux Falls Regional Airport",
    "Sioux Gateway Airport": "Sioux Gateway Airport",
    "Sitka Rocky Gutierrez Airport": "Sitka Rocky Gutierrez Airport",
    "Sloulin Field International Airport":
      "Sloulin Field International Airport",
    "South Bend International Airport (South Bend Regional)":
      "South Bend International Airport (South Bend Regional)",
    "Southwest Florida International Airport":
      "Southwest Florida International Airport",
    "Southwest Georgia Regional Airport": "Southwest Georgia Regional Airport",
    "Southwest Oregon Regional Airport (North Bend Municipal)":
      "Southwest Oregon Regional Airport (North Bend Municipal)",
    "Spokane International Airport": "Spokane International Airport",
    "Springfield-Branson National Airport":
      "Springfield-Branson National Airport",
    "St. Cloud Regional Airport": "St. Cloud Regional Airport",
    "St. George Regional Airport": "St. George Regional Airport",
    "St. Louis International Airport at Lambert Field":
      "St. Louis International Airport at Lambert Field",
    "Stewart International Airport": "Stewart International Airport",
    "Syracuse Hancock International Airport":
      "Syracuse Hancock International Airport",
    "Tallahassee International Airport": "Tallahassee International Airport",
    "Tampa International Airport": "Tampa International Airport",
    "Ted Stevens Anchorage International Airport":
      "Ted Stevens Anchorage International Airport",
    "Texarkana Regional Airport (Webb Field)":
      "Texarkana Regional Airport (Webb Field)",
    "The Eastern Iowa Airport": "The Eastern Iowa Airport",
    "Theodore Francis Green State Airport":
      "Theodore Francis Green State Airport",
    "Toledo Express Airport": "Toledo Express Airport",
    "Trenton Mercer Airport": "Trenton Mercer Airport",
    "Tri-Cities Airport": "Tri-Cities Airport",
    "Tri-Cities Regional Airport": "Tri-Cities Regional Airport",
    "Tucson International Airport": "Tucson International Airport",
    "Tulsa International Airport": "Tulsa International Airport",
    "Tyler Pounds Regional Airport": "Tyler Pounds Regional Airport",
    "University Park Airport": "University Park Airport",
    "University of Illinois - Willard Airport":
      "University of Illinois - Willard Airport",
    "Valdez Airport": "Valdez Airport",
    "Valdosta Regional Airport": "Valdosta Regional Airport",
    "Valley International Airport": "Valley International Airport",
    "Waco Regional Airport": "Waco Regional Airport",
    "Washington Dulles International Airport":
      "Washington Dulles International Airport",
    "Waterloo Regional Airport": "Waterloo Regional Airport",
    "Westchester County Airport": "Westchester County Airport",
    "Westerly State Airport": "Westerly State Airport",
    "Wichita Dwight D. Eisenhower National Airport (Wichita Mid-Continent Airport)":
      "Wichita Dwight D. Eisenhower National Airport (Wichita Mid-Continent Airport)",
    "Wichita Falls Municipal Airport/Sheppard AFB":
      "Wichita Falls Municipal Airport/Sheppard AFB",
    "Wiley Post-Will Rogers Memorial Airport":
      "Wiley Post-Will Rogers Memorial Airport",
    "Wilkes-Barre/Scranton International Airport":
      "Wilkes-Barre/Scranton International Airport",
    "Will Rogers World Airport": "Will Rogers World Airport",
    "William P. Hobby Airport": "William P. Hobby Airport",
    "Wilmington Airport": "Wilmington Airport",
    "Wilmington International Airport": "Wilmington International Airport",
    "Worcester Regional Airport": "Worcester Regional Airport",
    "Wrangell Airport": "Wrangell Airport",
    "Yakutat Airport": "Yakutat Airport",
    "Yampa Valley Airport (Yampa Valley Regional)":
      "Yampa Valley Airport (Yampa Valley Regional)",
    "Yeager Airport": "Yeager Airport",
    "Yellowstone Regional Airport": "Yellowstone Regional Airport",
    "Yuma International Airport": "Yuma International Airport",
  },
  "Day of Week": {
    Sunday: "7",
    Monday: "1",
    Tuesday: "2",
    Wednesday: "3",
    Thursday: "4",
    Friday: "5",
    Saturday: "6",
  },
  "Destination City": {
    Aberdeen: "Aberdeen",
    Abilene: "Abilene",
    Adak: "Adak",
    Agana: "Agana",
    Aguadilla: "Aguadilla",
    Akron: "Akron",
    Albany: "Albany",
    Albuquerque: "Albuquerque",
    Alexandria: "Alexandria",
    Allentown: "Allentown",
    Alpena: "Alpena",
    Amarillo: "Amarillo",
    Anchorage: "Anchorage",
    Appleton: "Appleton",
    "Arcata/Eureka": "Arcata/Eureka",
    Arlington: "Arlington",
    Asheville: "Asheville",
    Aspen: "Aspen",
    Atlanta: "Atlanta",
    "Atlantic City": "Atlantic City",
    Augusta: "Augusta",
    Austin: "Austin",
    Bakersfield: "Bakersfield",
    Baltimore: "Baltimore",
    Bangor: "Bangor",
    Barrow: "Barrow",
    "Baton Rouge": "Baton Rouge",
    "Beaumont/Port Arthur": "Beaumont/Port Arthur",
    Bellingham: "Bellingham",
    Bemidji: "Bemidji",
    Bethel: "Bethel",
    Billings: "Billings",
    Binghamton: "Binghamton",
    Birmingham: "Birmingham",
    Bismarck: "Bismarck",
    Bloomington: "Bloomington",
    Boise: "Boise",
    Boston: "Boston",
    Bozeman: "Bozeman",
    Brainerd: "Brainerd",
    Bristol: "Bristol",
    Brownsville: "Brownsville",
    Brunswick: "Brunswick",
    Buffalo: "Buffalo",
    Burbank: "Burbank",
    Burlington: "Burlington",
    Butte: "Butte",
    Casper: "Casper",
    "Cedar City": "Cedar City",
    "Cedar Rapids": "Cedar Rapids",
    "Champaign/Urbana": "Champaign/Urbana",
    Chantilly: "Chantilly",
    Charleston: "Charleston",
    Charlotte: "Charlotte",
    "Charlotte Amalie": "Charlotte Amalie",
    Charlottesville: "Charlottesville",
    Chattanooga: "Chattanooga",
    Chicago: "Chicago",
    Christiansted: "Christiansted",
    Cleveland: "Cleveland",
    Cody: "Cody",
    "College Station": "College Station",
    "Colorado Springs": "Colorado Springs",
    Columbia: "Columbia",
    Columbus: "Columbus",
    "Columbus-Starkville-West Point": "Columbus-Starkville-West Point",
    Cordova: "Cordova",
    "Corpus Christi": "Corpus Christi",
    Covington: "Covington",
    "Crescent City": "Crescent City",
    Dallas: "Dallas",
    "Dallas-Fort Worth": "Dallas-Fort Worth",
    Dayton: "Dayton",
    "Daytona Beach": "Daytona Beach",
    Deadhorse: "Deadhorse",
    Denver: "Denver",
    "Des Moines": "Des Moines",
    Detroit: "Detroit",
    "Devils Lake": "Devils Lake",
    Dickinson: "Dickinson",
    Dillingham: "Dillingham",
    Dothan: "Dothan",
    Dubuque: "Dubuque",
    Duluth: "Duluth",
    Durango: "Durango",
    Eagle: "Eagle",
    "Eau Claire": "Eau Claire",
    "El Paso": "El Paso",
    Elko: "Elko",
    Elmira: "Elmira",
    Erie: "Erie",
    Escanaba: "Escanaba",
    Eugene: "Eugene",
    Evansville: "Evansville",
    Fairbanks: "Fairbanks",
    Fargo: "Fargo",
    Fayetteville: "Fayetteville",
    "Fayetteville/Springdale/Rogers": "Fayetteville/Springdale/Rogers",
    Flagstaff: "Flagstaff",
    Flint: "Flint",
    "Fort Smith": "Fort Smith",
    "Fort Wayne": "Fort Wayne",
    Fresno: "Fresno",
    "Ft. Lauderdale": "Ft. Lauderdale",
    "Ft. Myers": "Ft. Myers",
    Gainesville: "Gainesville",
    "Garden City": "Garden City",
    Gillette: "Gillette",
    "Grand Forks": "Grand Forks",
    "Grand Island": "Grand Island",
    "Grand Junction": "Grand Junction",
    "Grand Rapids": "Grand Rapids",
    "Great Falls": "Great Falls",
    "Green Bay": "Green Bay",
    Greensboro: "Greensboro",
    Greer: "Greer",
    "Gulfport-Biloxi": "Gulfport-Biloxi",
    Gunnison: "Gunnison",
    Gustavus: "Gustavus",
    Hailey: "Hailey",
    Hancock: "Hancock",
    Harlingen: "Harlingen",
    Harrisburg: "Harrisburg",
    "Hattiesburg-Laurel": "Hattiesburg-Laurel",
    Hayden: "Hayden",
    Hays: "Hays",
    Helena: "Helena",
    Hibbing: "Hibbing",
    Hilo: "Hilo",
    Hobbs: "Hobbs",
    Honolulu: "Honolulu",
    Houston: "Houston",
    Huntsville: "Huntsville",
    Hyannis: "Hyannis",
    "Idaho Falls": "Idaho Falls",
    Indianapolis: "Indianapolis",
    "International Falls": "International Falls",
    "Iron Mountain/Kingsford": "Iron Mountain/Kingsford",
    Islip: "Islip",
    Ithaca: "Ithaca",
    Jackson: "Jackson",
    Jacksonville: "Jacksonville",
    Jamestown: "Jamestown",
    Joplin: "Joplin",
    Juneau: "Juneau",
    Kahului: "Kahului",
    "Kailua/Kona": "Kailua/Kona",
    Kalamazoo: "Kalamazoo",
    Kalispell: "Kalispell",
    "Kansas City": "Kansas City",
    Ketchikan: "Ketchikan",
    "Key West": "Key West",
    Killeen: "Killeen",
    "King Salmon": "King Salmon",
    Knoxville: "Knoxville",
    Kodiak: "Kodiak",
    Kotzebue: "Kotzebue",
    "La Crosse": "La Crosse",
    Lafayette: "Lafayette",
    "Lake Charles": "Lake Charles",
    Lansing: "Lansing",
    Laramie: "Laramie",
    Laredo: "Laredo",
    "Las Vegas": "Las Vegas",
    Latrobe: "Latrobe",
    Lawton: "Lawton",
    Lewiston: "Lewiston",
    Lexington: "Lexington",
    Lihue: "Lihue",
    Lincoln: "Lincoln",
    "Little Rock": "Little Rock",
    "Long Beach": "Long Beach",
    Longview: "Longview",
    "Los Angeles": "Los Angeles",
    Louisville: "Louisville",
    Lubbock: "Lubbock",
    Madison: "Madison",
    "Mammoth Lakes": "Mammoth Lakes",
    Manchester: "Manchester",
    Manhattan: "Manhattan",
    Marquette: "Marquette",
    "Marthas Vineyard": "Marthas Vineyard",
    McAllen: "McAllen",
    Medford: "Medford",
    Melbourne: "Melbourne",
    Memphis: "Memphis",
    Meridian: "Meridian",
    Miami: "Miami",
    Midland: "Midland",
    Milwaukee: "Milwaukee",
    Minneapolis: "Minneapolis",
    Minot: "Minot",
    Missoula: "Missoula",
    Moab: "Moab",
    Mobile: "Mobile",
    Moline: "Moline",
    Monroe: "Monroe",
    Monterey: "Monterey",
    Montgomery: "Montgomery",
    Montrose: "Montrose",
    Mosinee: "Mosinee",
    Muskegon: "Muskegon",
    "Myrtle Beach": "Myrtle Beach",
    Nantucket: "Nantucket",
    Nashville: "Nashville",
    "New Bern": "New Bern",
    "New Orleans": "New Orleans",
    "New York": "New York",
    Newark: "Newark",
    Newburgh: "Newburgh",
    "Newport News": "Newport News",
    "Niagara Falls": "Niagara Falls",
    Nome: "Nome",
    Norfolk: "Norfolk",
    "North Bend": "North Bend",
    Oakland: "Oakland",
    "Oklahoma City": "Oklahoma City",
    Omaha: "Omaha",
    Ontario: "Ontario",
    Orlando: "Orlando",
    Paducah: "Paducah",
    "Pago Pago": "Pago Pago",
    "Palm Springs": "Palm Springs",
    "Panama City": "Panama City",
    Pasco: "Pasco",
    Pellston: "Pellston",
    Pensacola: "Pensacola",
    Peoria: "Peoria",
    Petersburg: "Petersburg",
    Philadelphia: "Philadelphia",
    Phoenix: "Phoenix",
    Pittsburgh: "Pittsburgh",
    Plattsburgh: "Plattsburgh",
    Pocatello: "Pocatello",
    Ponce: "Ponce",
    Portland: "Portland",
    Providence: "Providence",
    Pueblo: "Pueblo",
    Raleigh: "Raleigh",
    "Rapid City": "Rapid City",
    Redding: "Redding",
    Redmond: "Redmond",
    Reno: "Reno",
    Rhinelander: "Rhinelander",
    Richmond: "Richmond",
    Roanoke: "Roanoke",
    Rochester: "Rochester",
    "Rock Springs": "Rock Springs",
    Roswell: "Roswell",
    Sacramento: "Sacramento",
    Saginaw: "Saginaw",
    "Salt Lake City": "Salt Lake City",
    "San Angelo": "San Angelo",
    "San Antonio": "San Antonio",
    "San Diego": "San Diego",
    "San Francisco": "San Francisco",
    "San Jose": "San Jose",
    "San Juan": "San Juan",
    "San Luis Obispo": "San Luis Obispo",
    "Santa Ana": "Santa Ana",
    "Santa Barbara": "Santa Barbara",
    "Santa Fe": "Santa Fe",
    "Santa Maria": "Santa Maria",
    Sarasota: "Sarasota",
    "Sault Ste. Marie": "Sault Ste. Marie",
    Savannah: "Savannah",
    Seattle: "Seattle",
    Shreveport: "Shreveport",
    "Sioux City": "Sioux City",
    "Sioux Falls": "Sioux Falls",
    Sitka: "Sitka",
    "South Bend": "South Bend",
    Spokane: "Spokane",
    Springfield: "Springfield",
    "St Cloud": "St Cloud",
    "St George": "St George",
    "St Louis": "St Louis",
    "St. Augustine": "St. Augustine",
    "State College": "State College",
    Syracuse: "Syracuse",
    Tallahassee: "Tallahassee",
    Tampa: "Tampa",
    Texarkana: "Texarkana",
    Toledo: "Toledo",
    "Traverse City": "Traverse City",
    Trenton: "Trenton",
    Tucson: "Tucson",
    Tulsa: "Tulsa",
    "Twin Falls": "Twin Falls",
    Tyler: "Tyler",
    Valdosta: "Valdosta",
    Valparaiso: "Valparaiso",
    Vernal: "Vernal",
    Waco: "Waco",
    Waterloo: "Waterloo",
    "West Palm Beach": "West Palm Beach",
    "West Yellowstone": "West Yellowstone",
    "White Plains": "White Plains",
    Wichita: "Wichita",
    "Wichita Falls": "Wichita Falls",
    "Wilkes-Barre/Scranton": "Wilkes-Barre/Scranton",
    Williston: "Williston",
    Wilmington: "Wilmington",
    "Windsor Locks": "Windsor Locks",
    Worcester: "Worcester",
    Wrangell: "Wrangell",
    Yakutat: "Yakutat",
    Yuma: "Yuma",
  },
  "Destination State": {
    AK: "AK",
    AL: "AL",
    AR: "AR",
    AS: "AS",
    AZ: "AZ",
    CA: "CA",
    CO: "CO",
    CT: "CT",
    DE: "DE",
    FL: "FL",
    GA: "GA",
    GU: "GU",
    HI: "HI",
    IA: "IA",
    ID: "ID",
    IL: "IL",
    IN: "IN",
    KS: "KS",
    KY: "KY",
    LA: "LA",
    MA: "MA",
    MD: "MD",
    ME: "ME",
    MI: "MI",
    MN: "MN",
    MO: "MO",
    MS: "MS",
    MT: "MT",
    NC: "NC",
    ND: "ND",
    NE: "NE",
    NH: "NH",
    NJ: "NJ",
    NM: "NM",
    NV: "NV",
    NY: "NY",
    OH: "OH",
    OK: "OK",
    OR: "OR",
    PA: "PA",
    PR: "PR",
    RI: "RI",
    SC: "SC",
    SD: "SD",
    TN: "TN",
    TX: "TX",
    UT: "UT",
    VA: "VA",
    VI: "VI",
    VT: "VT",
    WA: "WA",
    WI: "WI",
    WV: "WV",
    WY: "WY",
  },
};
