my_list=[
  "Ancestry recode",
    "Ancestry recode - first entry",
    "Ancestry recode - second entry",
    "Citizenship status",
    "Class of Worker",
    "Self-care difficulty",
    "Hearing difficulty",
    "Decade of entry",
    "Vision difficulty",
    "With a disability",
    "Georgraphic division",
    "Independent living difficulty",
    "Ambulatory difficulty",
    "Veteran Service Disability Rating (percentage)",
    "Veteran Service Disability Rating (checkbox)",
    "Cognitive difficulty",
    "Number of vehicles calculated from JWRI",
    "Ability to speak English",
    "Employment status of parents",
    "Raw labor-force status",
    "Gave birth within past year",
    "Medicare coverage given through the eligibility coverage edit",
    "Medicaid coverage given through the eligibility coverage edit",
    "TRICARE coverage given through the eligibility coverage edit",
    "Recoded field of degree - first entry",
    "Recoded field of degree - second entry",
    "Grandparents living with grandchildren",
    "Length of time responsible for grandchildren",
    "Responsible for grandchildren",
    "Health insurance coverage recode",
    "Insurance through a current or former employer or union",
    "Insurance purchased directly from an insurance company",
    "Medicare, for people 65 and older, or people with certain disabilities",
    "Medicaid, Medical Assistance, or any kind of government-assistance plan for those with low incomes or a disability",
    "TRICARE or other military health care",
    "VA (Health Insurance through VA Health Care)",
    "Indian Health Service",
    "Hispanic, Detailed",
    "Industry recode",
    "Vehicle occupancy (to work)",
    "Means of transportation to work",
    "Language other than English spoken at home",
    "Language other than English spoken at home",
    "Marital status",
    "Divorced in the past 12 months",
    "Married in the past 12 months",
    "Number of times married",
    "Widowed in the past 12 months",
    "Mobility status (lived here 1 year ago)",
    "Migration recode - State or foreign country code",
    "Military service",
    "Served September 2001 or later",
    "Served August 1990 - August 2001 (including Persian Gulf War)",
    "Served May 1975 - July 1990",
    "Served Vietnam era (August 1964 - April 1975)",
    "Served February 1955 - July 1964",
    "Served Korean War (July 1950 - January 1955)",
    "Served January 1947 - June 1950",
    "Served World War II (December 1941 - December 1946)",
    "Served November 1941 or earlier",
    "Married, spouse present/spouse absent",
    "Industry group",
    "Nativity",
    "Nativity of parent",
    "Temporary absence from work",
    "Available for Work",
    "On layoff from work",
    "Looking for work",
    "Informed of recall",
    "Own child",
    "Occupation group",
    "Presence and age of own children",
    "Place of birth",
    "Place of work PUM area code",
    "Place of work - State or foreign country recode",
    "Private health insurance coverage",
    "Public health coverage",
    "Public use microdata area code",
    "Quarter of birth",
    "Race/Ethnicity",
    "American Indian and Alaska Native",
    "Asian",
    "Black",
    "Native Hawaiian",
    "Other Pacific Islander",
    "Some other race",
    "White",
    "Related child",
    "Region",
    "Relationship to reference person",
    "record type",
    "School enrollment",
    "Grade level attending",
    "Educational attainment",
    "Field of degree - Science and Engineering flag",
    "Field of degree - Science and Engineering Related flag",
    "Sex",
    "Subfamily number",
    "Subfamily relationship",
    "Standard Occupational Classification",
    "State code",
    "Veteran Period of Service",
    "World area of birth (2005-2017 categories)",
    "When last worked",
    "Weeks worked during past 12 months",
    "Worked last week",
    "Age",
    "Usual hours worked per week past 12 months",
    "Years since divorce",
  ]
my_list.sort()



for item in my_list:
    print(f'"{item}",')